/*
 * startView.java
 *
 * Created on 8. Februar 2008, 16:49
 */

package mp3.classes.visual.sub;

import mp3.classes.interfaces.Constants;
//import mp3.classes.objects.ungrouped.MyData;
import mp3.classes.visual.main.mainframe;
import mp4.einstellungen.Einstellungen;


/**
 *
 * @author  anti43
 */
public class startView extends javax.swing.JPanel {
    private mainframe mainframe;
    
    /** Creates new form startView */
    public startView() {
        initComponents(); 
        
        jLabel7.setText(Einstellungen.instanceOf().getVersion());
    }

    public startView(mainframe aThis) {
         initComponents();
         jLabel8.setText(jLabel8.getText() + Constants.VERSION + " " + Constants.TITLE);
         jLabel7.setText("Version: " + Einstellungen.instanceOf().getVersion());
         mainframe= aThis;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

jLabel1 = new javax.swing.JLabel();
jPanel2 = new javax.swing.JPanel();
jPanel3 = new javax.swing.JPanel();
jLabel2 = new javax.swing.JLabel();
jLabel5 = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
jTextArea1 = new javax.swing.JTextArea();
jLabel6 = new javax.swing.JLabel();
jLabel7 = new javax.swing.JLabel();
jPanel4 = new javax.swing.JPanel();
jLabel3 = new javax.swing.JLabel();
jLabel8 = new javax.swing.JLabel();

setLayout(new java.awt.BorderLayout());

jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
jLabel1.setText("Willkommen zur MP Kunden und Rechnungsverwaltung!");
add(jLabel1, java.awt.BorderLayout.CENTER);

jPanel3.setBackground(new java.awt.Color(255, 255, 255));
jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
jLabel2.setText("MP Kunden und Rechnungsverwaltung");

jLabel5.setForeground(new java.awt.Color(0, 51, 51));

jScrollPane1.setBackground(new java.awt.Color(0, 51, 51));
jScrollPane1.setBorder(null);
jScrollPane1.setForeground(new java.awt.Color(0, 51, 51));
jScrollPane1.setAutoscrolls(true);
jScrollPane1.setOpaque(false);

jTextArea1.setColumns(20);
jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
jTextArea1.setLineWrap(true);
jTextArea1.setRows(5);
jTextArea1.setText("Apache Derby\nCopyright 2004-2007 The Apache Software Foundation\n\n\nMicroba \nCopyright (c) 2005-2006, Michael Baranov\nAll rights reserved.\n\n\niText\nPortions created by the Initial Developer are \nCopyright (C) 1999, 2000, 2001, 2002 by Bruno Lowagie.\nAll Rights Reserved.\nPortions created by the Co-Developer\nare Copyright (C) 2000, 2001, 2002 by Paulo Soares. \nAll Rights Reserved.\n\n\nOstermillerUtils\nCopyright (C) 2002-2004 Stephen Ostermiller\n\n\nSuperCsv\nCopyright 2007, Kasper B. Graversen\n\n\nTinyLaF\n© 2000 - 2007 Hans Bickel \n\n\nKDE Crystal Diamond Icons- by paolino");
jTextArea1.setWrapStyleWord(true);
jTextArea1.setBorder(null);
jTextArea1.setDisabledTextColor(new java.awt.Color(0, 51, 51));
jTextArea1.setEnabled(false);
jTextArea1.setFocusable(false);
jScrollPane1.setViewportView(jTextArea1);

jLabel6.setFont(new java.awt.Font("Arial", 0, 12));
jLabel6.setText("Diese GPL Software enthält freie Bibliotheken anderer Programmierer.");

jLabel7.setText("Version:");

jPanel4.setBackground(new java.awt.Color(255, 255, 255));
jPanel4.setLayout(new java.awt.BorderLayout());

jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
jLabel3.setText("Willkommen!");
jPanel4.add(jLabel3, java.awt.BorderLayout.CENTER);

jLabel8.setText("MP is Free Software released under the GNU/GPL License. ");

javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
jPanel3.setLayout(jPanel3Layout);
jPanel3Layout.setHorizontalGroup(
jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel3Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel3Layout.createSequentialGroup()
.addComponent(jLabel2)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel7))
.addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
.addGroup(jPanel3Layout.createSequentialGroup()
.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel5)
.addGroup(jPanel3Layout.createSequentialGroup()
.addGap(6, 6, 6)
.addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(191, 191, 191)))
.addContainerGap())
);
jPanel3Layout.setVerticalGroup(
jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel2)
.addComponent(jLabel7))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel6)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel3Layout.createSequentialGroup()
.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jLabel5)
.addComponent(jLabel8)))
.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
.addContainerGap())
);

javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
jPanel2.setLayout(jPanel2Layout);
jPanel2Layout.setHorizontalGroup(
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel2Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);
jPanel2Layout.setVerticalGroup(
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel2Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addContainerGap())
);

add(jPanel2, java.awt.BorderLayout.CENTER);
}// </editor-fold>//GEN-END:initComponents
    
    
// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel2;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel5;
private javax.swing.JLabel jLabel6;
private javax.swing.JLabel jLabel7;
private javax.swing.JLabel jLabel8;
private javax.swing.JPanel jPanel2;
private javax.swing.JPanel jPanel3;
private javax.swing.JPanel jPanel4;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JTextArea jTextArea1;
// End of variables declaration//GEN-END:variables
    
}
