/*
 *  This file is part of YaBS.
 *
 *      YaBS is free software: you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation, either version 3 of the License, or
 *      (at your option) any later version.
 *
 *      YaBS is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with YaBS.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * GeneralListPanel.java
 *
 * Created on 03.04.2009, 15:26:37
 */
package mpv5.ui.dialogs.subcomponents;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.table.TableCellRenderer;
import mpv5.data.PropertyStore;
import mpv5.db.common.Context;
import mpv5.db.common.DatabaseObject;
import mpv5.db.common.NodataFoundException;
import mpv5.db.objects.ScheduleTypes;
import mpv5.db.objects.User;
import mpv5.globals.Messages;
import mpv5.logging.Log;
import mpv5.ui.dialogs.ControlApplet;
import mpv5.ui.dialogs.Popup;
import mpv5.ui.panels.MPControlPanel;
import mpv5.utils.models.MPTableModel;
import mpv5.utils.renderer.TableCellRendererForDatabaseObjects;
import mpv5.utils.tables.TableFormat;

/**
 *
 *
 */
public class ControlPanel_Schedule extends javax.swing.JPanel implements ControlApplet {

    private static final long serialVersionUID = 1L;
    TableCellRendererForDatabaseObjects rend = new TableCellRendererForDatabaseObjects();
    private PropertyStore oldvalues;
    private ScheduleTypes s;

    /**
     * Creates new form GeneralListPanel
     */
    public ControlPanel_Schedule() {
        initComponents();

        labeledCombobox2.setContext(Context.getUser());
        labeledCombobox2.setSearchEnabled(true);
        labeledCombobox2.setEditable(true);
        labeledCombobox2.triggerSearch();

        bill_warn.setLabelWidth(300);
        initTable();
        setData();
        loadPropertys();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labeledCombobox2 = new mpv5.ui.beans.LabeledCombobox();
        jLabel1 = new javax.swing.JLabel();
        labeledTextField2 = new mpv5.ui.beans.LabeledTextField();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        copy = new javax.swing.JButton();
        copy1 = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new  mpv5.ui.misc.MPTable(this) {
            public Component prepareRenderer(TableCellRenderer renderer,
                int rowIndex, int vColIndex) {
                Component c = super.prepareRenderer(renderer, rowIndex, vColIndex);
                if (c instanceof JComponent) {
                    JComponent jc = (JComponent)c;
                    jc.setToolTipText(String.valueOf(getValueAt(rowIndex, vColIndex)));
                }
                return c;
            }
        };
        jPanel4 = new javax.swing.JPanel();
        use_offers = new javax.swing.JCheckBox();
        hide_offers = new javax.swing.JCheckBox();
        use_orders = new javax.swing.JCheckBox();
        hide_orders = new javax.swing.JCheckBox();
        use_confi = new javax.swing.JCheckBox();
        hide_confi = new javax.swing.JCheckBox();
        use_deliv = new javax.swing.JCheckBox();
        hide_deliv = new javax.swing.JCheckBox();
        use_bills = new javax.swing.JCheckBox();
        hide_bills = new javax.swing.JCheckBox();
        use_part = new javax.swing.JCheckBox();
        hide_part = new javax.swing.JCheckBox();
        use_deposit = new javax.swing.JCheckBox();
        hide_deposit = new javax.swing.JCheckBox();
        use_rev = new javax.swing.JCheckBox();
        hide_rev = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        offer_warn = new mpv5.ui.beans.LabeledTextField();
        order_warn = new mpv5.ui.beans.LabeledTextField();
        confi_warn = new mpv5.ui.beans.LabeledTextField();
        deliv_warn = new mpv5.ui.beans.LabeledTextField();
        bill_warn = new mpv5.ui.beans.LabeledTextField();
        part_warn = new mpv5.ui.beans.LabeledTextField();
        deposit_warn = new mpv5.ui.beans.LabeledTextField();
        rev_warn = new mpv5.ui.beans.LabeledTextField();
        jPanel7 = new javax.swing.JPanel();
        offer_alert = new mpv5.ui.beans.LabeledTextField();
        order_alert = new mpv5.ui.beans.LabeledTextField();
        confi_alert = new mpv5.ui.beans.LabeledTextField();
        deliv_alert = new mpv5.ui.beans.LabeledTextField();
        bill_alert = new mpv5.ui.beans.LabeledTextField();
        part_alert = new mpv5.ui.beans.LabeledTextField();
        deposit_alert = new mpv5.ui.beans.LabeledTextField();
        rev_alert = new mpv5.ui.beans.LabeledTextField();
        jPanel6 = new javax.swing.JPanel();
        apply = new javax.swing.JButton();
        save = new javax.swing.JButton();
        advanced = new javax.swing.JButton();

        java.util.ResourceBundle bundle =  mpv5.i18n.LanguageManager.getBundle(); // NOI18N
        setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("RemindPanel.border.title"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ControlPanel_Schedule.jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        labeledCombobox2.set_Label(bundle.getString("ControlPanel_Schedule.labeledCombobox2._Label")); // NOI18N
        labeledCombobox2.setName("labeledCombobox2"); // NOI18N

        jLabel1.setText(bundle.getString("ControlPanel_Schedule.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        labeledTextField2.set_Label(bundle.getString("ControlPanel_Schedule.labeledTextField2._Label")); // NOI18N
        labeledTextField2.setName("labeledTextField2"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labeledCombobox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labeledTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeledCombobox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labeledTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName("jPanel2"); // NOI18N

        add.setText(bundle.getString("ControlPanel_Schedule.add.text")); // NOI18N
        add.setName("add"); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);

        copy.setText(bundle.getString("ControlPanel_Schedule.copy.text")); // NOI18N
        copy.setToolTipText(bundle.getString("ControlPanel_Schedule.copy.toolTipText")); // NOI18N
        copy.setName("copy"); // NOI18N
        copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyActionPerformed(evt);
            }
        });
        jPanel2.add(copy);

        copy1.setText(bundle.getString("ControlPanel_Schedule.copy1.text")); // NOI18N
        copy1.setToolTipText(bundle.getString("ControlPanel_Schedule.copy1.toolTipText")); // NOI18N
        copy1.setName("copy1"); // NOI18N
        copy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copy1ActionPerformed(evt);
            }
        });
        jPanel2.add(copy1);

        remove.setText(bundle.getString("ControlPanel_Schedule.remove.text")); // NOI18N
        remove.setName("remove"); // NOI18N
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel2.add(remove);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ControlPanel_Schedule.jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoCreateRowSorter(true);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ControlPanel_Schedule.jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        use_offers.setText(bundle.getString("ControlPanel_Schedule.use_offers.text")); // NOI18N
        use_offers.setName("use_offers"); // NOI18N
        use_offers.setPreferredSize(new java.awt.Dimension(260, 20));
        use_offers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                use_offersActionPerformed(evt);
            }
        });
        jPanel4.add(use_offers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        hide_offers.setText(bundle.getString("ControlPanel_Schedule.hide_offers.text")); // NOI18N
        hide_offers.setEnabled(false);
        hide_offers.setName("hide_offers"); // NOI18N
        hide_offers.setPreferredSize(new java.awt.Dimension(350, 20));
        jPanel4.add(hide_offers, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        use_orders.setText(bundle.getString("ControlPanel_Schedule.use_orders.text")); // NOI18N
        use_orders.setName("use_orders"); // NOI18N
        use_orders.setPreferredSize(new java.awt.Dimension(260, 20));
        use_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                use_ordersActionPerformed(evt);
            }
        });
        jPanel4.add(use_orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        hide_orders.setText(bundle.getString("ControlPanel_Schedule.hide_orders.text")); // NOI18N
        hide_orders.setEnabled(false);
        hide_orders.setName("hide_orders"); // NOI18N
        hide_orders.setPreferredSize(new java.awt.Dimension(350, 20));
        jPanel4.add(hide_orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        use_confi.setText(bundle.getString("ControlPanel_Schedule.use_confi.text")); // NOI18N
        use_confi.setName("use_confi"); // NOI18N
        use_confi.setPreferredSize(new java.awt.Dimension(260, 20));
        use_confi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                use_confiActionPerformed(evt);
            }
        });
        jPanel4.add(use_confi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        hide_confi.setText(bundle.getString("ControlPanel_Schedule.hide_confi.text")); // NOI18N
        hide_confi.setEnabled(false);
        hide_confi.setName("hide_confi"); // NOI18N
        hide_confi.setPreferredSize(new java.awt.Dimension(350, 20));
        jPanel4.add(hide_confi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        use_deliv.setText(bundle.getString("ControlPanel_Schedule.use_deliv.text")); // NOI18N
        use_deliv.setName("use_deliv"); // NOI18N
        use_deliv.setPreferredSize(new java.awt.Dimension(260, 20));
        use_deliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                use_delivActionPerformed(evt);
            }
        });
        jPanel4.add(use_deliv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        hide_deliv.setText(bundle.getString("ControlPanel_Schedule.hide_deliv.text")); // NOI18N
        hide_deliv.setEnabled(false);
        hide_deliv.setName("hide_deliv"); // NOI18N
        hide_deliv.setPreferredSize(new java.awt.Dimension(350, 20));
        jPanel4.add(hide_deliv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        use_bills.setText(bundle.getString("ControlPanel_Schedule.bills.text")); // NOI18N
        use_bills.setName("bills"); // NOI18N
        use_bills.setPreferredSize(new java.awt.Dimension(260, 20));
        use_bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                use_billsActionPerformed(evt);
            }
        });
        jPanel4.add(use_bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        hide_bills.setText(bundle.getString("ControlPanel_Schedule.hide_bills.text")); // NOI18N
        hide_bills.setEnabled(false);
        hide_bills.setName("hide_bills"); // NOI18N
        hide_bills.setPreferredSize(new java.awt.Dimension(350, 20));
        jPanel4.add(hide_bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        use_part.setText(bundle.getString("ControlPanel_Schedule.use_part.text")); // NOI18N
        use_part.setName("use_part"); // NOI18N
        use_part.setPreferredSize(new java.awt.Dimension(260, 20));
        use_part.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                use_partActionPerformed(evt);
            }
        });
        jPanel4.add(use_part, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        hide_part.setText(bundle.getString("ControlPanel_Schedule.hide_part.text")); // NOI18N
        hide_part.setEnabled(false);
        hide_part.setName("hide_part"); // NOI18N
        hide_part.setPreferredSize(new java.awt.Dimension(350, 20));
        jPanel4.add(hide_part, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        use_deposit.setText(bundle.getString("ControlPanel_Schedule.use_deposit.text")); // NOI18N
        use_deposit.setName("use_deposit"); // NOI18N
        use_deposit.setPreferredSize(new java.awt.Dimension(260, 20));
        use_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                use_depositActionPerformed(evt);
            }
        });
        jPanel4.add(use_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        hide_deposit.setText(bundle.getString("ControlPanel_Schedule.hide_deposit.text")); // NOI18N
        hide_deposit.setEnabled(false);
        hide_deposit.setName("hide_deposit"); // NOI18N
        hide_deposit.setPreferredSize(new java.awt.Dimension(350, 20));
        jPanel4.add(hide_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        use_rev.setText(bundle.getString("ControlPanel_Schedule.use_rev.text")); // NOI18N
        use_rev.setName("use_rev"); // NOI18N
        use_rev.setPreferredSize(new java.awt.Dimension(260, 20));
        use_rev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                use_revActionPerformed(evt);
            }
        });
        jPanel4.add(use_rev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        hide_rev.setText(bundle.getString("ControlPanel_Schedule.hide_rev.text")); // NOI18N
        hide_rev.setEnabled(false);
        hide_rev.setName("hide_rev"); // NOI18N
        hide_rev.setPreferredSize(new java.awt.Dimension(350, 20));
        jPanel4.add(hide_rev, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ControlPanel_Schedule.jPanel8.border.title"))); // NOI18N
        jPanel8.setName("jPanel8"); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ControlPanel_Schedule.jPanel5.border.title"))); // NOI18N
        jPanel5.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel5.setMinimumSize(new java.awt.Dimension(400, 49));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 240));

        offer_warn.set_Label(bundle.getString("ControlPanel_Schedule.offer_warn._Label")); // NOI18N
        offer_warn.set_Text(bundle.getString("ControlPanel_Schedule.offer_warn._Text")); // NOI18N
        offer_warn.setName("offer_warn"); // NOI18N
        offer_warn.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel5.add(offer_warn);

        order_warn.set_Label(bundle.getString("ControlPanel_Schedule.order_warn._Label")); // NOI18N
        order_warn.set_Text(bundle.getString("ControlPanel_Schedule.order_warn._Text")); // NOI18N
        order_warn.setName("order_warn"); // NOI18N
        order_warn.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel5.add(order_warn);

        confi_warn.set_Label(bundle.getString("ControlPanel_Schedule.confi_warn._Label")); // NOI18N
        confi_warn.set_Text(bundle.getString("ControlPanel_Schedule.confi_warn._Text")); // NOI18N
        confi_warn.setName("confi_warn"); // NOI18N
        confi_warn.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel5.add(confi_warn);

        deliv_warn.set_Label(bundle.getString("ControlPanel_Schedule.deliv_warn._Label")); // NOI18N
        deliv_warn.set_Text(bundle.getString("ControlPanel_Schedule.deliv_warn._Text")); // NOI18N
        deliv_warn.setName("deliv_warn"); // NOI18N
        deliv_warn.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel5.add(deliv_warn);

        bill_warn.set_Label(bundle.getString("ControlPanel_Schedule.bill_warn._Label")); // NOI18N
        bill_warn.set_Text(bundle.getString("ControlPanel_Schedule.bill_warn._Text")); // NOI18N
        bill_warn.setName("bill_warn"); // NOI18N
        bill_warn.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel5.add(bill_warn);

        part_warn.set_Label(bundle.getString("ControlPanel_Schedule.part_warn._Label")); // NOI18N
        part_warn.set_Text(bundle.getString("ControlPanel_Schedule.part_warn._Text")); // NOI18N
        part_warn.setName("part_warn"); // NOI18N
        part_warn.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel5.add(part_warn);

        deposit_warn.set_Label(bundle.getString("ControlPanel_Schedule.deposit_warn._Label")); // NOI18N
        deposit_warn.set_Text(bundle.getString("ControlPanel_Schedule.deposit_warn._Text")); // NOI18N
        deposit_warn.setName("deposit_warn"); // NOI18N
        deposit_warn.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel5.add(deposit_warn);

        rev_warn.set_Label(bundle.getString("ControlPanel_Schedule.rev_warn._Label")); // NOI18N
        rev_warn.set_Text(bundle.getString("ControlPanel_Schedule.rev_warn._Text")); // NOI18N
        rev_warn.setName("rev_warn"); // NOI18N
        rev_warn.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel5.add(rev_warn);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ControlPanel_Schedule.jPanel7.border.title"))); // NOI18N
        jPanel7.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel7.setMinimumSize(new java.awt.Dimension(400, 49));
        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 240));

        offer_alert.set_Label(bundle.getString("ControlPanel_Schedule.offer_alert._Label")); // NOI18N
        offer_alert.set_Text(bundle.getString("ControlPanel_Schedule.offer_alert._Text")); // NOI18N
        offer_alert.setName("offer_alert"); // NOI18N
        offer_alert.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel7.add(offer_alert);

        order_alert.set_Label(bundle.getString("ControlPanel_Schedule.order_alert._Label")); // NOI18N
        order_alert.set_Text(bundle.getString("ControlPanel_Schedule.order_alert._Text")); // NOI18N
        order_alert.setName("order_alert"); // NOI18N
        order_alert.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel7.add(order_alert);

        confi_alert.set_Label(bundle.getString("ControlPanel_Schedule.confi_alert._Label")); // NOI18N
        confi_alert.set_Text(bundle.getString("ControlPanel_Schedule.confi_alert._Text")); // NOI18N
        confi_alert.setName("confi_alert"); // NOI18N
        confi_alert.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel7.add(confi_alert);

        deliv_alert.set_Label(bundle.getString("ControlPanel_Schedule.deliv_alert._Label")); // NOI18N
        deliv_alert.set_Text(bundle.getString("ControlPanel_Schedule.deliv_alert._Text")); // NOI18N
        deliv_alert.setName("deliv_alert"); // NOI18N
        deliv_alert.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel7.add(deliv_alert);

        bill_alert.set_Label(bundle.getString("ControlPanel_Schedule.bill_alert._Label")); // NOI18N
        bill_alert.set_Text(bundle.getString("ControlPanel_Schedule.bill_alert._Text")); // NOI18N
        bill_alert.setName("bill_alert"); // NOI18N
        bill_alert.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel7.add(bill_alert);

        part_alert.set_Label(bundle.getString("ControlPanel_Schedule.part_alert._Label")); // NOI18N
        part_alert.set_Text(bundle.getString("ControlPanel_Schedule.part_alert._Text")); // NOI18N
        part_alert.setName("part_alert"); // NOI18N
        part_alert.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel7.add(part_alert);

        deposit_alert.set_Label(bundle.getString("ControlPanel_Schedule.deposit_alert._Label")); // NOI18N
        deposit_alert.set_Text(bundle.getString("ControlPanel_Schedule.deposit_alert._Text")); // NOI18N
        deposit_alert.setName("deposit_alert"); // NOI18N
        deposit_alert.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel7.add(deposit_alert);

        rev_alert.set_Label(bundle.getString("ControlPanel_Schedule.rev_alert._Label")); // NOI18N
        rev_alert.set_Text(bundle.getString("ControlPanel_Schedule.rev_alert._Text")); // NOI18N
        rev_alert.setName("rev_alert"); // NOI18N
        rev_alert.setPreferredSize(new java.awt.Dimension(175, 20));
        jPanel7.add(rev_alert);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        apply.setText(bundle.getString("ControlPanel_Schedule.apply.text")); // NOI18N
        apply.setName("apply"); // NOI18N
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });
        jPanel6.add(apply);

        save.setText(bundle.getString("ControlPanel_Schedule.save.text")); // NOI18N
        save.setName("save"); // NOI18N
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel6.add(save);

        advanced.setText(bundle.getString("ControlPanel_Schedule.advanced.text")); // NOI18N
        advanced.setName("advanced"); // NOI18N
        advanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedActionPerformed(evt);
            }
        });
        jPanel6.add(advanced);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        ScheduleTypes s1 = new ScheduleTypes();
        s1.setCname(labeledTextField2.getText());
        s1.setUser(Integer.parseInt(labeledCombobox2.getSelectedItem().getId()));
        s1.save();
        setData();
}//GEN-LAST:event_addActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        s = (ScheduleTypes) ((MPTableModel) jTable1.getModel()).getValueAt(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()), 0);
        labeledTextField2.setText(s.__getCname());
        labeledCombobox2.setSelectedItem(User.getUsername(s.__getUserSids()));
    }//GEN-LAST:event_jTable1MouseClicked

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        if (s.delete()) {
            ((MPTableModel) jTable1.getModel()).removeRow(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()));
        }
    }//GEN-LAST:event_removeActionPerformed

    private void copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyActionPerformed
        ScheduleTypes s2 = new ScheduleTypes();
        s2.setCname(labeledTextField2.getText());
        s2.setUser(User.getCurrentUser().getID());
        s2.save();
        setData();
    }//GEN-LAST:event_copyActionPerformed

    private void copy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copy1ActionPerformed
        s.setCname(labeledTextField2.getText());
        s.setUser(User.getCurrentUser().getID());
        s.save();
        setData();
    }//GEN-LAST:event_copy1ActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        setPropertys();
    }//GEN-LAST:event_applyActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        setPropertys();
        mpv5.db.objects.User.getCurrentUser().saveProperties();
        Popup.notice(Messages.RESTART_REQUIRED);
    }//GEN-LAST:event_saveActionPerformed

    private void advancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedActionPerformed
        ControlPanel_AdvancedUserProperties c = new ControlPanel_AdvancedUserProperties();
        MPControlPanel.instanceOf().openDetails(c);
    }//GEN-LAST:event_advancedActionPerformed

    private void use_offersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_use_offersActionPerformed
        hide_offers.setEnabled(use_offers.isSelected());
    }//GEN-LAST:event_use_offersActionPerformed

    private void use_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_use_ordersActionPerformed
        hide_orders.setEnabled(use_orders.isSelected());
    }//GEN-LAST:event_use_ordersActionPerformed

    private void use_confiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_use_confiActionPerformed
        hide_confi.setEnabled(use_confi.isSelected());
    }//GEN-LAST:event_use_confiActionPerformed

    private void use_delivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_use_delivActionPerformed
        hide_deliv.setEnabled(use_deliv.isSelected());
    }//GEN-LAST:event_use_delivActionPerformed

    private void use_billsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_use_billsActionPerformed
        hide_bills.setEnabled(use_bills.isSelected());
    }//GEN-LAST:event_use_billsActionPerformed

    private void use_partActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_use_partActionPerformed
        hide_part.setEnabled(use_part.isSelected());
    }//GEN-LAST:event_use_partActionPerformed

    private void use_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_use_depositActionPerformed
        hide_deposit.setEnabled(use_deposit.isSelected());
    }//GEN-LAST:event_use_depositActionPerformed

    private void use_revActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_use_revActionPerformed
                hide_rev.setEnabled(use_rev.isSelected());
    }//GEN-LAST:event_use_revActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton advanced;
    private javax.swing.JButton apply;
    private mpv5.ui.beans.LabeledTextField bill_alert;
    private mpv5.ui.beans.LabeledTextField bill_warn;
    private mpv5.ui.beans.LabeledTextField confi_alert;
    private mpv5.ui.beans.LabeledTextField confi_warn;
    private javax.swing.JButton copy;
    private javax.swing.JButton copy1;
    private mpv5.ui.beans.LabeledTextField deliv_alert;
    private mpv5.ui.beans.LabeledTextField deliv_warn;
    private mpv5.ui.beans.LabeledTextField deposit_alert;
    private mpv5.ui.beans.LabeledTextField deposit_warn;
    private javax.swing.JCheckBox hide_bills;
    private javax.swing.JCheckBox hide_confi;
    private javax.swing.JCheckBox hide_deliv;
    private javax.swing.JCheckBox hide_deposit;
    private javax.swing.JCheckBox hide_offers;
    private javax.swing.JCheckBox hide_orders;
    private javax.swing.JCheckBox hide_part;
    private javax.swing.JCheckBox hide_rev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private mpv5.ui.beans.LabeledCombobox labeledCombobox2;
    private mpv5.ui.beans.LabeledTextField labeledTextField2;
    private mpv5.ui.beans.LabeledTextField offer_alert;
    private mpv5.ui.beans.LabeledTextField offer_warn;
    private mpv5.ui.beans.LabeledTextField order_alert;
    private mpv5.ui.beans.LabeledTextField order_warn;
    private mpv5.ui.beans.LabeledTextField part_alert;
    private mpv5.ui.beans.LabeledTextField part_warn;
    private javax.swing.JButton remove;
    private mpv5.ui.beans.LabeledTextField rev_alert;
    private mpv5.ui.beans.LabeledTextField rev_warn;
    private javax.swing.JButton save;
    private javax.swing.JCheckBox use_bills;
    private javax.swing.JCheckBox use_confi;
    private javax.swing.JCheckBox use_deliv;
    private javax.swing.JCheckBox use_deposit;
    private javax.swing.JCheckBox use_offers;
    private javax.swing.JCheckBox use_orders;
    private javax.swing.JCheckBox use_part;
    private javax.swing.JCheckBox use_rev;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getAndRemoveActionPanel() {
        this.remove(jPanel2);
        validate();
        return jPanel2;
    }

    @Override
    public void setValues(PropertyStore values) {
        oldvalues = values;
    }

    @Override
    public String getUname() {
        return "StageTypes";
    }

    @Override
    public void reset() {
        setValues(oldvalues);
    }

    private void setData() {
        try {
            final ArrayList<DatabaseObject> STypes = DatabaseObject.getObjects(Context.getScheduleTypes(), true);
            Object[][] data = new Object[STypes.size()][3];

            for (int i = 0; i < STypes.size(); i++) {
                ScheduleTypes st = (ScheduleTypes) STypes.get(i);
                data[i][0] = (DatabaseObject) st;
                data[i][1] = User.getUsername(st.__getUserSids());
                data[i][2] = st.__getCname();
            }
            MPTableModel m = new MPTableModel(data);
            m.setTypes(new Class[]{DatabaseObject.class,
                        String.class,
                        String.class});
            jTable1.setModel(m);
            jTable1.getColumn(m.getColumnIdentifiers().get(0)).setMinWidth(0);
            jTable1.getColumn(m.getColumnIdentifiers().get(0)).setMaxWidth(0);
            jTable1.getColumn(m.getColumnIdentifiers().get(0)).setResizable(false);
        } catch (NodataFoundException ex) {
            Log.Debug(this, ex);
        }
    }

    private void initTable() {
        jTable1.setDefaultRenderer(String.class,
                rend);
        jTable1.setDefaultRenderer(DatabaseObject.class,
                rend);
        TableFormat.hideHeader(jTable1);
    }

    private void setPropertys() {
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("bills.warn.days", bill_warn.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("bills.alert.days", bill_alert.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("order.warn.days", order_warn.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("order.alert.days", order_alert.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("offer.warn.days", offer_warn.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("offer.alert.days", offer_alert.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("deliver.warn.days", deliv_warn.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("deliver.alert.days", deliv_alert.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("confirmation.warn.days", confi_warn.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("confirmation.alert.days", confi_alert.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("partpayment.warn.days", part_warn.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("partpayment.alert.days", part_alert.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("deposit.warn.days", deposit_warn.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("deposit.alert.days", deposit_alert.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("revenue.warn.days", rev_warn.getText());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("revenue.alert.days", rev_alert.getText());
        
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "hideunpaidbills", hide_bills.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "hideunattentedorders", hide_orders.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "hideunacceptedoffers", hide_offers.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "hideunattenteddeliverys", hide_deliv.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "hideunattentedconfirmations", hide_confi.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "hideunattentedrevenues", hide_rev.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "hideunattentedpartpayments", hide_part.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "hideunattenteddeposits", hide_deposit.isSelected());
        
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "usebills", use_bills.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "useorders", use_orders.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "useoffers", use_offers.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "usedeliverys", use_deliv.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "useconfirmations", use_confi.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "userevenues", use_rev.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "usepartpayment", use_part.isSelected());
        mpv5.db.objects.User.getCurrentUser().getProperties().changeProperty("org.openyabs.uiproperty", "usedeposit", use_deposit.isSelected());
    }

    private void loadPropertys() {
        hide_bills.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "hideunpaidbills"));
        hide_orders.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "hideunattentedorders"));
        hide_offers.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "hideunacceptedoffers"));
        hide_deliv.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "hideunattenteddeliverys"));
        hide_confi.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "hideunattentedconfirmations"));
        hide_part.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "hideunattentedpartpayments"));
        hide_deposit.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "hideunattenteddeposits"));
        hide_rev.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "hideunattentedrevenues"));
        
        use_bills.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "usebills"));
        use_orders.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "useorders"));
        use_offers.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "useoffers"));
        use_deliv.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "usedeliverys"));
        use_confi.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "useconfirmations"));
        use_part.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "usepartpayment"));
        use_deposit.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "usedeposit"));
        use_rev.setSelected(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("org.openyabs.uiproperty", "userevenues"));

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("bills.warn.days")) {
            bill_warn.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("bills.warn.days"));
        } else {
            bill_warn.setText("14");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("bills.alert.days")) {
            bill_alert.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("bills.alert.days"));
        } else {
            bill_alert.setText("30");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("order.warn.days")) {
            order_warn.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("order.warn.days"));
        } else {
            order_warn.setText("14");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("order.alert.days")) {
            order_alert.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("order.alert.days"));
        } else {
            order_alert.setText("30");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("offer.warn.days")) {
            offer_warn.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("offer.warn.days"));
        } else {
            offer_warn.setText("14");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("offer.alert.days")) {
            offer_alert.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("offer.alert.days"));
        } else {
            offer_alert.setText("30");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("deliver.warn.days")) {
            deliv_warn.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("deliver.warn.days"));
        } else {
            deliv_warn.setText("14");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("deliver.alert.days")) {
            deliv_alert.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("deliver.alert.days"));
        } else {
            deliv_alert.setText("30");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("confirmation.warn.days")) {
            confi_warn.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("confirmation.warn.days"));
        } else {
            confi_warn.setText("14");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("confirmation.alert.days")) {
            confi_alert.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("confirmation.alert.days"));
        } else {
            confi_alert.setText("30");
        }
        
        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("partpayment.warn.days")) {
           part_warn.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("partpayment.warn.days"));
        } else {
            part_warn.setText("14");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("partpayment.alert.days")) {
            part_alert.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("partpayment.alert.days"));
        } else {
            part_alert.setText("30");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("deposit.warn.days")) {
            deposit_warn.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("deposit.warn.days"));
        } else {
            deposit_warn.setText("14");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("deposit.alert.days")) {
            deposit_alert.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("deposit.alert.days"));
        } else {
            deposit_alert.setText("30");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("revenue.warn.days")) {
            rev_warn.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("revenue.warn.days"));
        } else {
            rev_warn.setText("14");
        }

        if (mpv5.db.objects.User.getCurrentUser().getProperties().hasProperty("revenue.alert.days")) {
            rev_alert.setText(mpv5.db.objects.User.getCurrentUser().getProperties().getProperty("revenue.alert.days"));
        } else {
            rev_alert.setText("30");
        }                                          
        hide_offers.setEnabled(use_offers.isSelected());
        hide_orders.setEnabled(use_orders.isSelected());
        hide_confi.setEnabled(use_confi.isSelected());
        hide_deliv.setEnabled(use_deliv.isSelected());
        hide_bills.setEnabled(use_bills.isSelected());
        hide_part.setEnabled(use_part.isSelected());
        hide_deposit.setEnabled(use_deposit.isSelected());
        hide_rev.setEnabled(use_rev.isSelected());
    }
}
