/*
 * mainframe.java
 *
 * Created on July 11, 2008, 10:08 AM
 */
package mp3.classes.visual.main;

import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import mp3.classes.layer.QueryClass;
import mp3.classes.objects.bill.Bill;
import mp3.classes.objects.eur.Ausgabe;
import mp3.classes.objects.eur.Einnahme;
import mp3.classes.utils.Formater;
import mp3.database.util.Conn;

/**
 *
 * @author  Administrator
 */
public class mainframe extends javax.swing.JFrame {

    private String[][] bills;
    private ArrayList results;
    private String[][] ausgaben;
    private String[][] einnahmen;
    private int count = 0;
    private int err = 0;

    /** Creates new form mainframe */
    public mainframe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Dieses Programm untersucht Ihre MP 3.6x Datenbank auf Konsistenz.");

        jLabel2.setText("Gefundene Probleme:");

        jButton1.setText("Untersuchung starten");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //id, rechnungnummer, gesamtpreis"
    //id,Anzahl,Posten,Mehrwertsteuer,Nettopreis,Bruttopreis

    count = 0;
    err = 0;
    
    results = new ArrayList();
    this.setCursor(Cursor.WAIT_CURSOR);

    jLabel3.setText("Untersuche Rechnungen, " + count + " Datensaetze untersucht.");
    bills = new Bill(QueryClass.instanceOf()).getAll();

    if (bills != null) {
        for (int i = 0; i < bills.length; i++) {

            System.out.println("Untersuche Rechnung mit der ID " + bills[i][0]);
            Object[][] products = new Bill(QueryClass.instanceOf(), bills[i][0]).getProductlistAsArray();

            if(products != null){
            for (int k = 0; k < products.length; k++) {

                if ((Double) products[k][1] != 1d) {

                    results.add(new String[]{"Rechnung Nummer: " + bills[i][1], "Gesamtbetrag neu berechnen lassen!"});

                    err++;
                }

                count++;
            }
            }
        }
    }
    jLabel3.setText("Untersuche Ausgaben, " + count + " Datensaetze untersucht.");

    ausgaben = new Ausgabe().getAll();
    if (ausgaben != null) {
//"preis, datum"
        for (int i = 0; i < ausgaben.length; i++) {
            System.out.println("Untersuche Ausgabe mit der ID " + i);
            try {
                Double.valueOf(ausgaben[i][0]);
            } catch (NumberFormatException numberFormatException) {
                results.add(new String[]{"Ausgabe vom: " + ausgaben[i][1] + " Betrag: " + ausgaben[i][0], "Betrag neu eingeben!"});
                err++;
            }
            count++;
        }
        jLabel3.setText("Untersuche Einnahmen, " + count + " Datensaetze untersucht.");
    }


    einnahmen = new Einnahme().getAll();
//"preis, datum"
    if (einnahmen != null) {
        for (int i = 0; i < einnahmen.length; i++) {
            System.out.println("Untersuche Einnahme mit der ID " + i);
            try {
                Double.valueOf(einnahmen[i][0]);
            } catch (NumberFormatException numberFormatException) {
                results.add(new String[]{"Einnahme vom: " + einnahmen[i][1] + " Betrag: " + einnahmen[i][0], "Betrag neu eingeben!"});
                err++;
            }
            count++;
        }
    }
    jTable1.setModel(new DefaultTableModel(Formater.listToStringArray(results), new String[]{"Datensatz", "Ergebnis"}));

    jLabel3.setText("Untersuchung beendet, " + count + " Datensaetze untersucht. " + err + " Fehler gefunden.");

    System.out.println("Beende Datenbankverbindung...");
    Conn.shutdown();
    QueryClass.kill();
    this.setCursor(Cursor.DEFAULT_CURSOR);
}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
