/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Stockmanager.java
 *
 * Created on Oct 7, 2012, 4:30:52 PM
 */
package mpv5.ui.panels;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import mpv5.db.common.Context;
import mpv5.db.common.DatabaseObject;
import mpv5.db.common.NodataFoundException;
import mpv5.db.objects.Product;
import mpv5.logging.Log;
import mpv5.utils.models.MPTableModel;
import mpv5.utils.tables.TableFormat;

/**
 *
 * @author anti
 */
public class Stockmanager extends javax.swing.JPanel {

    private static Stockmanager me;

    public static Stockmanager instanceOf() {
        if (me == null) {
            me = new Stockmanager();
        }
        return me;
    }
    private final MPTableModel model;
    private int index;

    /** Creates new form Stockmanager */
    public Stockmanager() {
        initComponents();
        model = new MPTableModel(new Class[]{String.class, Integer.class}, new boolean[]{true, true}, new Object[]{"1", "2"});
        model.addRow(100);
        mainTable.setModel(model);
        TableFormat.hideHeader(mainTable);
        TableFormat.resizeCol(mainTable, 1, 100, true);

        String solve = "Solve";
        KeyStroke enter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
        mainTable.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(enter, solve);
        mainTable.getActionMap().put(solve, new EnterAction());
    }

    private class EnterAction extends AbstractAction {

        @Override
        public void actionPerformed(ActionEvent e) {
            TableFormat.stopEditing(mainTable);
            Log.Print("index is "+ index);
            model.setValueAt(1, index, getCurrentAmount(String.valueOf(model.getValueAt(index, 0))) + 1);
            TableFormat.startEditing(mainTable, index++, 0);
        }
    }

    private List<String> getProductKeys() {
        List<String> keys = new ArrayList<String>();
        for (Object[] d : model.getData()) {
            try {
                String key = String.valueOf(d[0]);
                if (key.length() > 0 && !key.equals("null")) {
                    keys.add(key);
                }
            } catch (Exception exception) {
                Log.Debug(exception);
            }
        }
        return keys;
    }

    private int getCurrentAmount(String mkey) {
        Log.Print("getCurrentAmount(String " + mkey + ")");
        for (Object[] d : model.getData()) {
            if (d[0] != null) {
                try {
                    String key = String.valueOf(d[0]);
                    Log.Print(Arrays.asList(d));
                    if (key.equals(mkey)) {
                        if (d[1] == null) {
                            Log.Print("val is null");
                            return 0;
                        }
                        Log.Print("val is " + String.valueOf(d[1]));
                        return Integer.valueOf(String.valueOf(d[1]));
                    }
                } catch (Exception exception) {
                    Log.Debug(exception);
                }
            }
        }
        return 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();

        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mpv5/ui/panels/Bundle"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Stockmanager.jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jButton1.setText(bundle.getString("Stockmanager.jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        mainTable.setName("mainTable"); // NOI18N
        mainTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mainTableKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(mainTable);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        for (Object[] d : model.getData()) {
            try {
                String key = String.valueOf(d[0]);
                if (key.length() > 0 && !key.equals("null")) {
                    BigDecimal val = new BigDecimal(String.valueOf(d[1]));
                    Product dbo = (Product) DatabaseObject.getObject(Context.getProduct(), "ean", key);
                    dbo.setStockvalue(val);
                    dbo.save();
                }
            } catch (Exception exception) {
                Log.Debug(exception);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mainTableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainTableKeyTyped
//        Log.Print(evt);
    }//GEN-LAST:event_mainTableKeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables

    public void start() {
        mainTable.requestFocusInWindow();
        TableFormat.startEditing(mainTable, 0, 0);
    }
}
