  /*
 *  This file is part of YaBS.
 *
 *  YaBS is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  YaBS is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with YaBS.  If not, see <http://www.gnu.org/licenses/>.
 */
package mpv5.db.common;

import javax.swing.UIManager;
import mpv5.db.objects.Account;
import mpv5.globals.Constants;
import mpv5.globals.Messages;

/**
 * 
 */
public class DatabaseInstallation {

    /**
     * This contains the database structure for mpv5
     *
     * As SQL.Views are currently not updateable from DERBY, i use two nearly identical tables here, to store user informations.
     * First one holds a users default data, where the second table holds additional address info.
     *
     */
    public final static String[] DERBY_STRUCTURE = new String[]{
        "CREATE TABLE groups (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), cname VARCHAR(250) UNIQUE NOT NULL,description VARCHAR(750) DEFAULT NULL,defaults VARCHAR(250) DEFAULT NULL,groupsids BIGINT DEFAULT 0,dateadded DATE NOT NULL,reserve1 VARCHAR(500) DEFAULT NULL,intaddedby BIGINT DEFAULT 0, hierarchypath VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL, PRIMARY KEY  (ids))",
        "CREATE TABLE productgroups (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), CONSTRAINT const1 UNIQUE (cname, groupsids), cname VARCHAR(250) NOT NULL,description VARCHAR(750) DEFAULT NULL,defaults VARCHAR(250) DEFAULT NULL,groupsids BIGINT DEFAULT 0, productgroupsids BIGINT DEFAULT 0,dateadded DATE NOT NULL, hierarchypath VARCHAR(500) DEFAULT NULL, reserve1 VARCHAR(500) DEFAULT NULL,intaddedby BIGINT DEFAULT 0, reserve2 VARCHAR(500) DEFAULT NULL, PRIMARY KEY  (ids))",
        "CREATE TABLE history (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250)  NOT NULL, username VARCHAR(250) NOT NULL,dbidentity VARCHAR(25)  NOT NULL, INTitem SMALLINT NOT NULL,groupsids BIGINT DEFAULT 0, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE countries (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), cname VARCHAR(250) NOT NULL, iso SMALLINT  UNIQUE NOT NULL,groupsids BIGINT DEFAULT 1,reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE searchindex (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),dbidentity VARCHAR(25) NOT NULL, groupsids BIGINT, rowID BIGINT NOT NULL,text VARCHAR(5000) DEFAULT NULL)",
        "CREATE TABLE globalsettings (IDS BIGINT DEFAULT 1,  CONSTRAINT const2 UNIQUE (cname, groupsids), cname VARCHAR(250) NOT NULL, groupsids BIGINT DEFAULT 1, value VARCHAR(250) NOT NULL)",
        //Main tables, must have ids, cname, groupsids, dateadded, intaddedby, invisible
        "CREATE TABLE tax (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), cname VARCHAR(250), taxvalue DOUBLE DEFAULT 0,identifier VARCHAR(250) DEFAULT NULL, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,country VARCHAR(50) DEFAULT NULL, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE contacts (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), CONSTRAINT const3 UNIQUE (cnumber, groupsids), cnumber VARCHAR(250) DEFAULT NULL, taxnumber VARCHAR(250), title VARCHAR(250) DEFAULT NULL,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,country VARCHAR(50) DEFAULT NULL, prename VARCHAR(250) DEFAULT NULL, cname VARCHAR(250) DEFAULT NULL, street VARCHAR(250) DEFAULT NULL,zip VARCHAR(50) DEFAULT NULL,city VARCHAR(300) DEFAULT NULL, mainphone VARCHAR(250) DEFAULT NULL,fax VARCHAR(250) DEFAULT NULL,mobilephone VARCHAR(250) DEFAULT NULL,workphone VARCHAR(250) DEFAULT NULL,mailaddress VARCHAR(350) DEFAULT NULL,company VARCHAR(250) DEFAULT NULL, department VARCHAR(250) DEFAULT NULL,website VARCHAR(350) DEFAULT NULL,notes VARCHAR(10000),dateadded DATE NOT NULL,isactive SMALLINT DEFAULT 0,iscustomer SMALLINT DEFAULT 0,ismanufacturer SMALLINT DEFAULT 0,issupplier SMALLINT DEFAULT 0,iscompany SMALLINT DEFAULT 0,ismale SMALLINT DEFAULT 0,isenabled SMALLINT DEFAULT 1,intaddedby BIGINT DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE users (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), CONSTRAINT const4 UNIQUE (cname, groupsids), cname VARCHAR(250) NOT NULL, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, intdefaultaccount BIGINT DEFAULT 1, compsids BIGINT DEFAULT 0, intdefaultstatus BIGINT DEFAULT 1,fullname VARCHAR(250) NOT NULL, password VARCHAR(250) NOT NULL,laf VARCHAR(150) DEFAULT NULL, locale VARCHAR(50) DEFAULT NULL, defcountry VARCHAR(50) DEFAULT '276', mail VARCHAR(50) DEFAULT NULL, language VARCHAR(150) DEFAULT NULL, inthighestright SMALLINT DEFAULT 3,isenabled SMALLINT DEFAULT 1,isrgrouped SMALLINT DEFAULT 0,isloggedin SMALLINT DEFAULT 0,datelastlog DATE DEFAULT NULL, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0,reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE files (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), cname VARCHAR(25) UNIQUE NOT NULL, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,dateadded DATE NOT NULL,data BLOB(50M) NOT NULL, filesize BIGINT NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0,PRIMARY KEY  (ids))",
        "CREATE TABLE languages(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), CONSTRAINT const6 UNIQUE (cname, groupsids), cname VARCHAR(250) NOT NULL, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, longname VARCHAR(250) UNIQUE NOT NULL, filename VARCHAR(25) NOT NULL REFERENCES files(cname) ON DELETE CASCADE,dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0,reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE favourites (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, usersids BIGINT REFERENCES users (ids)  ON DELETE CASCADE,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,itemsids BIGINT NOT NULL,dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0,reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE accounts(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), intaccountclass SMALLINT DEFAULT 0, cname VARCHAR(250) NOT NULL, description VARCHAR(250) NOT NULL, taxvalue DOUBLE NOT NULL DEFAULT 0, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0, intparentaccount BIGINT DEFAULT 0, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, invisible SMALLINT DEFAULT 0, intaccounttype SMALLINT NOT NULL, intprofitfid SMALLINT NOT NULL, inttaxfid SMALLINT NOT NULL, inttaxuid SMALLINT NOT NULL, frame VARCHAR(25) NOT NULL, hierarchypath VARCHAR(250) DEFAULT NULL, PRIMARY KEY  (ids))",
        "CREATE TABLE items (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), CONSTRAINT const7 UNIQUE (cnumber, inttype), cname VARCHAR(250) NOT NULL, cnumber VARCHAR(250) NOT NULL, description VARCHAR(2500) DEFAULT NULL, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, accountsids BIGINT REFERENCES accounts(ids) DEFAULT 1,contactsids BIGINT REFERENCES contacts(ids)  ON DELETE CASCADE, netvalue DOUBLE DEFAULT 0,taxvalue DOUBLE DEFAULT 0, discountvalue DOUBLE DEFAULT 0, shippingvalue DOUBLE DEFAULT 0, datetodo DATE DEFAULT NULL, dateend DATE DEFAULT NULL, intreminders INTEGER DEFAULT 0, inttype SMALLINT DEFAULT 0, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0,intstatus SMALLINT DEFAULT 0, hierarchypath VARCHAR(500) DEFAULT NULL, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL, PRIMARY KEY  (ids))",
        "CREATE TABLE subitems (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), cname VARCHAR(5000) DEFAULT NULL,itemsids BIGINT REFERENCES items(ids)  ON DELETE CASCADE, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,originalproductsids BIGINT DEFAULT NULL, countvalue DOUBLE DEFAULT 0 NOT NULL, quantityvalue DOUBLE DEFAULT 0 NOT NULL, measure VARCHAR(250) NOT NULL, linkurl VARCHAR(1000) DEFAULT NULL,description VARCHAR(1000) DEFAULT NULL, internalvalue DOUBLE DEFAULT 0, totalnetvalue DOUBLE DEFAULT 0, totalbrutvalue DOUBLE DEFAULT 0, externalvalue DOUBLE DEFAULT 0, taxpercentvalue DOUBLE DEFAULT 0 NOT NULL,datedelivery DATE DEFAULT NULL, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0,reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE schedule (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,usersids BIGINT REFERENCES users (ids)  ON DELETE CASCADE,itemsids BIGINT REFERENCES items (ids)  ON DELETE CASCADE,stopdate DATE NOT NULL,startdate DATE NOT NULL,nextdate DATE NOT NULL, isdone SMALLINT DEFAULT 0, intervalmonth SMALLINT NOT NULL, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0,reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE products (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), CONSTRAINT const8 UNIQUE (cnumber, groupsids), cname VARCHAR(500) NOT NULL, cnumber VARCHAR(250) NOT NULL, description VARCHAR(5000), externalnetvalue DOUBLE DEFAULT 0, internalnetvalue DOUBLE DEFAULT 0, measure VARCHAR(250) NOT NULL, taxids BIGINT REFERENCES tax(ids), manufacturersids BIGINT DEFAULT 0, suppliersids BIGINT DEFAULT 0, groupsids  BIGINT  REFERENCES groups(ids) DEFAULT 1, productgroupsids  BIGINT  REFERENCES productgroups(ids) DEFAULT 1, url VARCHAR(250) DEFAULT NULL,ean VARCHAR(25) DEFAULT NULL, reference VARCHAR(50) DEFAULT NULL,dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0, inttype SMALLINT NOT NULL, defaultimage VARCHAR(30) DEFAULT NULL, reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE productlists (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), cname VARCHAR(2500) DEFAULT NULL, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, description VARCHAR(1000) DEFAULT NULL, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0,reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE productlistitems (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), cname VARCHAR(2500) DEFAULT NULL, linkurl VARCHAR(250) DEFAULT NULL, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, productlistsids BIGINT REFERENCES productlists(ids) ON DELETE CASCADE,originalproductsids BIGINT REFERENCES products(ids) ON DELETE CASCADE, countvalue DOUBLE DEFAULT 0 NOT NULL, quantityvalue DOUBLE DEFAULT 0 NOT NULL, measure VARCHAR(250) NOT NULL,description VARCHAR(1000) DEFAULT NULL, internalvalue DOUBLE DEFAULT 0, totalnetvalue DOUBLE DEFAULT 0, totalbrutvalue DOUBLE DEFAULT 0, externalvalue DOUBLE DEFAULT 0, taxpercentvalue DOUBLE DEFAULT 0 NOT NULL, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0,invisible SMALLINT DEFAULT 0,reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE userproperties(IDS BIGINT DEFAULT 1,cname VARCHAR(250) NOT NULL, value VARCHAR(250) NOT NULL, usersids BIGINT NOT NULL, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,invisible SMALLINT DEFAULT 0)",
        "CREATE TABLE mails(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(1000) NOT NULL, dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,invisible SMALLINT DEFAULT 0, usersids BIGINT REFERENCES users(ids) ON DELETE CASCADE, description VARCHAR(5000) NOT NULL, PRIMARY KEY  (ids))",
        "CREATE TABLE comps (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, cname VARCHAR(250) DEFAULT NULL,state VARCHAR(250) DEFAULT NULL,phoneprefix VARCHAR(250) DEFAULT NULL,business VARCHAR(250) DEFAULT NULL,taxadvisor VARCHAR(250) DEFAULT NULL,city  VARCHAR(250) DEFAULT NULL,taxadvjob VARCHAR(250) DEFAULT NULL,street VARCHAR(250) DEFAULT NULL,stb  VARCHAR(250) DEFAULT NULL,email  VARCHAR(250) DEFAULT NULL,name  VARCHAR(250) DEFAULT NULL,zipcode VARCHAR(250) DEFAULT NULL,phone VARCHAR(250) DEFAULT NULL,firstname  VARCHAR(250) DEFAULT NULL,taxauthority VARCHAR(250) DEFAULT NULL,taxnumber VARCHAR(250) DEFAULT NULL,taxadvmandant VARCHAR(250) DEFAULT NULL,dateadded DATE NOT NULL,ismale SMALLINT DEFAULT 0,isenabled SMALLINT DEFAULT 1,intaddedby BIGINT DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE expenses (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, cnumber VARCHAR(250) DEFAULT NULL, cname VARCHAR(250) DEFAULT NULL, accountsids BIGINT REFERENCES accounts(ids), netvalue DOUBLE DEFAULT 0, taxpercentvalue DOUBLE DEFAULT 0, brutvalue DOUBLE DEFAULT 0, description VARCHAR(5000) DEFAULT NULL,dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE revenues (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, cnumber VARCHAR(250) DEFAULT NULL, cname VARCHAR(250) DEFAULT NULL, accountsids BIGINT REFERENCES accounts(ids), netvalue DOUBLE DEFAULT 0, taxpercentvalue DOUBLE DEFAULT 0, brutvalue DOUBLE DEFAULT 0, description VARCHAR(5000) DEFAULT NULL,dateadded DATE NOT NULL,intaddedby BIGINT DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE webshops (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), CONSTRAINT const9 UNIQUE (cname, groupsids), cname VARCHAR(250) NOT NULL,description VARCHAR(750) DEFAULT NULL,groupsids BIGINT DEFAULT 0,dateadded DATE NOT NULL, isrequestcompression SMALLINT DEFAULT 0, isauthenticated SMALLINT DEFAULT 0, username VARCHAR(50) DEFAULT NULL, passw VARCHAR(50) DEFAULT NULL,reserve1 VARCHAR(500) DEFAULT NULL,intaddedby BIGINT DEFAULT 0, interv BIGINT DEFAULT 0, url VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL, PRIMARY KEY  (ids))",
        "CREATE TABLE wscontactsmapping (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), webshopsids BIGINT REFERENCES webshops(ids) ON DELETE CASCADE, cname VARCHAR(250) NOT NULL, groupsids BIGINT REFERENCES groups(ids) ON DELETE CASCADE,contactsids BIGINT REFERENCES contacts(ids) ON DELETE CASCADE, wscontact VARCHAR(250) NOT NULL, dateadded DATE DEFAULT NULL, intaddedby BIGINT DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, CONSTRAINT const10 UNIQUE (wscontact, groupsids, webshopsids), reserve2 VARCHAR(500) DEFAULT NULL, PRIMARY KEY  (ids))",
        "CREATE TABLE wsitemsmapping (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), webshopsids BIGINT REFERENCES webshops(ids) ON DELETE CASCADE, cname VARCHAR(250) NOT NULL, groupsids BIGINT REFERENCES groups(ids) ON DELETE CASCADE,itemsids BIGINT REFERENCES contacts(ids) ON DELETE CASCADE, wsitem VARCHAR(250) NOT NULL, dateadded DATE DEFAULT NULL, intaddedby BIGINT DEFAULT 0, invisible SMALLINT DEFAULT 0, CONSTRAINT const11 UNIQUE (wsitem, groupsids, webshopsids), reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        //sub tables #2
        "CREATE TABLE tablelock (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250), rowID BIGINT NOT NULL, usersids BIGINT REFERENCES users(ids) ON DELETE CASCADE,reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids), CONSTRAINT one_lock UNIQUE(cname, rowid))",
        "CREATE TABLE itemstoaccounts (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), itemsids BIGINT NOT NULL REFERENCES items(ids) ON DELETE CASCADE, accountsids BIGINT REFERENCES accounts(ids) ON DELETE CASCADE,reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE trashbin (IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(500), rowID BIGINT NOT NULL, description VARCHAR(2500), deleteme SMALLINT DEFAULT 1, reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE filestocontacts(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, contactsids BIGINT NOT NULL REFERENCES contacts(ids) ON DELETE CASCADE, filename VARCHAR(25) NOT NULL REFERENCES files(cname) ON DELETE CASCADE, intsize BIGINT DEFAULT 0, mimetype VARCHAR(25) DEFAULT NULL, intaddedby BIGINT DEFAULT 0,dateadded DATE NOT NULL,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,PRIMARY KEY  (ids))",
        "CREATE TABLE templates(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, format VARCHAR(55) DEFAULT NULL, description VARCHAR(550) DEFAULT NULL, intsize BIGINT DEFAULT 0, mimetype VARCHAR(25) DEFAULT NULL, filename VARCHAR(25) NOT NULL REFERENCES files(cname) ON DELETE CASCADE, intaddedby BIGINT DEFAULT 0,dateadded DATE NOT NULL,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,PRIMARY KEY  (ids))",
        "CREATE TABLE filestoitems(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, itemsids BIGINT NOT NULL REFERENCES items(ids) ON DELETE CASCADE,filename VARCHAR(25) NOT NULL REFERENCES files(cname) ON DELETE CASCADE,intsize BIGINT DEFAULT 0, mimetype VARCHAR(25) DEFAULT NULL, intaddedby BIGINT DEFAULT 0,dateadded DATE NOT NULL,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,PRIMARY KEY  (ids))",
        "CREATE TABLE filestoproducts(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, productsids BIGINT NOT NULL REFERENCES products(ids) ON DELETE CASCADE,filename VARCHAR(25) NOT NULL REFERENCES files(cname) ON DELETE CASCADE,intsize BIGINT DEFAULT 0, mimetype VARCHAR(25) DEFAULT NULL, intaddedby BIGINT DEFAULT 0,dateadded DATE NOT NULL,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,PRIMARY KEY  (ids))",
        "CREATE TABLE plugins(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL,filename VARCHAR(25) NOT NULL REFERENCES files(cname) ON DELETE CASCADE,intaddedby BIGINT DEFAULT 0,dateadded DATE NOT NULL,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,PRIMARY KEY  (ids))",
        "CREATE TABLE pluginstousers(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, usersids BIGINT NOT NULL, pluginsids BIGINT NOT NULL REFERENCES plugins(ids) ON DELETE CASCADE,intaddedby BIGINT DEFAULT 0,dateadded DATE NOT NULL,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,PRIMARY KEY  (ids))",
        "CREATE TABLE formatstousers(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, usersids BIGINT REFERENCES users(ids) ON DELETE CASCADE, inttype SMALLINT  DEFAULT 0,PRIMARY KEY (ids))",
        "CREATE TABLE templatestousers(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, usersids BIGINT REFERENCES users(ids) ON DELETE CASCADE, templatesids BIGINT NOT NULL REFERENCES templates(ids) ON DELETE CASCADE, groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1, PRIMARY KEY (ids))",
        "CREATE TABLE addresses(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,contactsids BIGINT REFERENCES contacts(ids),title VARCHAR(250) DEFAULT NULL, taxnumber VARCHAR(250),prename VARCHAR(250) DEFAULT NULL, cname VARCHAR(250) DEFAULT NULL, street VARCHAR(250) DEFAULT NULL,zip VARCHAR(50) DEFAULT NULL,city VARCHAR(300) DEFAULT NULL, company VARCHAR(250) DEFAULT NULL, department VARCHAR(250) DEFAULT NULL,country VARCHAR(50) DEFAULT NULL, ismale SMALLINT DEFAULT 0,intaddedby BIGINT DEFAULT 0,dateadded DATE DEFAULT NULL,inttype SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL,reserve2 VARCHAR(500) DEFAULT NULL,PRIMARY KEY  (ids))",
        "CREATE TABLE reminders(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, stagesids BIGINT NOT NULL,itemsids BIGINT NOT NULL REFERENCES items(ids) ON DELETE CASCADE, extravalue DOUBLE DEFAULT 0, intaddedby BIGINT DEFAULT 0,dateadded DATE NOT NULL,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,PRIMARY KEY  (ids))",
        "CREATE TABLE stages(IDS BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, extravalue DOUBLE DEFAULT 0, intaddedby BIGINT DEFAULT 0,dateadded DATE NOT NULL,groupsids BIGINT  REFERENCES groups(ids) DEFAULT 1,PRIMARY KEY  (ids))",
        //Trigger
        "CREATE TRIGGER contacts_indexer1 AFTER INSERT ON contacts REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids, 'contacts',newdata.ids,newdata.cnumber||' '||newdata.taxnumber||' '||newdata.title||' '||newdata.country||' '|| newdata.prename||' '|| newdata.cname||' '|| newdata.street||' '||newdata.zip||' '|| newdata.city ||' '||newdata.mainphone||' '||newdata.fax||' '||newdata.mobilephone||' '||newdata.workphone||' '||newdata.mailaddress||' '||newdata.company||' '|| newdata.department||' '||newdata.website||' '||newdata.notes)",
        "CREATE TRIGGER contacts_indexer2 AFTER UPDATE ON contacts REFERENCING NEW AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'contacts' AND  rowid = newdata.ids",
        "CREATE TRIGGER contacts_indexer3 AFTER UPDATE ON contacts REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'contacts',newdata.ids,newdata.cnumber||' '||newdata.taxnumber||' '||newdata.title||' '||newdata.country||' '|| newdata.prename||' '|| newdata.cname||' '|| newdata.street||' '||newdata.zip||' '|| newdata.city ||' '||newdata.mainphone||' '||newdata.fax||' '||newdata.mobilephone||' '||newdata.workphone||' '||newdata.mailaddress||' '||newdata.company||' '|| newdata.department||' '||newdata.website||' '||newdata.notes)",
        "CREATE TRIGGER contacts_indexer4 AFTER DELETE ON contacts REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'contacts' AND  rowid = newdata.ids",
        "CREATE TRIGGER contacts_trash1   AFTER UPDATE ON contacts REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible,'contacts',newdata.ids,newdata.cnumber||' ('|| newdata.cname||')')",
        "CREATE TRIGGER contacts_trash2 AFTER DELETE ON contacts REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM trashbin WHERE cname = 'contacts' AND  rowid = newdata.ids",
        "CREATE TRIGGER filestocontacts_indexer1 AFTER INSERT ON filestocontacts REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'filestocontacts',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.filename)",
        "CREATE TRIGGER filestocontacts_indexer2 AFTER UPDATE ON filestocontacts REFERENCING NEW AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'filestocontacts' AND  rowid = newdata.ids",
        "CREATE TRIGGER filestocontacts_indexer3 AFTER UPDATE ON filestocontacts REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'filestocontacts',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.filename)",
        "CREATE TRIGGER filestocontacts_indexer4 AFTER DELETE ON filestocontacts REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'filestocontacts' AND  rowid = newdata.ids",
        "CREATE TRIGGER groups_indexer1 AFTER INSERT ON groups REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'groups',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.dateadded)",
        "CREATE TRIGGER groups_indexer2 AFTER UPDATE ON groups REFERENCING NEW AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'groups' AND  rowid = newdata.ids",
        "CREATE TRIGGER groups_indexer3 AFTER UPDATE ON groups REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'groups',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.dateadded)",
        "CREATE TRIGGER groups_indexer4 AFTER DELETE ON groups REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'groups' AND  rowid = newdata.ids",
        "CREATE TRIGGER items_indexer1 AFTER INSERT ON items REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'items',newdata.ids,newdata.cname||' '||newdata.dateadded)",
        "CREATE TRIGGER items_indexer2 AFTER UPDATE ON items REFERENCING NEW AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'items' AND  rowid = newdata.ids",
        "CREATE TRIGGER items_indexer3 AFTER UPDATE ON items REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'items',newdata.ids,newdata.cname||' '||newdata.dateadded)",
        "CREATE TRIGGER items_indexer4 AFTER DELETE ON items REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'items' AND  rowid = newdata.ids",
        "CREATE TRIGGER items_trash2 AFTER DELETE ON items REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM trashbin WHERE cname = 'items' AND  rowid = newdata.ids",
        "CREATE TRIGGER items_trash1 AFTER UPDATE ON items REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible,'items',newdata.ids,newdata.cname)",
        "CREATE TRIGGER expenses_indexer1 AFTER INSERT ON expenses REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'expenses',newdata.ids,newdata.cname||' '||newdata.dateadded)",
        "CREATE TRIGGER expenses_indexer2 AFTER UPDATE ON expenses REFERENCING NEW AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'expenses' AND  rowid = newdata.ids",
        "CREATE TRIGGER expenses_indexer3 AFTER UPDATE ON expenses REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'expenses',newdata.ids,newdata.cname||' '||newdata.dateadded)",
        "CREATE TRIGGER expenses_indexer4 AFTER DELETE ON expenses REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'expenses' AND  rowid = newdata.ids",
        "CREATE TRIGGER expenses_trash2 AFTER DELETE ON expenses REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM trashbin WHERE cname = 'expenses' AND  rowid = newdata.ids",
        "CREATE TRIGGER expenses_trash1 AFTER UPDATE ON expenses REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible,'expenses',newdata.ids,newdata.cname)",
        "CREATE TRIGGER revenues_indexer1 AFTER INSERT ON revenues REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'revenues',newdata.ids,newdata.cname||' '||newdata.dateadded)",
        "CREATE TRIGGER revenues_indexer2 AFTER UPDATE ON revenues REFERENCING NEW AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'revenues' AND  rowid = newdata.ids",
        "CREATE TRIGGER revenues_indexer3 AFTER UPDATE ON revenues REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'revenues',newdata.ids,newdata.cname||' '||newdata.dateadded)",
        "CREATE TRIGGER revenues_indexer4 AFTER DELETE ON revenues REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'revenues' AND  rowid = newdata.ids",
        "CREATE TRIGGER revenues_trash2 AFTER DELETE ON revenues REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM trashbin WHERE cname = 'revenues' AND  rowid = newdata.ids",
        "CREATE TRIGGER revenues_trash1 AFTER UPDATE ON revenues REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible,'revenues',newdata.ids,newdata.cname)",
        "CREATE TRIGGER subitems_indexer1 AFTER INSERT ON subitems REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'subitems',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.dateadded)",
        "CREATE TRIGGER subitems_indexer2 AFTER UPDATE ON subitems REFERENCING NEW AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'subitems' AND  rowid = newdata.ids",
        "CREATE TRIGGER subitems_indexer3 AFTER UPDATE ON subitems REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'subitems',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.dateadded)",
        "CREATE TRIGGER subitems_indexer4 AFTER DELETE ON subitems REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'subitems' AND  rowid = newdata.ids",
        "CREATE TRIGGER products_indexer1 AFTER INSERT ON products REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'products',newdata.ids,newdata.cname||' '||newdata.cnumber||' '||newdata.description||' '||newdata.dateadded)",
        "CREATE TRIGGER products_indexer2 AFTER UPDATE ON products REFERENCING NEW AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'products' AND  rowid = newdata.ids",
        "CREATE TRIGGER products_indexer3 AFTER UPDATE ON products REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'products',newdata.ids,newdata.cname||' '||newdata.cnumber||' '||newdata.description||' '||newdata.dateadded)",
        "CREATE TRIGGER products_indexer4 AFTER DELETE ON products REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM searchindex WHERE dbidentity = 'products' AND  rowid = newdata.ids",
        "CREATE TRIGGER products_trash1 AFTER UPDATE ON products REFERENCING NEW AS newdata FOR EACH ROW INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible, 'products',newdata.ids,newdata.cnumber||' ('|| newdata.cname||')')",
        "CREATE TRIGGER products_trash2 AFTER DELETE ON products REFERENCING OLD AS newdata FOR EACH ROW DELETE FROM trashbin WHERE cname = 'products' AND  rowid = newdata.ids",
        "CREATE TRIGGER thrash_handler1 AFTER INSERT ON trashbin FOR EACH STATEMENT DELETE FROM trashbin WHERE deleteme = 0",
        "CREATE TRIGGER thrash_handler2 AFTER INSERT ON trashbin FOR EACH STATEMENT DELETE FROM trashbin WHERE ids IN (SELECT ids FROM trashbin WHERE EXISTS( SELECT ids FROM trashbin AS tmptable WHERE trashbin.cname = tmptable.cname AND trashbin.rowid = tmptable.rowid HAVING trashbin.ids < MAX(tmptable.ids) ) )",};
    public static String[] MYSQL_STRUCTURE = new String[]{
        "CREATE TABLE accounts ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, intaccountclass SMALLINT DEFAULT 0, cname VARCHAR(250) NOT NULL, description VARCHAR(250) NOT NULL, taxvalue DOUBLE NOT NULL DEFAULT 0, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, intparentaccount BIGINT(20) DEFAULT 0, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, invisible SMALLINT DEFAULT 0, intaccounttype SMALLINT NOT NULL, intprofitfid SMALLINT NOT NULL, inttaxfid SMALLINT NOT NULL, inttaxuid SMALLINT NOT NULL, frame VARCHAR(25) NOT NULL, hierarchypath VARCHAR(250) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE addresses ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, contactsids BIGINT(20) UNSIGNED NOT NULL, title VARCHAR(250) DEFAULT NULL, taxnumber VARCHAR(250) DEFAULT NULL, prename VARCHAR(250) DEFAULT NULL, cname VARCHAR(250) DEFAULT NULL, street VARCHAR(250) DEFAULT NULL, zip VARCHAR(50) DEFAULT NULL, city VARCHAR(300) DEFAULT NULL, company VARCHAR(250) DEFAULT NULL, department VARCHAR(250) DEFAULT NULL, country VARCHAR(50) DEFAULT NULL, ismale SMALLINT DEFAULT 0, intaddedby BIGINT(20) DEFAULT 0, dateadded DATE DEFAULT NULL, inttype SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE comps ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, cname VARCHAR(250) DEFAULT NULL, state VARCHAR(250) DEFAULT NULL, phoneprefix VARCHAR(250) DEFAULT NULL, business VARCHAR(250) DEFAULT NULL, taxadvisor VARCHAR(250) DEFAULT NULL, city VARCHAR(250) DEFAULT NULL, taxadvjob VARCHAR(250) DEFAULT NULL, street VARCHAR(250) DEFAULT NULL, stb VARCHAR(250) DEFAULT NULL, email VARCHAR(250) DEFAULT NULL, name VARCHAR(250) DEFAULT NULL, zipcode VARCHAR(250) DEFAULT NULL, phone VARCHAR(250) DEFAULT NULL, firstname VARCHAR(250) DEFAULT NULL, taxauthority VARCHAR(250) DEFAULT NULL, taxnumber VARCHAR(250) DEFAULT NULL, taxadvmandant VARCHAR(250) DEFAULT NULL, dateadded DATE NOT NULL, ismale SMALLINT DEFAULT 0, isenabled SMALLINT DEFAULT 1, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE contacts ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cnumber VARCHAR(250) DEFAULT NULL, taxnumber VARCHAR(250), title VARCHAR(250) DEFAULT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, country VARCHAR(50) DEFAULT NULL, prename VARCHAR(250) DEFAULT NULL, cname VARCHAR(250) DEFAULT NULL, street VARCHAR(250) DEFAULT NULL, zip VARCHAR(50) DEFAULT NULL, city VARCHAR(300) DEFAULT NULL, mainphone VARCHAR(250) DEFAULT NULL, fax VARCHAR(250) DEFAULT NULL, mobilephone VARCHAR(250) DEFAULT NULL, workphone VARCHAR(250) DEFAULT NULL, mailaddress VARCHAR(350) DEFAULT NULL, company VARCHAR(250) DEFAULT NULL, department VARCHAR(250) DEFAULT NULL, website VARCHAR(350) DEFAULT NULL, notes VARCHAR(10000), dateadded DATE NOT NULL, isactive SMALLINT DEFAULT 0, iscustomer SMALLINT DEFAULT 0, ismanufacturer SMALLINT DEFAULT 0, issupplier SMALLINT DEFAULT 0, iscompany SMALLINT DEFAULT 0, ismale SMALLINT DEFAULT 0, isenabled SMALLINT DEFAULT 1, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE countries ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, iso SMALLINT NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE expenses ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, cnumber VARCHAR(250) DEFAULT NULL, cname VARCHAR(250) DEFAULT NULL, accountsids BIGINT(20) UNSIGNED NOT NULL, netvalue DOUBLE DEFAULT 0, taxpercentvalue DOUBLE DEFAULT 0, brutvalue DOUBLE DEFAULT 0, description VARCHAR(5000) DEFAULT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE favourites ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, usersids BIGINT(20) UNSIGNED NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, itemsids BIGINT(20) UNSIGNED NOT NULL NOT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE files ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(25) NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, dateadded DATE NOT NULL, DATA BLOB(5242880) NOT NULL, filesize BIGINT(20) NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE filestocontacts ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, contactsids BIGINT(20) UNSIGNED NOT NULL NOT NULL, filename VARCHAR(25) NOT NULL, intsize BIGINT(20) DEFAULT 0, mimetype VARCHAR(25) DEFAULT NULL, intaddedby BIGINT(20) DEFAULT 0, dateadded DATE NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE filestoitems ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, itemsids BIGINT(20) UNSIGNED NOT NULL NOT NULL, filename VARCHAR(25) NOT NULL, intsize BIGINT(20) DEFAULT 0, mimetype VARCHAR(25) DEFAULT NULL, intaddedby BIGINT(20) DEFAULT 0, dateadded DATE NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE filestoproducts ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, productsids BIGINT(20) UNSIGNED NOT NULL NOT NULL, filename VARCHAR(25) NOT NULL, intsize BIGINT(20) DEFAULT 0, mimetype VARCHAR(25) DEFAULT NULL, intaddedby BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, dateadded DATE NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE formatstousers ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, usersids BIGINT(20) UNSIGNED NOT NULL, inttype SMALLINT DEFAULT 0 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE globalsettings ( ids BIGINT(20) DEFAULT 1, cname VARCHAR(250) NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, VALUE VARCHAR(250) NOT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE groups ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, description VARCHAR(750) DEFAULT NULL, defaults VARCHAR(250) DEFAULT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, dateadded DATE NOT NULL, reserve1 VARCHAR(500) DEFAULT NULL, intaddedby BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, hierarchypath VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE history ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, username VARCHAR(250) NOT NULL, dbidentity VARCHAR(25) NOT NULL, intitem SMALLINT NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE items ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, cnumber VARCHAR(250) NOT NULL, description VARCHAR(2500) DEFAULT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, accountsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, contactsids BIGINT(20) UNSIGNED NOT NULL, netvalue DOUBLE DEFAULT 0, taxvalue DOUBLE DEFAULT 0, discountvalue DOUBLE DEFAULT 0, shippingvalue DOUBLE DEFAULT 0, datetodo DATE DEFAULT NULL, dateend DATE DEFAULT NULL, intreminders INTEGER DEFAULT 0, inttype SMALLINT DEFAULT 0, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, intstatus SMALLINT DEFAULT 0, hierarchypath VARCHAR(500) DEFAULT NULL, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE itemstoaccounts ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, itemsids BIGINT(20) UNSIGNED NOT NULL NOT NULL, accountsids BIGINT(20) UNSIGNED NOT NULL, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE languages ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, longname VARCHAR(250) NOT NULL, filename VARCHAR(25) NOT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE mails ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(1000) NOT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, invisible SMALLINT DEFAULT 0, usersids BIGINT(20) UNSIGNED NOT NULL, description VARCHAR(5000) NOT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE plugins ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, filename VARCHAR(25) NOT NULL, intaddedby BIGINT(20) DEFAULT 0, dateadded DATE NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE pluginstousers ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, usersids BIGINT(20) UNSIGNED NOT NULL NOT NULL, pluginsids BIGINT(20) UNSIGNED NOT NULL NOT NULL, intaddedby BIGINT(20) DEFAULT 0, dateadded DATE NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE productgroups ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, description VARCHAR(750) DEFAULT NULL, defaults VARCHAR(250) DEFAULT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, productgroupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, dateadded DATE NOT NULL, hierarchypath VARCHAR(500) DEFAULT NULL, reserve1 VARCHAR(500) DEFAULT NULL, intaddedby BIGINT(20) DEFAULT 0, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE productlistitems ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(2500) DEFAULT NULL, linkurl VARCHAR(250) DEFAULT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, productlistsids BIGINT(20) UNSIGNED NOT NULL, originalproductsids BIGINT(20) UNSIGNED NOT NULL, countvalue DOUBLE NOT NULL DEFAULT 0, quantityvalue DOUBLE NOT NULL DEFAULT 0, measure VARCHAR(250) NOT NULL, description VARCHAR(1000) DEFAULT NULL, internalvalue DOUBLE DEFAULT 0, totalnetvalue DOUBLE DEFAULT 0, totalbrutvalue DOUBLE DEFAULT 0, externalvalue DOUBLE DEFAULT 0, taxpercentvalue DOUBLE NOT NULL DEFAULT 0, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE productlists ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(2500) DEFAULT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, description VARCHAR(1000) DEFAULT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE products ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(500) NOT NULL, cnumber VARCHAR(250) NOT NULL, description VARCHAR(5000), externalnetvalue DOUBLE DEFAULT 0, internalnetvalue DOUBLE DEFAULT 0, measure VARCHAR(250) NOT NULL, taxids BIGINT(20) UNSIGNED NOT NULL, manufacturersids BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, suppliersids BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, productgroupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, url VARCHAR(250) DEFAULT NULL, ean VARCHAR(25) DEFAULT NULL, reference VARCHAR(50) DEFAULT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, inttype SMALLINT NOT NULL, defaultimage VARCHAR(30) DEFAULT NULL, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE reminders ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, stagesids BIGINT(20) UNSIGNED NOT NULL, itemsids BIGINT(20) UNSIGNED NOT NULL, extravalue DOUBLE DEFAULT 0, intaddedby BIGINT(20) DEFAULT 0, dateadded DATE NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE revenues ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, cnumber VARCHAR(250) DEFAULT NULL, cname VARCHAR(250) DEFAULT NULL, accountsids BIGINT(20) UNSIGNED NOT NULL, netvalue DOUBLE DEFAULT 0, taxpercentvalue DOUBLE DEFAULT 0, brutvalue DOUBLE DEFAULT 0, description VARCHAR(5000) DEFAULT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE schedule ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, usersids BIGINT(20) UNSIGNED NOT NULL, itemsids BIGINT(20) UNSIGNED NOT NULL, stopdate DATE NOT NULL, startdate DATE NOT NULL, nextdate DATE NOT NULL, isdone SMALLINT DEFAULT 0, intervalmonth SMALLINT NOT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE searchindex ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, dbidentity VARCHAR(25) NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL, rowid BIGINT(20) NOT NULL, TEXT VARCHAR(5000) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE stages ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, description VARCHAR(550) DEFAULT NULL, extravalue DOUBLE DEFAULT 0, intaddedby BIGINT(20) DEFAULT 0, dateadded DATE NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE subitems ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(5000) DEFAULT NULL, itemsids BIGINT(20) UNSIGNED NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, originalproductsids BIGINT(20) UNSIGNED DEFAULT NULL, countvalue DOUBLE NOT NULL DEFAULT 0, quantityvalue DOUBLE NOT NULL DEFAULT 0, measure VARCHAR(250) NOT NULL, linkurl VARCHAR(1000) DEFAULT NULL, description VARCHAR(1000) DEFAULT NULL, internalvalue DOUBLE DEFAULT 0, totalnetvalue DOUBLE DEFAULT 0, totalbrutvalue DOUBLE DEFAULT 0, externalvalue DOUBLE DEFAULT 0, taxpercentvalue DOUBLE NOT NULL DEFAULT 0, datedelivery DATE DEFAULT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE tablelock ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250), rowid BIGINT(20) NOT NULL, usersids BIGINT(20) UNSIGNED NOT NULL, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE tax ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250), taxvalue DOUBLE DEFAULT 0, identifier VARCHAR(250) DEFAULT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, country VARCHAR(50) DEFAULT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE templates ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, format VARCHAR(55) DEFAULT NULL, description VARCHAR(550) DEFAULT NULL, intsize BIGINT(20) DEFAULT 0, mimetype VARCHAR(25) DEFAULT NULL, filename VARCHAR(25) NOT NULL, intaddedby BIGINT(20) DEFAULT 0, dateadded DATE NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE templatestousers ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, usersids BIGINT(20) UNSIGNED NOT NULL, templatesids BIGINT(20) UNSIGNED NOT NULL NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE trashbin ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(500), rowid BIGINT(20) NOT NULL, description VARCHAR(2500), deleteme SMALLINT DEFAULT 1, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE userproperties ( ids BIGINT(20) DEFAULT 1, cname VARCHAR(250) NOT NULL, VALUE VARCHAR(250) NOT NULL, usersids BIGINT(20) UNSIGNED NOT NULL NOT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, invisible SMALLINT DEFAULT 0 ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE users ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 1, intdefaultaccount BIGINT(20) DEFAULT 1, compsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, intdefaultstatus BIGINT(20) DEFAULT 1, fullname VARCHAR(250) NOT NULL, PASSWORD VARCHAR(250) NOT NULL, laf VARCHAR(50) DEFAULT NULL, locale VARCHAR(50) DEFAULT NULL, defcountry VARCHAR(50) DEFAULT NULL, mail VARCHAR(50) DEFAULT NULL, LANGUAGE VARCHAR(50) DEFAULT NULL, inthighestright SMALLINT DEFAULT 3, isenabled SMALLINT DEFAULT 1, isrgrouped SMALLINT DEFAULT 0, isloggedin SMALLINT DEFAULT 0, datelastlog DATE DEFAULT NULL, dateadded DATE NOT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE webshops ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, cname VARCHAR(250) NOT NULL, description VARCHAR(750) DEFAULT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL DEFAULT 0, dateadded DATE NOT NULL, isrequestcompression SMALLINT DEFAULT 0, isauthenticated SMALLINT DEFAULT 0, username VARCHAR(50) DEFAULT NULL, passw VARCHAR(50) DEFAULT NULL, reserve1 VARCHAR(500) DEFAULT NULL, intaddedby BIGINT(20) DEFAULT 0, interv BIGINT(20) DEFAULT 0, url VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE wscontactsmapping ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, webshopsids BIGINT(20) UNSIGNED NOT NULL, cname VARCHAR(250) NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL, contactsids BIGINT(20) UNSIGNED NOT NULL, wscontact VARCHAR(250) NOT NULL, dateadded DATE DEFAULT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE TABLE wsitemsmapping ( ids BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, webshopsids BIGINT(20) UNSIGNED NOT NULL, cname VARCHAR(250) NOT NULL, groupsids BIGINT(20) UNSIGNED NOT NULL, itemsids BIGINT(20) UNSIGNED NOT NULL, wsitem VARCHAR(250) NOT NULL, dateadded DATE DEFAULT NULL, intaddedby BIGINT(20) DEFAULT 0, invisible SMALLINT DEFAULT 0, reserve1 VARCHAR(500) DEFAULT NULL, reserve2 VARCHAR(500) DEFAULT NULL ) ENGINE=myisam DEFAULT CHARSET=utf8",
        "CREATE UNIQUE INDEX sql091006084310810 ON groups(cname)",
        "CREATE UNIQUE INDEX sql091006084310820 ON groups(ids)",
        "CREATE UNIQUE INDEX sql091006084311391 ON productgroups(cname, groupsids)",
        "CREATE UNIQUE INDEX sql091006084311390 ON productgroups(ids)",
        "CREATE UNIQUE INDEX sql091006084311800 ON history(ids)",
        "CREATE UNIQUE INDEX sql091006084312110 ON countries(iso)",
        "CREATE UNIQUE INDEX sql091006084312111 ON countries(ids)",
        "CREATE UNIQUE INDEX sql091006084312620 ON globalsettings(cname, groupsids)",
        "CREATE UNIQUE INDEX sql091006084312900 ON tax(ids)",
        "CREATE INDEX sql091006084312890 ON tax(groupsids)",
        "CREATE UNIQUE INDEX sql091006084313451 ON contacts(ids)",
        "CREATE INDEX sql091006084313450 ON contacts(groupsids)",
        "CREATE UNIQUE INDEX sql091006084313971 ON users(cname, groupsids)",
        "CREATE UNIQUE INDEX sql091006084313970 ON users(ids)",
        "CREATE INDEX sql091006084313960 ON users(groupsids)",
        "CREATE UNIQUE INDEX sql091006084314570 ON files(cname)",
        "CREATE UNIQUE INDEX sql091006084314572 ON files(ids)",
        "CREATE INDEX sql091006084314571 ON files(groupsids)",
        "CREATE UNIQUE INDEX sql091006084315174 ON languages(cname, groupsids)",
        "CREATE UNIQUE INDEX sql091006084315171 ON languages(longname)",
        "CREATE UNIQUE INDEX sql091006084315173 ON languages(ids)",
        "CREATE INDEX sql091006084315170 ON languages(groupsids)",
        "CREATE INDEX sql091006084315172 ON languages(filename)",
        "CREATE UNIQUE INDEX sql091006084315882 ON favourites(ids)",
        "CREATE INDEX sql091006084315880 ON favourites(usersids)",
        "CREATE INDEX sql091006084315881 ON favourites(groupsids)",
        "CREATE UNIQUE INDEX sql091006084316451 ON accounts(ids)",
        "CREATE INDEX sql091006084316450 ON accounts(groupsids)",
        "CREATE UNIQUE INDEX sql091006084316862 ON items(cnumber, inttype)",
        "CREATE UNIQUE INDEX sql091006084316861 ON items(ids)",
        "CREATE INDEX sql091006084316850 ON items(groupsids)",
        "CREATE INDEX sql091006084316851 ON items(accountsids)",
        "CREATE INDEX sql091006084316860 ON items(contactsids)",
        "CREATE UNIQUE INDEX sql091006084317902 ON subitems(ids)",
        "CREATE INDEX sql091006084317900 ON subitems(itemsids)",
        "CREATE INDEX sql091006084317901 ON subitems(groupsids)",
        "CREATE UNIQUE INDEX sql091006084318483 ON schedule(ids)",
        "CREATE INDEX sql091006084318480 ON schedule(groupsids)",
        "CREATE INDEX sql091006084318481 ON schedule(usersids)",
        "CREATE INDEX sql091006084318482 ON schedule(itemsids)",
        "CREATE UNIQUE INDEX sql091006084319621 ON products(cnumber, groupsids)",
        "CREATE UNIQUE INDEX sql091006084319620 ON products(ids)",
        "CREATE INDEX sql091006084319610 ON products(taxids)",
        "CREATE INDEX sql091006084319611 ON products(groupsids)",
        "CREATE INDEX sql091006084319612 ON products(productgroupsids)",
        "CREATE UNIQUE INDEX sql091006084320591 ON productlists(ids)",
        "CREATE INDEX sql091006084320590 ON productlists(groupsids)",
        "CREATE UNIQUE INDEX sql091006084321141 ON productlistitems(ids)",
        "CREATE INDEX sql091006084321130 ON productlistitems(groupsids)",
        "CREATE INDEX sql091006084321131 ON productlistitems(productlistsids)",
        "CREATE INDEX sql091006084321140 ON productlistitems(originalproductsids)",
        "CREATE INDEX sql091006084322190 ON userproperties(groupsids)",
        "CREATE UNIQUE INDEX sql091006084322552 ON mails(ids)",
        "CREATE INDEX sql091006084322550 ON mails(groupsids)",
        "CREATE INDEX sql091006084322551 ON mails(usersids)",
        "CREATE UNIQUE INDEX sql091006084323381 ON comps(ids)",
        "CREATE INDEX sql091006084323380 ON comps(groupsids)",
        "CREATE UNIQUE INDEX sql091006084324160 ON expenses(ids)",
        "CREATE INDEX sql091006084324140 ON expenses(groupsids)",
        "CREATE INDEX sql091006084324141 ON expenses(accountsids)",
        "CREATE UNIQUE INDEX sql091006084324810 ON revenues(ids)",
        "CREATE INDEX sql091006084324790 ON revenues(groupsids)",
        "CREATE INDEX sql091006084324800 ON revenues(accountsids)",
        "CREATE UNIQUE INDEX sql091006084325551 ON webshops(cname, groupsids)",
        "CREATE UNIQUE INDEX sql091006084325550 ON webshops(ids)",
        "CREATE UNIQUE INDEX sql091006084326054 ON wscontactsmapping(wscontact, groupsids, webshopsids)",
        "CREATE UNIQUE INDEX sql091006084326053 ON wscontactsmapping(ids)",
        "CREATE INDEX sql091006084326050 ON wscontactsmapping(webshopsids)",
        "CREATE INDEX sql091006084326051 ON wscontactsmapping(groupsids)",
        "CREATE INDEX sql091006084326052 ON wscontactsmapping(contactsids)",
        "CREATE UNIQUE INDEX sql091006084326881 ON wsitemsmapping(wsitem, groupsids, webshopsids)",
        "CREATE UNIQUE INDEX sql091006084326880 ON wsitemsmapping(ids)",
        "CREATE INDEX sql091006084326870 ON wsitemsmapping(webshopsids)",
        "CREATE INDEX sql091006084326871 ON wsitemsmapping(groupsids)",
        "CREATE INDEX sql091006084326872 ON wsitemsmapping(itemsids)",
        "CREATE UNIQUE INDEX sql091006084327910 ON tablelock(ids)",
        "CREATE UNIQUE INDEX sql091006084327911 ON tablelock(cname, rowid)",
        "CREATE INDEX sql091006084327890 ON tablelock(usersids)",
        "CREATE UNIQUE INDEX sql091006084328480 ON itemstoaccounts(ids)",
        "CREATE INDEX sql091006084328460 ON itemstoaccounts(itemsids)",
        "CREATE INDEX sql091006084328461 ON itemstoaccounts(accountsids)",
        "CREATE UNIQUE INDEX sql091006084329120 ON trashbin(ids)",
        "CREATE UNIQUE INDEX sql091006084329671 ON filestocontacts(ids)",
        "CREATE INDEX sql091006084329650 ON filestocontacts(contactsids)",
        "CREATE INDEX sql091006084329651 ON filestocontacts(filename)",
        "CREATE INDEX sql091006084329670 ON filestocontacts(groupsids)",
        "CREATE UNIQUE INDEX sql091006084330492 ON templates(ids)",
        "CREATE INDEX sql091006084330490 ON templates(filename)",
        "CREATE INDEX sql091006084330491 ON templates(groupsids)",
        "CREATE UNIQUE INDEX sql091006084331263 ON filestoitems(ids)",
        "CREATE INDEX sql091006084331260 ON filestoitems(itemsids)",
        "CREATE INDEX sql091006084331261 ON filestoitems(filename)",
        "CREATE INDEX sql091006084331262 ON filestoitems(groupsids)",
        "CREATE UNIQUE INDEX sql091006084332163 ON filestoproducts(ids)",
        "CREATE INDEX sql091006084332160 ON filestoproducts(productsids)",
        "CREATE INDEX sql091006084332161 ON filestoproducts(filename)",
        "CREATE INDEX sql091006084332162 ON filestoproducts(groupsids)",
        "CREATE UNIQUE INDEX sql091006084333560 ON plugins(ids)",
        "CREATE INDEX sql091006084333550 ON plugins(filename)",
        "CREATE INDEX sql091006084333551 ON plugins(groupsids)",
        "CREATE UNIQUE INDEX sql091006084334241 ON pluginstousers(ids)",
        "CREATE INDEX sql091006084334230 ON pluginstousers(pluginsids)",
        "CREATE INDEX sql091006084334240 ON pluginstousers(groupsids)",
        "CREATE UNIQUE INDEX sql091006084334891 ON formatstousers(ids)",
        "CREATE INDEX sql091006084334890 ON formatstousers(usersids)",
        "CREATE UNIQUE INDEX sql091006084335461 ON templatestousers(ids)",
        "CREATE INDEX sql091006084335450 ON templatestousers(usersids)",
        "CREATE INDEX sql091006084335451 ON templatestousers(templatesids)",
        "CREATE INDEX sql091006084335460 ON templatestousers(groupsids)",
        "CREATE UNIQUE INDEX sql091006084336332 ON addresses(ids)",
        "CREATE INDEX sql091006084336330 ON addresses(groupsids)",
        "CREATE INDEX sql091006084336331 ON addresses(contactsids)",
        "CREATE UNIQUE INDEX sql091006084336882 ON reminders(ids)",
        "CREATE INDEX sql091006084336880 ON reminders(itemsids)",
        "CREATE INDEX sql091006084336881 ON reminders(groupsids)",
        "CREATE UNIQUE INDEX sql091006084337581 ON stages(ids)",
        "CREATE INDEX sql091006084337580 ON stages(groupsids)",
        "ALTER TABLE contacts ADD CONSTRAINT const3 UNIQUE (cnumber, groupsids)",
        "ALTER TABLE countries ADD CONSTRAINT sql0910060843121101 UNIQUE (iso)",
        "ALTER TABLE files ADD CONSTRAINT sql0910060843145701 UNIQUE (cname)",
        "ALTER TABLE globalsettings ADD CONSTRAINT const2 UNIQUE (cname, groupsids)",
        "ALTER TABLE groups ADD CONSTRAINT sql0910060843108101 UNIQUE (cname)",
        "ALTER TABLE items ADD CONSTRAINT const7 UNIQUE (cnumber, inttype)",
        "ALTER TABLE languages ADD CONSTRAINT sql0910060843151711 UNIQUE (longname)",
        "ALTER TABLE languages ADD CONSTRAINT const8 UNIQUE (cname, groupsids)",
        "ALTER TABLE productgroups ADD CONSTRAINT const1 UNIQUE (cname, groupsids)",
        "ALTER TABLE products ADD CONSTRAINT const8 UNIQUE (cnumber, groupsids)",
        "ALTER TABLE tablelock ADD CONSTRAINT one_lock UNIQUE (cname, rowid)",
        "ALTER TABLE users ADD CONSTRAINT const4 UNIQUE (cname, groupsids)",
        "ALTER TABLE webshops ADD CONSTRAINT const9 UNIQUE (cname, groupsids)",
        "ALTER TABLE wscontactsmapping ADD CONSTRAINT const10 UNIQUE (wscontact, groupsids, webshopsids)",
        "ALTER TABLE wsitemsmapping ADD CONSTRAINT const11 UNIQUE (wsitem, groupsids, webshopsids)",
        "ALTER TABLE accounts ADD CONSTRAINT sql0910060843164501 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE addresses ADD CONSTRAINT sql0910060843363311 FOREIGN KEY(contactsids) REFERENCES contacts(ids)",
        "ALTER TABLE addresses ADD CONSTRAINT sql0910060843363301 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE comps ADD CONSTRAINT sql0910060843233801 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE contacts ADD CONSTRAINT sql0910060843134501 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE expenses ADD CONSTRAINT sql0910060843241411 FOREIGN KEY(accountsids) REFERENCES accounts(ids)",
        "ALTER TABLE expenses ADD CONSTRAINT sql0910060843241401 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE favourites ADD CONSTRAINT sql0910060843158811 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE favourites ADD CONSTRAINT sql0910060843158801 FOREIGN KEY(usersids) REFERENCES users(ids) ON DELETE CASCADE",
        "ALTER TABLE files ADD CONSTRAINT sql0910060843145711 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE filestocontacts ADD CONSTRAINT sql0910060843296701 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE filestocontacts ADD CONSTRAINT sql0910060843296511 FOREIGN KEY(filename) REFERENCES files(cname) ON DELETE CASCADE",
        "ALTER TABLE filestocontacts ADD CONSTRAINT sql0910060843296501 FOREIGN KEY(contactsids) REFERENCES contacts(ids) ON DELETE CASCADE",
        "ALTER TABLE filestoitems ADD CONSTRAINT sql0910060843312621 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE filestoitems ADD CONSTRAINT sql0910060843312611 FOREIGN KEY(filename) REFERENCES files(cname) ON DELETE CASCADE",
        "ALTER TABLE filestoitems ADD CONSTRAINT sql0910060843312601 FOREIGN KEY(itemsids) REFERENCES items(ids) ON DELETE CASCADE",
        "ALTER TABLE filestoproducts ADD CONSTRAINT sql0910060843321621 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE filestoproducts ADD CONSTRAINT sql0910060843321611 FOREIGN KEY(filename) REFERENCES files(cname) ON DELETE CASCADE",
        "ALTER TABLE filestoproducts ADD CONSTRAINT sql0910060843321601 FOREIGN KEY(productsids) REFERENCES products(ids) ON DELETE CASCADE",
        "ALTER TABLE formatstousers ADD CONSTRAINT sql0910060843348901 FOREIGN KEY(usersids) REFERENCES users(ids) ON DELETE CASCADE",
        "ALTER TABLE items ADD CONSTRAINT sql0910060843168601 FOREIGN KEY(contactsids) REFERENCES contacts(ids) ON DELETE CASCADE",
        "ALTER TABLE items ADD CONSTRAINT sql0910060843168511 FOREIGN KEY(accountsids) REFERENCES accounts(ids)",
        "ALTER TABLE items ADD CONSTRAINT sql0910060843168501 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE itemstoaccounts ADD CONSTRAINT sql0910060843284611 FOREIGN KEY(accountsids) REFERENCES accounts(ids) ON DELETE CASCADE",
        "ALTER TABLE itemstoaccounts ADD CONSTRAINT sql0910060843284601 FOREIGN KEY(itemsids) REFERENCES items(ids) ON DELETE CASCADE",
        "ALTER TABLE languages ADD CONSTRAINT sql0910060843151721 FOREIGN KEY(filename) REFERENCES files(cname) ON DELETE CASCADE",
        "ALTER TABLE languages ADD CONSTRAINT sql0910060843151701 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE mails ADD CONSTRAINT sql0910060843225511 FOREIGN KEY(usersids) REFERENCES users(ids) ON DELETE CASCADE",
        "ALTER TABLE mails ADD CONSTRAINT sql0910060843225501 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE plugins ADD CONSTRAINT sql0910060843335511 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE plugins ADD CONSTRAINT sql0910060843335501 FOREIGN KEY(filename) REFERENCES files(cname) ON DELETE CASCADE",
        "ALTER TABLE pluginstousers ADD CONSTRAINT sql0910060843342401 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE pluginstousers ADD CONSTRAINT sql0910060843342301 FOREIGN KEY(pluginsids) REFERENCES plugins(ids) ON DELETE CASCADE",
        "ALTER TABLE productlistitems ADD CONSTRAINT sql0910060843211401 FOREIGN KEY(originalproductsids) REFERENCES products(ids) ON DELETE CASCADE",
        "ALTER TABLE productlistitems ADD CONSTRAINT sql0910060843211311 FOREIGN KEY(productlistsids) REFERENCES productlists(ids) ON DELETE CASCADE",
        "ALTER TABLE productlistitems ADD CONSTRAINT sql0910060843211301 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE productlists ADD CONSTRAINT sql0910060843205901 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE products ADD CONSTRAINT sql0910060843196121 FOREIGN KEY(productgroupsids) REFERENCES productsgroups(ids)",
        "ALTER TABLE products ADD CONSTRAINT sql0910060843196111 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE products ADD CONSTRAINT sql0910060843196101 FOREIGN KEY(taxids) REFERENCES tax(ids)",
        "ALTER TABLE reminders ADD CONSTRAINT sql0910060843368811 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE reminders ADD CONSTRAINT sql0910060843368801 FOREIGN KEY(itemsids) REFERENCES items(ids) ON DELETE CASCADE",
        "ALTER TABLE revenues ADD CONSTRAINT sql0910060843248001 FOREIGN KEY(accountsids) REFERENCES accounts(ids)",
        "ALTER TABLE revenues ADD CONSTRAINT sql0910060843247901 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE schedule ADD CONSTRAINT sql0910060843184821 FOREIGN KEY(itemsids) REFERENCES items(ids) ON DELETE CASCADE",
        "ALTER TABLE schedule ADD CONSTRAINT sql0910060843184811 FOREIGN KEY(usersids) REFERENCES users(ids) ON DELETE CASCADE",
        "ALTER TABLE schedule ADD CONSTRAINT sql0910060843184801 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE stages ADD CONSTRAINT sql0910060843375801 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE subitems ADD CONSTRAINT sql0910060843179011 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE subitems ADD CONSTRAINT sql0910060843179001 FOREIGN KEY(itemsids) REFERENCES items(ids) ON DELETE CASCADE",
        "ALTER TABLE tablelock ADD CONSTRAINT sql0910060843278901 FOREIGN KEY(usersids) REFERENCES users(ids) ON DELETE CASCADE",
        "ALTER TABLE tax ADD CONSTRAINT sql0910060843128901 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE templates ADD CONSTRAINT sql0910060843304911 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE templates ADD CONSTRAINT sql0910060843304901 FOREIGN KEY(filename) REFERENCES files(cname) ON DELETE CASCADE",
        "ALTER TABLE templatestousers ADD CONSTRAINT sql0910060843354601 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE templatestousers ADD CONSTRAINT sql0910060843354511 FOREIGN KEY(templatesids) REFERENCES templates(ids) ON DELETE CASCADE",
        "ALTER TABLE templatestousers ADD CONSTRAINT sql0910060843354501 FOREIGN KEY(usersids) REFERENCES users(ids) ON DELETE CASCADE",
        "ALTER TABLE userproperties ADD CONSTRAINT sql0910060843221901 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE users ADD CONSTRAINT sql0910060843139601 FOREIGN KEY(groupsids) REFERENCES groups(ids)",
        "ALTER TABLE wscontactsmapping ADD CONSTRAINT sql0910060843260521 FOREIGN KEY(contactsids) REFERENCES contacts(ids) ON DELETE CASCADE",
        "ALTER TABLE wscontactsmapping ADD CONSTRAINT sql0910060843260511 FOREIGN KEY(groupsids) REFERENCES groups(ids) ON DELETE CASCADE",
        "ALTER TABLE wscontactsmapping ADD CONSTRAINT sql0910060843260501 FOREIGN KEY(webshopsids) REFERENCES webshops(ids) ON DELETE CASCADE",
        "ALTER TABLE wsitemsmapping ADD CONSTRAINT sql0910060843268721 FOREIGN KEY(itemsids) REFERENCES contacts(ids) ON DELETE CASCADE",
        "ALTER TABLE wsitemsmapping ADD CONSTRAINT sql0910060843268711 FOREIGN KEY(groupsids) REFERENCES groups(ids) ON DELETE CASCADE",
        "ALTER TABLE wsitemsmapping ADD CONSTRAINT sql0910060843268701 FOREIGN KEY(webshopsids) REFERENCES webshops(ids) ON DELETE CASCADE"
    };
    public static String[] INITIAL_DATA = new String[]{
        "INSERT INTO groups (cname,description, dateadded) VALUES ('" + Messages.GROUPNAMES + "','This group is visible to everyone.', '2009-04-03 09:31:33')",
        "INSERT INTO tax(cname, dateadded, identifier) VALUES ('Default 0%', '2009-04-03 09:31:33', 'Default 0%')",
        "INSERT INTO tax(cname, dateadded, identifier, taxvalue) VALUES ('Default 19%', '2009-04-03 09:31:33', 'Default 19%', 19.0)",
        "INSERT INTO tax(cname, dateadded, identifier, taxvalue) VALUES ('Default 7%', '2009-04-03 09:31:33', 'Default 7%', 7.0)",
        "INSERT INTO productgroups (cname,description, dateadded) VALUES ('" + Messages.PRODUCTGROUPNAMES + "','This product group is visible to everyone.', '2009-04-03 09:31:33')",
        "INSERT INTO accounts (cname,description, dateadded, taxvalue, intaccounttype, frame, intprofitfid, inttaxfid, inttaxuid) VALUES ('" + Messages.ACCOUNTNAMES + "','This account is the parent account of all account frames.', '2009-04-03 09:31:33', 0.0, 0, 'builtin',0,0,0)",
        "INSERT INTO accounts (cname,description, dateadded, taxvalue, intaccounttype, frame, intprofitfid, inttaxfid, inttaxuid, intparentaccount) VALUES ('" + Messages.EXPENSE + "','', '2009-04-03 09:31:33', 0.0, " + Account.EXPENSE + ", 'builtin',0,0,0,1)",
        "INSERT INTO countries (iso, cname ) VALUES (276,'Deutschland')",
        "INSERT INTO accounts (cname,description, dateadded, taxvalue, intaccounttype, frame, intprofitfid, inttaxfid, inttaxuid, intparentaccount) VALUES ('" + Messages.INCOME + "','', '2009-04-03 09:31:33', 0.0, " + Account.INCOME + ", 'builtin',0,0,0,1)",
        "INSERT INTO users (fullname,password,cname,laf,locale,mail,language,inthighestright,datelastlog,isenabled, dateadded ) VALUES ('Administrator','5f4dcc3b5aa765d61d8327deb882cf99','admin','" + UIManager.getSystemLookAndFeelClassName() + "','de_DE','','buildin_en',0,'2009-04-03 09:31:33',1,'2009-04-03 09:31:33')",
        "INSERT INTO globalsettings (cname, groupsids, value ) VALUES ('yabs_dbversion', 1, '" + Constants.DATABASE_ORIGINAL_VERSION + "')"
    };
    public static String[] CUSTOM_STRUCTURE = new String[]{};

    public String[] getStructure() {
        if (ConnectionTypeHandler.getDriverType() == ConnectionTypeHandler.DERBY) {
            return DERBY_STRUCTURE;
        } else if (ConnectionTypeHandler.getDriverType() == ConnectionTypeHandler.MYSQL) {
            return MYSQL_STRUCTURE;
        } else {
            return CUSTOM_STRUCTURE;
        }
    }
   
    public static String[] getStructureForMigration(int conType) {
        switch (conType) {
            case ConnectionTypeHandler.DERBY:
                return DERBY_STRUCTURE;
            case ConnectionTypeHandler.MYSQL:
                return MYSQL_STRUCTURE;
            default:
                return CUSTOM_STRUCTURE;
        }
    }

    /**
     * @param CUSTOM_STRUCTURE the CUSTOM_STRUCTURE SQL commands to set
     */
    public void setCUSTOM(String[] CUSTOM_STRUCTURE) {
        DatabaseInstallation.CUSTOM_STRUCTURE = CUSTOM_STRUCTURE;
    }

    /**
     * The initial data 
     * @return
     */
    public String[] getInitialData() {
        return INITIAL_DATA;
    }
}
