CREATE TABLE ACCOUNTS  (
	IDS             	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	INTACCOUNTCLASS 	SMALLINT DEFAULT 0,
	CNAME           	VARCHAR(250) NOT NULL,
	DESCRIPTION     	VARCHAR(250) NOT NULL,
	TAXVALUE        	DOUBLE NOT NULL DEFAULT 0,
	DATEADDED       	DATE NOT NULL,
	INTADDEDBY      	BIGINT(20) DEFAULT 0,
	INTPARENTACCOUNT	BIGINT(20) DEFAULT 0,
	GROUPSIDS       	BIGINT(20) DEFAULT 1,
	INVISIBLE       	SMALLINT DEFAULT 0,
	INTACCOUNTTYPE  	SMALLINT NOT NULL,
	INTPROFITFID    	SMALLINT NOT NULL,
	INTTAXFID       	SMALLINT NOT NULL,
	INTTAXUID       	SMALLINT NOT NULL,
	FRAME           	VARCHAR(25) NOT NULL,
	HIERARCHYPATH   	VARCHAR(250) DEFAULT NULL
);

CREATE TABLE ADDRESSES  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	GROUPSIDS  	BIGINT(20) DEFAULT 1,
	CONTACTSIDS	BIGINT(20),
	TITLE      	VARCHAR(250) DEFAULT NULL,
	TAXNUMBER  	VARCHAR(250),
	PRENAME    	VARCHAR(250) DEFAULT NULL,
	CNAME      	VARCHAR(250) DEFAULT NULL,
	STREET     	VARCHAR(250) DEFAULT NULL,
	ZIP        	VARCHAR(50) DEFAULT NULL,
	CITY       	VARCHAR(300) DEFAULT NULL,
	COMPANY    	VARCHAR(250) DEFAULT NULL,
	DEPARTMENT 	VARCHAR(250) DEFAULT NULL,
	COUNTRY    	VARCHAR(50) DEFAULT NULL,
	ISMALE     	SMALLINT DEFAULT 0,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE DEFAULT NULL,
	INTTYPE    	SMALLINT DEFAULT 0,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE COMPS  (
	IDS          	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	GROUPSIDS    	BIGINT(20) DEFAULT 1,
	CNAME        	VARCHAR(250) DEFAULT NULL,
	STATE        	VARCHAR(250) DEFAULT NULL,
	PHONEPREFIX  	VARCHAR(250) DEFAULT NULL,
	BUSINESS     	VARCHAR(250) DEFAULT NULL,
	TAXADVISOR   	VARCHAR(250) DEFAULT NULL,
	CITY         	VARCHAR(250) DEFAULT NULL,
	TAXADVJOB    	VARCHAR(250) DEFAULT NULL,
	STREET       	VARCHAR(250) DEFAULT NULL,
	STB          	VARCHAR(250) DEFAULT NULL,
	EMAIL        	VARCHAR(250) DEFAULT NULL,
	NAME         	VARCHAR(250) DEFAULT NULL,
	ZIPCODE      	VARCHAR(250) DEFAULT NULL,
	PHONE        	VARCHAR(250) DEFAULT NULL,
	FIRSTNAME    	VARCHAR(250) DEFAULT NULL,
	TAXAUTHORITY 	VARCHAR(250) DEFAULT NULL,
	TAXNUMBER    	VARCHAR(250) DEFAULT NULL,
	TAXADVMANDANT	VARCHAR(250) DEFAULT NULL,
	DATEADDED    	DATE NOT NULL,
	ISMALE       	SMALLINT DEFAULT 0,
	ISENABLED    	SMALLINT DEFAULT 1,
	INTADDEDBY   	BIGINT(20) DEFAULT 0,
	INVISIBLE    	SMALLINT DEFAULT 0,
	RESERVE1     	VARCHAR(500) DEFAULT NULL,
	RESERVE2     	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE CONTACTS  (
	IDS           	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNUMBER       	VARCHAR(250) DEFAULT NULL,
	TAXNUMBER     	VARCHAR(250),
	TITLE         	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS     	BIGINT(20) DEFAULT 1,
	COUNTRY       	VARCHAR(50) DEFAULT NULL,
	PRENAME       	VARCHAR(250) DEFAULT NULL,
	CNAME         	VARCHAR(250) DEFAULT NULL,
	STREET        	VARCHAR(250) DEFAULT NULL,
	ZIP           	VARCHAR(50) DEFAULT NULL,
	CITY          	VARCHAR(300) DEFAULT NULL,
	MAINPHONE     	VARCHAR(250) DEFAULT NULL,
	FAX           	VARCHAR(250) DEFAULT NULL,
	MOBILEPHONE   	VARCHAR(250) DEFAULT NULL,
	WORKPHONE     	VARCHAR(250) DEFAULT NULL,
	MAILADDRESS   	VARCHAR(350) DEFAULT NULL,
	COMPANY       	VARCHAR(250) DEFAULT NULL,
	DEPARTMENT    	VARCHAR(250) DEFAULT NULL,
	WEBSITE       	VARCHAR(350) DEFAULT NULL,
	NOTES         	VARCHAR(10000),
	DATEADDED     	DATE NOT NULL,
	ISACTIVE      	SMALLINT DEFAULT 0,
	ISCUSTOMER    	SMALLINT DEFAULT 0,
	ISMANUFACTURER	SMALLINT DEFAULT 0,
	ISSUPPLIER    	SMALLINT DEFAULT 0,
	ISCOMPANY     	SMALLINT DEFAULT 0,
	ISMALE        	SMALLINT DEFAULT 0,
	ISENABLED     	SMALLINT DEFAULT 1,
	INTADDEDBY    	BIGINT(20) DEFAULT 0,
	INVISIBLE     	SMALLINT DEFAULT 0,
	RESERVE1      	VARCHAR(500) DEFAULT NULL,
	RESERVE2      	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE COUNTRIES  (
	IDS      	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME    	VARCHAR(250) NOT NULL,
	ISO      	SMALLINT NOT NULL,
	GROUPSIDS	BIGINT(20) DEFAULT 1,
	RESERVE1 	VARCHAR(500) DEFAULT NULL,
	RESERVE2 	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE EXPENSES  (
	IDS            	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	GROUPSIDS      	BIGINT(20) DEFAULT 1,
	CNUMBER        	VARCHAR(250) DEFAULT NULL,
	CNAME          	VARCHAR(250) DEFAULT NULL,
	ACCOUNTSIDS    	BIGINT(20),
	NETVALUE       	DOUBLE DEFAULT 0,
	TAXPERCENTVALUE	DOUBLE DEFAULT 0,
	BRUTVALUE      	DOUBLE DEFAULT 0,
	DESCRIPTION    	VARCHAR(5000) DEFAULT NULL,
	DATEADDED      	DATE NOT NULL,
	INTADDEDBY     	BIGINT(20) DEFAULT 0,
	INVISIBLE      	SMALLINT DEFAULT 0,
	RESERVE1       	VARCHAR(500) DEFAULT NULL,
	RESERVE2       	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE FAVOURITES  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250) NOT NULL,
	USERSIDS  	BIGINT(20),
	GROUPSIDS 	BIGINT(20) DEFAULT 1,
	ITEMSIDS  	BIGINT(20) NOT NULL,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	INVISIBLE 	SMALLINT DEFAULT 0,
	RESERVE1  	VARCHAR(500) DEFAULT NULL,
	RESERVE2  	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE FILES  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(25) NOT NULL,
	GROUPSIDS 	BIGINT(20) DEFAULT 1,
	DATEADDED 	DATE NOT NULL,
	DATA      	BLOB(5242880) NOT NULL,
	FILESIZE  	BIGINT(20) NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	INVISIBLE 	SMALLINT DEFAULT 0
);

CREATE TABLE FILESTOCONTACTS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	CONTACTSIDS	BIGINT(20) NOT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTSIZE    	BIGINT(20) DEFAULT 0,
	MIMETYPE   	VARCHAR(25) DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) DEFAULT 1
);

CREATE TABLE FILESTOITEMS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	ITEMSIDS   	BIGINT(20) NOT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTSIZE    	BIGINT(20) DEFAULT 0,
	MIMETYPE   	VARCHAR(25) DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) DEFAULT 1
);

CREATE TABLE FILESTOPRODUCTS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	PRODUCTSIDS	BIGINT(20) NOT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTSIZE    	BIGINT(20) DEFAULT 0,
	MIMETYPE   	VARCHAR(25) DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) DEFAULT 1
);

CREATE TABLE FORMATSTOUSERS  (
	IDS     	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME   	VARCHAR(250) NOT NULL,
	USERSIDS	BIGINT(20),
	INTTYPE 	SMALLINT DEFAULT 0
);

CREATE TABLE GLOBALSETTINGS  (
	IDS      	BIGINT(20) DEFAULT 1,
	CNAME    	VARCHAR(250) NOT NULL,
	GROUPSIDS	BIGINT(20) DEFAULT 1,
	VALUE    	VARCHAR(250) NOT NULL
	);

CREATE TABLE GROUPS  (
	IDS          	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME        	VARCHAR(250) NOT NULL,
	DESCRIPTION  	VARCHAR(750) DEFAULT NULL,
	DEFAULTS     	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS    	BIGINT(20) DEFAULT 0,
	DATEADDED    	DATE NOT NULL,
	RESERVE1     	VARCHAR(500) DEFAULT NULL,
	INTADDEDBY   	BIGINT(20) DEFAULT 0,
	HIERARCHYPATH	VARCHAR(500) DEFAULT NULL,
	RESERVE2     	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE HISTORY  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250) NOT NULL,
	USERNAME  	VARCHAR(250) NOT NULL,
	DBIDENTITY	VARCHAR(25) NOT NULL,
	INTITEM   	SMALLINT NOT NULL,
	GROUPSIDS 	BIGINT(20) DEFAULT 0,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	RESERVE1  	VARCHAR(500) DEFAULT NULL,
	RESERVE2  	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE ITEMS  (
	IDS          	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME        	VARCHAR(250) NOT NULL,
	CNUMBER      	VARCHAR(250) NOT NULL,
	DESCRIPTION  	VARCHAR(2500) DEFAULT NULL,
	GROUPSIDS    	BIGINT(20) DEFAULT 1,
	ACCOUNTSIDS  	BIGINT(20) DEFAULT 1,
	CONTACTSIDS  	BIGINT(20),
	NETVALUE     	DOUBLE DEFAULT 0,
	TAXVALUE     	DOUBLE DEFAULT 0,
	DISCOUNTVALUE	DOUBLE DEFAULT 0,
	SHIPPINGVALUE	DOUBLE DEFAULT 0,
	DATETODO     	DATE DEFAULT NULL,
	DATEEND      	DATE DEFAULT NULL,
	INTREMINDERS 	INTEGER DEFAULT 0,
	INTTYPE      	SMALLINT DEFAULT 0,
	DATEADDED    	DATE NOT NULL,
	INTADDEDBY   	BIGINT(20) DEFAULT 0,
	INVISIBLE    	SMALLINT DEFAULT 0,
	INTSTATUS    	SMALLINT DEFAULT 0,
	HIERARCHYPATH	VARCHAR(500) DEFAULT NULL,
	RESERVE1     	VARCHAR(500) DEFAULT NULL,
	RESERVE2     	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE ITEMSTOACCOUNTS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	ITEMSIDS   	BIGINT(20) NOT NULL,
	ACCOUNTSIDS	BIGINT(20),
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE LANGUAGES  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250) NOT NULL,
	GROUPSIDS 	BIGINT(20) DEFAULT 1,
	LONGNAME  	VARCHAR(250) NOT NULL,
	FILENAME  	VARCHAR(25) NOT NULL,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	INVISIBLE 	SMALLINT DEFAULT 0,
	RESERVE1  	VARCHAR(500) DEFAULT NULL,
	RESERVE2  	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE MAILS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(1000) NOT NULL,
	DATEADDED  	DATE NOT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	GROUPSIDS  	BIGINT(20) DEFAULT 1,
	INVISIBLE  	SMALLINT DEFAULT 0,
	USERSIDS   	BIGINT(20),
	DESCRIPTION	VARCHAR(5000) NOT NULL
);

CREATE TABLE PLUGINS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) DEFAULT 1
);

CREATE TABLE PLUGINSTOUSERS  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250) NOT NULL,
	USERSIDS  	BIGINT(20) NOT NULL,
	PLUGINSIDS	BIGINT(20) NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	DATEADDED 	DATE NOT NULL,
	GROUPSIDS 	BIGINT(20) DEFAULT 1
);

CREATE TABLE PRODUCTGROUPS  (
	IDS             	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME           	VARCHAR(250) NOT NULL,
	DESCRIPTION     	VARCHAR(750) DEFAULT NULL,
	DEFAULTS        	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS       	BIGINT(20) DEFAULT 0,
	PRODUCTGROUPSIDS	BIGINT(20) DEFAULT 0,
	DATEADDED       	DATE NOT NULL,
	HIERARCHYPATH   	VARCHAR(500) DEFAULT NULL,
	RESERVE1        	VARCHAR(500) DEFAULT NULL,
	INTADDEDBY      	BIGINT(20) DEFAULT 0,
	RESERVE2        	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE PRODUCTLISTITEMS  (
	IDS                	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME              	VARCHAR(2500) DEFAULT NULL,
	LINKURL            	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS          	BIGINT(20) DEFAULT 1,
	PRODUCTLISTSIDS    	BIGINT(20),
	ORIGINALPRODUCTSIDS	BIGINT(20),
	COUNTVALUE         	DOUBLE NOT NULL DEFAULT 0,
	QUANTITYVALUE      	DOUBLE NOT NULL DEFAULT 0,
	MEASURE            	VARCHAR(250) NOT NULL,
	DESCRIPTION        	VARCHAR(1000) DEFAULT NULL,
	INTERNALVALUE      	DOUBLE DEFAULT 0,
	TOTALNETVALUE      	DOUBLE DEFAULT 0,
	TOTALBRUTVALUE     	DOUBLE DEFAULT 0,
	EXTERNALVALUE      	DOUBLE DEFAULT 0,
	TAXPERCENTVALUE    	DOUBLE NOT NULL DEFAULT 0,
	DATEADDED          	DATE NOT NULL,
	INTADDEDBY         	BIGINT(20) DEFAULT 0,
	INVISIBLE          	SMALLINT DEFAULT 0,
	RESERVE1           	VARCHAR(500) DEFAULT NULL,
	RESERVE2           	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE PRODUCTLISTS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(2500) DEFAULT NULL,
	GROUPSIDS  	BIGINT(20) DEFAULT 1,
	DESCRIPTION	VARCHAR(1000) DEFAULT NULL,
	DATEADDED  	DATE NOT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	INVISIBLE  	SMALLINT DEFAULT 0,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE PRODUCTS  (
	IDS             	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME           	VARCHAR(500) NOT NULL,
	CNUMBER         	VARCHAR(250) NOT NULL,
	DESCRIPTION     	VARCHAR(5000),
	EXTERNALNETVALUE	DOUBLE DEFAULT 0,
	INTERNALNETVALUE	DOUBLE DEFAULT 0,
	MEASURE         	VARCHAR(250) NOT NULL,
	TAXIDS          	BIGINT(20),
	MANUFACTURERSIDS	BIGINT(20) DEFAULT 0,
	SUPPLIERSIDS    	BIGINT(20) DEFAULT 0,
	GROUPSIDS       	BIGINT(20) DEFAULT 1,
	PRODUCTGROUPSIDS	BIGINT(20) DEFAULT 1,
	URL             	VARCHAR(250) DEFAULT NULL,
	EAN             	VARCHAR(25) DEFAULT NULL,
	REFERENCE       	VARCHAR(50) DEFAULT NULL,
	DATEADDED       	DATE NOT NULL,
	INTADDEDBY      	BIGINT(20) DEFAULT 0,
	INVISIBLE       	SMALLINT DEFAULT 0,
	INTTYPE         	SMALLINT NOT NULL,
	DEFAULTIMAGE    	VARCHAR(30) DEFAULT NULL,
	RESERVE1        	VARCHAR(500) DEFAULT NULL,
	RESERVE2        	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE REMINDERS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	STAGESIDS  	BIGINT(20) NOT NULL,
	ITEMSIDS   	BIGINT(20) NOT NULL,
	EXTRAVALUE 	DOUBLE DEFAULT 0,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) DEFAULT 1
);

CREATE TABLE REVENUES  (
	IDS            	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	GROUPSIDS      	BIGINT(20) DEFAULT 1,
	CNUMBER        	VARCHAR(250) DEFAULT NULL,
	CNAME          	VARCHAR(250) DEFAULT NULL,
	ACCOUNTSIDS    	BIGINT(20),
	NETVALUE       	DOUBLE DEFAULT 0,
	TAXPERCENTVALUE	DOUBLE DEFAULT 0,
	BRUTVALUE      	DOUBLE DEFAULT 0,
	DESCRIPTION    	VARCHAR(5000) DEFAULT NULL,
	DATEADDED      	DATE NOT NULL,
	INTADDEDBY     	BIGINT(20) DEFAULT 0,
	INVISIBLE      	SMALLINT DEFAULT 0,
	RESERVE1       	VARCHAR(500) DEFAULT NULL,
	RESERVE2       	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE SCHEDULE  (
	IDS          	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME        	VARCHAR(250) NOT NULL,
	GROUPSIDS    	BIGINT(20) DEFAULT 1,
	USERSIDS     	BIGINT(20),
	ITEMSIDS     	BIGINT(20),
	STOPDATE     	DATE NOT NULL,
	STARTDATE    	DATE NOT NULL,
	NEXTDATE     	DATE NOT NULL,
	ISDONE       	SMALLINT DEFAULT 0,
	INTERVALMONTH	SMALLINT NOT NULL,
	DATEADDED    	DATE NOT NULL,
	INTADDEDBY   	BIGINT(20) DEFAULT 0,
	INVISIBLE    	SMALLINT DEFAULT 0,
	RESERVE1     	VARCHAR(500) DEFAULT NULL,
	RESERVE2     	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE SEARCHINDEX  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	DBIDENTITY	VARCHAR(25) NOT NULL,
	GROUPSIDS 	BIGINT(20),
	ROWID     	BIGINT(20) NOT NULL,
	TEXT      	VARCHAR(5000) DEFAULT NULL
	);

CREATE TABLE STAGES  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	EXTRAVALUE 	DOUBLE DEFAULT 0,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) DEFAULT 1
);

CREATE TABLE SUBITEMS  (
	IDS                	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME              	VARCHAR(5000) DEFAULT NULL,
	ITEMSIDS           	BIGINT(20),
	GROUPSIDS          	BIGINT(20) DEFAULT 1,
	ORIGINALPRODUCTSIDS	BIGINT(20) DEFAULT NULL,
	COUNTVALUE         	DOUBLE NOT NULL DEFAULT 0,
	QUANTITYVALUE      	DOUBLE NOT NULL DEFAULT 0,
	MEASURE            	VARCHAR(250) NOT NULL,
	LINKURL            	VARCHAR(1000) DEFAULT NULL,
	DESCRIPTION        	VARCHAR(1000) DEFAULT NULL,
	INTERNALVALUE      	DOUBLE DEFAULT 0,
	TOTALNETVALUE      	DOUBLE DEFAULT 0,
	TOTALBRUTVALUE     	DOUBLE DEFAULT 0,
	EXTERNALVALUE      	DOUBLE DEFAULT 0,
	TAXPERCENTVALUE    	DOUBLE NOT NULL DEFAULT 0,
	DATEDELIVERY       	DATE DEFAULT NULL,
	DATEADDED          	DATE NOT NULL,
	INTADDEDBY         	BIGINT(20) DEFAULT 0,
	INVISIBLE          	SMALLINT DEFAULT 0,
	RESERVE1           	VARCHAR(500) DEFAULT NULL,
	RESERVE2           	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE TABLELOCK  (
	IDS     	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME   	VARCHAR(250),
	ROWID   	BIGINT(20) NOT NULL,
	USERSIDS	BIGINT(20),
	RESERVE1	VARCHAR(500) DEFAULT NULL,
	RESERVE2	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE TAX  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250),
	TAXVALUE  	DOUBLE DEFAULT 0,
	IDENTIFIER	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS 	BIGINT(20) DEFAULT 1,
	COUNTRY   	VARCHAR(50) DEFAULT NULL,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	INVISIBLE 	SMALLINT DEFAULT 0,
	RESERVE1  	VARCHAR(500) DEFAULT NULL,
	RESERVE2  	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE TEMPLATES  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	FORMAT     	VARCHAR(55) DEFAULT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	INTSIZE    	BIGINT(20) DEFAULT 0,
	MIMETYPE   	VARCHAR(25) DEFAULT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) DEFAULT 1
);

CREATE TABLE TEMPLATESTOUSERS  (
	IDS         	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME       	VARCHAR(250) NOT NULL,
	USERSIDS    	BIGINT(20),
	TEMPLATESIDS	BIGINT(20) NOT NULL,
	GROUPSIDS   	BIGINT(20) DEFAULT 1
);

CREATE TABLE TRASHBIN  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(500),
	ROWID      	BIGINT(20) NOT NULL,
	DESCRIPTION	VARCHAR(2500),
	DELETEME   	SMALLINT DEFAULT 1,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE USERPROPERTIES  (
	IDS       	BIGINT(20) DEFAULT 1,
	CNAME     	VARCHAR(250) NOT NULL,
	VALUE     	VARCHAR(250) NOT NULL,
	USERSIDS  	BIGINT(20) NOT NULL,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	GROUPSIDS 	BIGINT(20) DEFAULT 1,
	INVISIBLE 	SMALLINT DEFAULT 0
	);

CREATE TABLE USERS  (
	IDS              	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME            	VARCHAR(250) NOT NULL,
	GROUPSIDS        	BIGINT(20) DEFAULT 1,
	INTDEFAULTACCOUNT	BIGINT(20) DEFAULT 1,
	COMPSIDS         	BIGINT(20) DEFAULT 0,
	INTDEFAULTSTATUS 	BIGINT(20) DEFAULT 1,
	FULLNAME         	VARCHAR(250) NOT NULL,
	PASSWORD         	VARCHAR(250) NOT NULL,
	LAF              	VARCHAR(50) DEFAULT NULL,
	LOCALE           	VARCHAR(50) DEFAULT NULL,
	DEFCOUNTRY       	VARCHAR(50) DEFAULT NULL,
	MAIL             	VARCHAR(50) DEFAULT NULL,
	LANGUAGE         	VARCHAR(50) DEFAULT NULL,
	INTHIGHESTRIGHT  	SMALLINT DEFAULT 3,
	ISENABLED        	SMALLINT DEFAULT 1,
	ISRGROUPED       	SMALLINT DEFAULT 0,
	ISLOGGEDIN       	SMALLINT DEFAULT 0,
	DATELASTLOG      	DATE DEFAULT NULL,
	DATEADDED        	DATE NOT NULL,
	INTADDEDBY       	BIGINT(20) DEFAULT 0,
	INVISIBLE        	SMALLINT DEFAULT 0,
	RESERVE1         	VARCHAR(500) DEFAULT NULL,
	RESERVE2         	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE WEBSHOPS  (
	IDS                 	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME               	VARCHAR(250) NOT NULL,
	DESCRIPTION         	VARCHAR(750) DEFAULT NULL,
	GROUPSIDS           	BIGINT(20) DEFAULT 0,
	DATEADDED           	DATE NOT NULL,
	ISREQUESTCOMPRESSION	SMALLINT DEFAULT 0,
	ISAUTHENTICATED     	SMALLINT DEFAULT 0,
	USERNAME            	VARCHAR(50) DEFAULT NULL,
	PASSWORD            	VARCHAR(50) DEFAULT NULL,
	RESERVE1            	VARCHAR(500) DEFAULT NULL,
	INTADDEDBY          	BIGINT(20) DEFAULT 0,
	INTERVAL            	BIGINT(20) DEFAULT 0,
	URL                 	VARCHAR(500) DEFAULT NULL,
	RESERVE2            	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE WSCONTACTSMAPPING  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	WEBSHOPSIDS	BIGINT(20),
	CNAME      	VARCHAR(250) NOT NULL,
	GROUPSIDS  	BIGINT(20),
	CONTACTSIDS	BIGINT(20),
	WSCONTACT  	VARCHAR(250) NOT NULL,
	DATEADDED  	DATE DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	INVISIBLE  	SMALLINT DEFAULT 0,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE WSITEMSMAPPING  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	WEBSHOPSIDS	BIGINT(20),
	CNAME      	VARCHAR(250) NOT NULL,
	GROUPSIDS  	BIGINT(20),
	ITEMSIDS   	BIGINT(20),
	WSITEM     	VARCHAR(250) NOT NULL,
	DATEADDED  	DATE DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	INVISIBLE  	SMALLINT DEFAULT 0,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE UNIQUE INDEX SQL091006084310810
	ON GROUPS(CNAME);

CREATE UNIQUE INDEX SQL091006084310820
	ON GROUPS(IDS);

CREATE UNIQUE INDEX SQL091006084311391
	ON PRODUCTGROUPS(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084311390
	ON PRODUCTGROUPS(IDS);

CREATE UNIQUE INDEX SQL091006084311800
	ON HISTORY(IDS);

CREATE UNIQUE INDEX SQL091006084312110
	ON COUNTRIES(ISO);

CREATE UNIQUE INDEX SQL091006084312111
	ON COUNTRIES(IDS);

CREATE UNIQUE INDEX SQL091006084312620
	ON GLOBALSETTINGS(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084312900
	ON TAX(IDS);

CREATE INDEX SQL091006084312890
	ON TAX(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084313452
	ON CONTACTS(CNUMBER, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084313451
	ON CONTACTS(IDS);

CREATE INDEX SQL091006084313450
	ON CONTACTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084313971
	ON USERS(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084313970
	ON USERS(IDS);

CREATE INDEX SQL091006084313960
	ON USERS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084314570
	ON FILES(CNAME);

CREATE UNIQUE INDEX SQL091006084314572
	ON FILES(IDS);

CREATE INDEX SQL091006084314571
	ON FILES(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084315174
	ON LANGUAGES(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084315171
	ON LANGUAGES(LONGNAME);

CREATE UNIQUE INDEX SQL091006084315173
	ON LANGUAGES(IDS);

CREATE INDEX SQL091006084315170
	ON LANGUAGES(GROUPSIDS);

CREATE INDEX SQL091006084315172
	ON LANGUAGES(FILENAME);

CREATE UNIQUE INDEX SQL091006084315882
	ON FAVOURITES(IDS);

CREATE INDEX SQL091006084315880
	ON FAVOURITES(USERSIDS);

CREATE INDEX SQL091006084315881
	ON FAVOURITES(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084316451
	ON ACCOUNTS(IDS);

CREATE INDEX SQL091006084316450
	ON ACCOUNTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084316862
	ON ITEMS(CNUMBER, INTTYPE);

CREATE UNIQUE INDEX SQL091006084316861
	ON ITEMS(IDS);

CREATE INDEX SQL091006084316850
	ON ITEMS(GROUPSIDS);

CREATE INDEX SQL091006084316851
	ON ITEMS(ACCOUNTSIDS);

CREATE INDEX SQL091006084316860
	ON ITEMS(CONTACTSIDS);

CREATE UNIQUE INDEX SQL091006084317902
	ON SUBITEMS(IDS);

CREATE INDEX SQL091006084317900
	ON SUBITEMS(ITEMSIDS);

CREATE INDEX SQL091006084317901
	ON SUBITEMS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084318483
	ON SCHEDULE(IDS);

CREATE INDEX SQL091006084318480
	ON SCHEDULE(GROUPSIDS);

CREATE INDEX SQL091006084318481
	ON SCHEDULE(USERSIDS);

CREATE INDEX SQL091006084318482
	ON SCHEDULE(ITEMSIDS);

CREATE UNIQUE INDEX SQL091006084319621
	ON PRODUCTS(CNUMBER, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084319620
	ON PRODUCTS(IDS);

CREATE INDEX SQL091006084319610
	ON PRODUCTS(TAXIDS);

CREATE INDEX SQL091006084319611
	ON PRODUCTS(GROUPSIDS);

CREATE INDEX SQL091006084319612
	ON PRODUCTS(PRODUCTGROUPSIDS);

CREATE UNIQUE INDEX SQL091006084320591
	ON PRODUCTLISTS(IDS);

CREATE INDEX SQL091006084320590
	ON PRODUCTLISTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084321141
	ON PRODUCTLISTITEMS(IDS);

CREATE INDEX SQL091006084321130
	ON PRODUCTLISTITEMS(GROUPSIDS);

CREATE INDEX SQL091006084321131
	ON PRODUCTLISTITEMS(PRODUCTLISTSIDS);

CREATE INDEX SQL091006084321140
	ON PRODUCTLISTITEMS(ORIGINALPRODUCTSIDS);

CREATE INDEX SQL091006084322190
	ON USERPROPERTIES(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084322552
	ON MAILS(IDS);

CREATE INDEX SQL091006084322550
	ON MAILS(GROUPSIDS);

CREATE INDEX SQL091006084322551
	ON MAILS(USERSIDS);

CREATE UNIQUE INDEX SQL091006084323381
	ON COMPS(IDS);

CREATE INDEX SQL091006084323380
	ON COMPS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084324160
	ON EXPENSES(IDS);

CREATE INDEX SQL091006084324140
	ON EXPENSES(GROUPSIDS);

CREATE INDEX SQL091006084324141
	ON EXPENSES(ACCOUNTSIDS);

CREATE UNIQUE INDEX SQL091006084324810
	ON REVENUES(IDS);

CREATE INDEX SQL091006084324790
	ON REVENUES(GROUPSIDS);

CREATE INDEX SQL091006084324800
	ON REVENUES(ACCOUNTSIDS);

CREATE UNIQUE INDEX SQL091006084325551
	ON WEBSHOPS(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084325550
	ON WEBSHOPS(IDS);

CREATE UNIQUE INDEX SQL091006084326054
	ON WSCONTACTSMAPPING(WSCONTACT, GROUPSIDS, WEBSHOPSIDS);

CREATE UNIQUE INDEX SQL091006084326053
	ON WSCONTACTSMAPPING(IDS);

CREATE INDEX SQL091006084326050
	ON WSCONTACTSMAPPING(WEBSHOPSIDS);

CREATE INDEX SQL091006084326051
	ON WSCONTACTSMAPPING(GROUPSIDS);

CREATE INDEX SQL091006084326052
	ON WSCONTACTSMAPPING(CONTACTSIDS);

CREATE UNIQUE INDEX SQL091006084326881
	ON WSITEMSMAPPING(WSITEM, GROUPSIDS, WEBSHOPSIDS);

CREATE UNIQUE INDEX SQL091006084326880
	ON WSITEMSMAPPING(IDS);

CREATE INDEX SQL091006084326870
	ON WSITEMSMAPPING(WEBSHOPSIDS);

CREATE INDEX SQL091006084326871
	ON WSITEMSMAPPING(GROUPSIDS);

CREATE INDEX SQL091006084326872
	ON WSITEMSMAPPING(ITEMSIDS);

CREATE UNIQUE INDEX SQL091006084327910
	ON TABLELOCK(IDS);

CREATE UNIQUE INDEX SQL091006084327911
	ON TABLELOCK(CNAME, ROWID);

CREATE INDEX SQL091006084327890
	ON TABLELOCK(USERSIDS);

CREATE UNIQUE INDEX SQL091006084328480
	ON ITEMSTOACCOUNTS(IDS);

CREATE INDEX SQL091006084328460
	ON ITEMSTOACCOUNTS(ITEMSIDS);

CREATE INDEX SQL091006084328461
	ON ITEMSTOACCOUNTS(ACCOUNTSIDS);

CREATE UNIQUE INDEX SQL091006084329120
	ON TRASHBIN(IDS);

CREATE UNIQUE INDEX SQL091006084329671
	ON FILESTOCONTACTS(IDS);

CREATE INDEX SQL091006084329650
	ON FILESTOCONTACTS(CONTACTSIDS);

CREATE INDEX SQL091006084329651
	ON FILESTOCONTACTS(FILENAME);

CREATE INDEX SQL091006084329670
	ON FILESTOCONTACTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084330492
	ON TEMPLATES(IDS);

CREATE INDEX SQL091006084330490
	ON TEMPLATES(FILENAME);

CREATE INDEX SQL091006084330491
	ON TEMPLATES(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084331263
	ON FILESTOITEMS(IDS);

CREATE INDEX SQL091006084331260
	ON FILESTOITEMS(ITEMSIDS);

CREATE INDEX SQL091006084331261
	ON FILESTOITEMS(FILENAME);

CREATE INDEX SQL091006084331262
	ON FILESTOITEMS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084332163
	ON FILESTOPRODUCTS(IDS);

CREATE INDEX SQL091006084332160
	ON FILESTOPRODUCTS(PRODUCTSIDS);

CREATE INDEX SQL091006084332161
	ON FILESTOPRODUCTS(FILENAME);

CREATE INDEX SQL091006084332162
	ON FILESTOPRODUCTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084333560
	ON PLUGINS(IDS);

CREATE INDEX SQL091006084333550
	ON PLUGINS(FILENAME);

CREATE INDEX SQL091006084333551
	ON PLUGINS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084334241
	ON PLUGINSTOUSERS(IDS);

CREATE INDEX SQL091006084334230
	ON PLUGINSTOUSERS(PLUGINSIDS);

CREATE INDEX SQL091006084334240
	ON PLUGINSTOUSERS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084334891
	ON FORMATSTOUSERS(IDS);

CREATE INDEX SQL091006084334890
	ON FORMATSTOUSERS(USERSIDS);

CREATE UNIQUE INDEX SQL091006084335461
	ON TEMPLATESTOUSERS(IDS);

CREATE INDEX SQL091006084335450
	ON TEMPLATESTOUSERS(USERSIDS);

CREATE INDEX SQL091006084335451
	ON TEMPLATESTOUSERS(TEMPLATESIDS);

CREATE INDEX SQL091006084335460
	ON TEMPLATESTOUSERS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084336332
	ON ADDRESSES(IDS);

CREATE INDEX SQL091006084336330
	ON ADDRESSES(GROUPSIDS);

CREATE INDEX SQL091006084336331
	ON ADDRESSES(CONTACTSIDS);

CREATE UNIQUE INDEX SQL091006084336882
	ON REMINDERS(IDS);

CREATE INDEX SQL091006084336880
	ON REMINDERS(ITEMSIDS);

CREATE INDEX SQL091006084336881
	ON REMINDERS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084337581
	ON STAGES(IDS);

CREATE INDEX SQL091006084337580
	ON STAGES(GROUPSIDS);

	ALTER TABLE CONTACTS
	ADD CONSTRAINT CONST3
	 UNIQUE (CNUMBER, GROUPSIDS) ;

ALTER TABLE COUNTRIES
	ADD CONSTRAINT SQL091006084312110
	 UNIQUE (ISO) ;

ALTER TABLE FILES
	ADD CONSTRAINT SQL091006084314570
	 UNIQUE (CNAME) ;

ALTER TABLE GLOBALSETTINGS
	ADD CONSTRAINT CONST2
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE GROUPS
	ADD CONSTRAINT SQL091006084310810
	 UNIQUE (CNAME) ;

ALTER TABLE ITEMS
	ADD CONSTRAINT CONST7
	 UNIQUE (CNUMBER, INTTYPE) ;

ALTER TABLE LANGUAGES
	ADD CONSTRAINT SQL091006084315171
	 UNIQUE (LONGNAME) ;

ALTER TABLE LANGUAGES
	ADD CONSTRAINT CONST6
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE PRODUCTGROUPS
	ADD CONSTRAINT CONST1
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE PRODUCTS
	ADD CONSTRAINT CONST8
	 UNIQUE (CNUMBER, GROUPSIDS) ;

ALTER TABLE TABLELOCK
	ADD CONSTRAINT ONE_LOCK
	 UNIQUE (CNAME, ROWID) ;

ALTER TABLE USERS
	ADD CONSTRAINT CONST4
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE WEBSHOPS
	ADD CONSTRAINT CONST9
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE WSCONTACTSMAPPING
	ADD CONSTRAINT CONST10
	 UNIQUE (WSCONTACT, GROUPSIDS, WEBSHOPSIDS) ;

ALTER TABLE WSITEMSMAPPING
	ADD CONSTRAINT CONST11
	 UNIQUE (WSITEM, GROUPSIDS, WEBSHOPSIDS) ;

ALTER TABLE ACCOUNTS
	ADD CONSTRAINT SQL091006084316450
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE ADDRESSES
	ADD CONSTRAINT SQL091006084336331
	FOREIGN KEY(CONTACTSIDS)
	REFERENCES CONTACTS(IDS);

ALTER TABLE ADDRESSES
	ADD CONSTRAINT SQL091006084336330
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE COMPS
	ADD CONSTRAINT SQL091006084323380
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE CONTACTS
	ADD CONSTRAINT SQL091006084313450
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE EXPENSES
	ADD CONSTRAINT SQL091006084324141
	FOREIGN KEY(ACCOUNTSIDS)
	REFERENCES ACCOUNTS(IDS);

ALTER TABLE EXPENSES
	ADD CONSTRAINT SQL091006084324140
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FAVOURITES
	ADD CONSTRAINT SQL091006084315881
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FAVOURITES
	ADD CONSTRAINT SQL091006084315880
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE FILES
	ADD CONSTRAINT SQL091006084314571
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FILESTOCONTACTS
	ADD CONSTRAINT SQL091006084329670
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FILESTOCONTACTS
	ADD CONSTRAINT SQL091006084329651
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOCONTACTS
	ADD CONSTRAINT SQL091006084329650
	FOREIGN KEY(CONTACTSIDS)
	REFERENCES CONTACTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOITEMS
	ADD CONSTRAINT SQL091006084331262
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FILESTOITEMS
	ADD CONSTRAINT SQL091006084331261
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOITEMS
	ADD CONSTRAINT SQL091006084331260
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOPRODUCTS
	ADD CONSTRAINT SQL091006084332162
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FILESTOPRODUCTS
	ADD CONSTRAINT SQL091006084332161
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOPRODUCTS
	ADD CONSTRAINT SQL091006084332160
	FOREIGN KEY(PRODUCTSIDS)
	REFERENCES PRODUCTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE FORMATSTOUSERS
	ADD CONSTRAINT SQL091006084334890
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE ITEMS
	ADD CONSTRAINT SQL091006084316860
	FOREIGN KEY(CONTACTSIDS)
	REFERENCES CONTACTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE ITEMS
	ADD CONSTRAINT SQL091006084316851
	FOREIGN KEY(ACCOUNTSIDS)
	REFERENCES ACCOUNTS(IDS);

ALTER TABLE ITEMS
	ADD CONSTRAINT SQL091006084316850
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE ITEMSTOACCOUNTS
	ADD CONSTRAINT SQL091006084328461
	FOREIGN KEY(ACCOUNTSIDS)
	REFERENCES ACCOUNTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE ITEMSTOACCOUNTS
	ADD CONSTRAINT SQL091006084328460
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE LANGUAGES
	ADD CONSTRAINT SQL091006084315172
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE LANGUAGES
	ADD CONSTRAINT SQL091006084315170
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE MAILS
	ADD CONSTRAINT SQL091006084322551
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE MAILS
	ADD CONSTRAINT SQL091006084322550
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PLUGINS
	ADD CONSTRAINT SQL091006084333551
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PLUGINS
	ADD CONSTRAINT SQL091006084333550
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE PLUGINSTOUSERS
	ADD CONSTRAINT SQL091006084334240
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PLUGINSTOUSERS
	ADD CONSTRAINT SQL091006084334230
	FOREIGN KEY(PLUGINSIDS)
	REFERENCES PLUGINS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE PRODUCTLISTITEMS
	ADD CONSTRAINT SQL091006084321140
	FOREIGN KEY(ORIGINALPRODUCTSIDS)
	REFERENCES PRODUCTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE PRODUCTLISTITEMS
	ADD CONSTRAINT SQL091006084321131
	FOREIGN KEY(PRODUCTLISTSIDS)
	REFERENCES PRODUCTLISTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE PRODUCTLISTITEMS
	ADD CONSTRAINT SQL091006084321130
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PRODUCTLISTS
	ADD CONSTRAINT SQL091006084320590
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PRODUCTS
	ADD CONSTRAINT SQL091006084319612
	FOREIGN KEY(PRODUCTGROUPSIDS)
	REFERENCES PRODUCTGROUPS(IDS);

ALTER TABLE PRODUCTS
	ADD CONSTRAINT SQL091006084319611
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PRODUCTS
	ADD CONSTRAINT SQL091006084319610
	FOREIGN KEY(TAXIDS)
	REFERENCES TAX(IDS);

ALTER TABLE REMINDERS
	ADD CONSTRAINT SQL091006084336881
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE REMINDERS
	ADD CONSTRAINT SQL091006084336880
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE REVENUES
	ADD CONSTRAINT SQL091006084324800
	FOREIGN KEY(ACCOUNTSIDS)
	REFERENCES ACCOUNTS(IDS);

ALTER TABLE REVENUES
	ADD CONSTRAINT SQL091006084324790
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE SCHEDULE
	ADD CONSTRAINT SQL091006084318482
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE SCHEDULE
	ADD CONSTRAINT SQL091006084318481
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE SCHEDULE
	ADD CONSTRAINT SQL091006084318480
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE STAGES
	ADD CONSTRAINT SQL091006084337580
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE SUBITEMS
	ADD CONSTRAINT SQL091006084317901
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE SUBITEMS
	ADD CONSTRAINT SQL091006084317900
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE TABLELOCK
	ADD CONSTRAINT SQL091006084327890
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE TAX
	ADD CONSTRAINT SQL091006084312890
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE TEMPLATES
	ADD CONSTRAINT SQL091006084330491
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE TEMPLATES
	ADD CONSTRAINT SQL091006084330490
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE TEMPLATESTOUSERS
	ADD CONSTRAINT SQL091006084335460
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE TEMPLATESTOUSERS
	ADD CONSTRAINT SQL091006084335451
	FOREIGN KEY(TEMPLATESIDS)
	REFERENCES TEMPLATES(IDS)
	ON DELETE CASCADE ;

ALTER TABLE TEMPLATESTOUSERS
	ADD CONSTRAINT SQL091006084335450
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE USERPROPERTIES
	ADD CONSTRAINT SQL091006084322190
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE USERS
	ADD CONSTRAINT SQL091006084313960
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE WSCONTACTSMAPPING
	ADD CONSTRAINT SQL091006084326052
	FOREIGN KEY(CONTACTSIDS)
	REFERENCES CONTACTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSCONTACTSMAPPING
	ADD CONSTRAINT SQL091006084326051
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSCONTACTSMAPPING
	ADD CONSTRAINT SQL091006084326050
	FOREIGN KEY(WEBSHOPSIDS)
	REFERENCES WEBSHOPS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSITEMSMAPPING
	ADD CONSTRAINT SQL091006084326872
	FOREIGN KEY(ITEMSIDS)
	REFERENCES CONTACTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSITEMSMAPPING
	ADD CONSTRAINT SQL091006084326871
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSITEMSMAPPING
	ADD CONSTRAINT SQL091006084326870
	FOREIGN KEY(WEBSHOPSIDS)
	REFERENCES WEBSHOPS(IDS)
	ON DELETE CASCADE ;

CREATE TRIGGER CONTACTS_INDEXER1
	AFTER INSERT ON CONTACTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids, 'contacts',newdata.ids,newdata.cnumber||' '||newdata.taxnumber||' '||newdata.title||' '||newdata.country||' '|| newdata.prename||' '|| newdata.cname||' '|| newdata.street||' '||newdata.zip||' '|| newdata.city ||' '||newdata.mainphone||' '||newdata.fax||' '||newdata.mobilephone||' '||newdata.workphone||' '||newdata.mailaddress||' '||newdata.company||' '|| newdata.department||' '||newdata.website||' '||newdata.notes);

CREATE TRIGGER CONTACTS_INDEXER2
	AFTER UPDATE ON CONTACTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'contacts' AND  rowid = newdata.ids;

CREATE TRIGGER CONTACTS_INDEXER3
	AFTER UPDATE ON CONTACTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'contacts',newdata.ids,newdata.cnumber||' '||newdata.taxnumber||' '||newdata.title||' '||newdata.country||' '|| newdata.prename||' '|| newdata.cname||' '|| newdata.street||' '||newdata.zip||' '|| newdata.city ||' '||newdata.mainphone||' '||newdata.fax||' '||newdata.mobilephone||' '||newdata.workphone||' '||newdata.mailaddress||' '||newdata.company||' '|| newdata.department||' '||newdata.website||' '||newdata.notes);

CREATE TRIGGER CONTACTS_INDEXER4
	AFTER DELETE ON CONTACTS
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'contacts' AND  rowid = newdata.ids;

CREATE TRIGGER CONTACTS_TRASH1
	AFTER UPDATE ON CONTACTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible,'contacts',newdata.ids,newdata.cnumber||' ('|| newdata.cname||')');

CREATE TRIGGER CONTACTS_TRASH2
	AFTER DELETE ON CONTACTS
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM trashbin WHERE cname = 'contacts' AND  rowid = newdata.ids;

CREATE TRIGGER EXPENSES_INDEXER1
	AFTER INSERT ON EXPENSES
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'expenses',newdata.ids,newdata.cname||' '||newdata.dateadded);

CREATE TRIGGER EXPENSES_INDEXER2
	AFTER UPDATE ON EXPENSES
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'expenses' AND  rowid = newdata.ids;

CREATE TRIGGER EXPENSES_INDEXER3
	AFTER UPDATE ON EXPENSES
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'expenses',newdata.ids,newdata.cname||' '||newdata.dateadded);

CREATE TRIGGER EXPENSES_INDEXER4
	AFTER DELETE ON EXPENSES
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'expenses' AND  rowid = newdata.ids;

CREATE TRIGGER EXPENSES_TRASH1
	AFTER UPDATE ON EXPENSES
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible,'expenses',newdata.ids,newdata.cname);

CREATE TRIGGER EXPENSES_TRASH2
	AFTER DELETE ON EXPENSES
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM trashbin WHERE cname = 'expenses' AND  rowid = newdata.ids;

CREATE TRIGGER FILESTOCONTACTS_INDEXER1
	AFTER INSERT ON FILESTOCONTACTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'filestocontacts',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.filename);

CREATE TRIGGER FILESTOCONTACTS_INDEXER2
	AFTER UPDATE ON FILESTOCONTACTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'filestocontacts' AND  rowid = newdata.ids;

CREATE TRIGGER FILESTOCONTACTS_INDEXER3
	AFTER UPDATE ON FILESTOCONTACTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'filestocontacts',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.filename);

CREATE TRIGGER FILESTOCONTACTS_INDEXER4
	AFTER DELETE ON FILESTOCONTACTS
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'filestocontacts' AND  rowid = newdata.ids;

CREATE TRIGGER GROUPS_INDEXER1
	AFTER INSERT ON GROUPS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'groups',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.dateadded);

CREATE TRIGGER GROUPS_INDEXER2
	AFTER UPDATE ON GROUPS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'groups' AND  rowid = newdata.ids;

CREATE TRIGGER GROUPS_INDEXER3
	AFTER UPDATE ON GROUPS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'groups',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.dateadded);

CREATE TRIGGER GROUPS_INDEXER4
	AFTER DELETE ON GROUPS
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'groups' AND  rowid = newdata.ids;

CREATE TRIGGER ITEMS_INDEXER1
	AFTER INSERT ON ITEMS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'items',newdata.ids,newdata.cname||' '||newdata.dateadded);

CREATE TRIGGER ITEMS_INDEXER2
	AFTER UPDATE ON ITEMS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'items' AND  rowid = newdata.ids;

CREATE TRIGGER ITEMS_INDEXER3
	AFTER UPDATE ON ITEMS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'items',newdata.ids,newdata.cname||' '||newdata.dateadded);

CREATE TRIGGER ITEMS_INDEXER4
	AFTER DELETE ON ITEMS
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'items' AND  rowid = newdata.ids;

CREATE TRIGGER ITEMS_TRASH1
	AFTER UPDATE ON ITEMS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible,'items',newdata.ids,newdata.cname);

CREATE TRIGGER ITEMS_TRASH2
	AFTER DELETE ON ITEMS
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM trashbin WHERE cname = 'items' AND  rowid = newdata.ids;

CREATE TRIGGER PRODUCTS_INDEXER1
	AFTER INSERT ON PRODUCTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'products',newdata.ids,newdata.cname||' '||newdata.cnumber||' '||newdata.description||' '||newdata.dateadded);

CREATE TRIGGER PRODUCTS_INDEXER2
	AFTER UPDATE ON PRODUCTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'products' AND  rowid = newdata.ids;

CREATE TRIGGER PRODUCTS_INDEXER3
	AFTER UPDATE ON PRODUCTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'products',newdata.ids,newdata.cname||' '||newdata.cnumber||' '||newdata.description||' '||newdata.dateadded);

CREATE TRIGGER PRODUCTS_INDEXER4
	AFTER DELETE ON PRODUCTS
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'products' AND  rowid = newdata.ids;

CREATE TRIGGER PRODUCTS_TRASH1
	AFTER UPDATE ON PRODUCTS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible, 'products',newdata.ids,newdata.cnumber||' ('|| newdata.cname||')');

CREATE TRIGGER PRODUCTS_TRASH2
	AFTER DELETE ON PRODUCTS
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM trashbin WHERE cname = 'products' AND  rowid = newdata.ids;

CREATE TRIGGER REVENUES_INDEXER1
	AFTER INSERT ON REVENUES
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'revenues',newdata.ids,newdata.cname||' '||newdata.dateadded);

CREATE TRIGGER REVENUES_INDEXER2
	AFTER UPDATE ON REVENUES
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'revenues' AND  rowid = newdata.ids;

CREATE TRIGGER REVENUES_INDEXER3
	AFTER UPDATE ON REVENUES
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'revenues',newdata.ids,newdata.cname||' '||newdata.dateadded);

CREATE TRIGGER REVENUES_INDEXER4
	AFTER DELETE ON REVENUES
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'revenues' AND  rowid = newdata.ids;

CREATE TRIGGER REVENUES_TRASH1
	AFTER UPDATE ON REVENUES
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (newdata.invisible,'revenues',newdata.ids,newdata.cname);

CREATE TRIGGER REVENUES_TRASH2
	AFTER DELETE ON REVENUES
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM trashbin WHERE cname = 'revenues' AND  rowid = newdata.ids;

CREATE TRIGGER SUBITEMS_INDEXER1
	AFTER INSERT ON SUBITEMS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'subitems',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.dateadded);

CREATE TRIGGER SUBITEMS_INDEXER2
	AFTER UPDATE ON SUBITEMS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'subitems' AND  rowid = newdata.ids;

CREATE TRIGGER SUBITEMS_INDEXER3
	AFTER UPDATE ON SUBITEMS
	REFERENCING NEW AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (newdata.groupsids,'subitems',newdata.ids,newdata.cname||' '||newdata.description||' '||newdata.dateadded);

CREATE TRIGGER SUBITEMS_INDEXER4
	AFTER DELETE ON SUBITEMS
	REFERENCING OLD AS NEWDATA
	FOR EACH ROW  MODE DB2SQL
	DELETE FROM searchindex WHERE dbidentity = 'subitems' AND  rowid = newdata.ids;

CREATE TRIGGER THRASH_HANDLER1
	AFTER INSERT ON TRASHBIN
	FOR EACH STATEMENT  MODE DB2SQL
	DELETE FROM trashbin WHERE deleteme = 0;

CREATE TRIGGER THRASH_HANDLER2
	AFTER INSERT ON TRASHBIN
	FOR EACH STATEMENT  MODE DB2SQL
	DELETE FROM trashbin WHERE ids IN (SELECT ids FROM trashbin WHERE EXISTS( SELECT ids FROM trashbin AS tmptable WHERE trashbin.cname = tmptable.cname AND trashbin.rowid = tmptable.rowid HAVING trashbin.ids < MAX(tmptable.ids) ) );


INSERT INTO GROUPS(CNAME, DESCRIPTION, DEFAULTS, GROUPSIDS, DATEADDED, RESERVE1, INTADDEDBY, HIERARCHYPATH, RESERVE2)
  VALUES( 'All Groups', 'This group is visible to everyone.', NULL, 0, '2009-04-03', NULL, 0, NULL, NULL);
INSERT INTO ACCOUNTS(INTACCOUNTCLASS, CNAME, DESCRIPTION, TAXVALUE, DATEADDED, INTADDEDBY, INTPARENTACCOUNT, GROUPSIDS, INVISIBLE, INTACCOUNTTYPE, INTPROFITFID, INTTAXFID, INTTAXUID, FRAME, HIERARCHYPATH)
  VALUES( 0, 'All Accounts', 'This account is the parent account of all account frames.', 0.0, '2009-04-03', 0, 0, 1, 0, 0, 0, 0, 0, 'builtin', NULL);
INSERT INTO ACCOUNTS(INTACCOUNTCLASS, CNAME, DESCRIPTION, TAXVALUE, DATEADDED, INTADDEDBY, INTPARENTACCOUNT, GROUPSIDS, INVISIBLE, INTACCOUNTTYPE, INTPROFITFID, INTTAXFID, INTTAXUID, FRAME, HIERARCHYPATH)
  VALUES( 0, 'Expenses', '', 0.0, '2009-04-03', 0, 1, 1, 0, 2, 0, 0, 0, 'builtin', NULL);
INSERT INTO ACCOUNTS(INTACCOUNTCLASS, CNAME, DESCRIPTION, TAXVALUE, DATEADDED, INTADDEDBY, INTPARENTACCOUNT, GROUPSIDS, INVISIBLE, INTACCOUNTTYPE, INTPROFITFID, INTTAXFID, INTTAXUID, FRAME, HIERARCHYPATH)
  VALUES( 0, 'Income', '', 0.0, '2009-04-03', 0, 1, 1, 0, 3, 0, 0, 0, 'builtin', NULL);
INSERT INTO COUNTRIES(CNAME, ISO, GROUPSIDS, RESERVE1, RESERVE2)
  VALUES( 'Deutschland', 276, 1, NULL, NULL);
INSERT INTO GLOBALSETTINGS(CNAME, GROUPSIDS, VALUE)
  VALUES( 'yabs_dbversion', 1, '1.0');
INSERT INTO PRODUCTGROUPS(CNAME, DESCRIPTION, DEFAULTS, GROUPSIDS, PRODUCTGROUPSIDS, DATEADDED, HIERARCHYPATH, RESERVE1, INTADDEDBY, RESERVE2)
  VALUES( 'All Products', 'This product group is visible to everyone.', NULL, 0, 0, '2009-04-03', NULL, NULL, 0, NULL);
INSERT INTO SEARCHINDEX(DBIDENTITY, GROUPSIDS, ROWID, TEXT)
  VALUES( 'groups', 0, 1, 'All Groups This group is visible to everyone. 2009-04-03');
INSERT INTO TAX(CNAME, TAXVALUE, IDENTIFIER, GROUPSIDS, COUNTRY, DATEADDED, INTADDEDBY, INVISIBLE, RESERVE1, RESERVE2)
  VALUES( 'Default 0%', 0.0, 'Default 0%', 1, NULL, '2009-04-03', 0, 0, NULL, NULL);
INSERT INTO TAX(CNAME, TAXVALUE, IDENTIFIER, GROUPSIDS, COUNTRY, DATEADDED, INTADDEDBY, INVISIBLE, RESERVE1, RESERVE2)
  VALUES( 'Default 19%', 19.0, 'Default 19%', 1, NULL, '2009-04-03', 0, 0, NULL, NULL);
INSERT INTO TAX( CNAME, TAXVALUE, IDENTIFIER, GROUPSIDS, COUNTRY, DATEADDED, INTADDEDBY, INVISIBLE, RESERVE1, RESERVE2)
  VALUES( 'Default 7%', 7.0, 'Default 7%', 1, NULL, '2009-04-03', 0, 0, NULL, NULL);
INSERT INTO USERS(CNAME, GROUPSIDS, INTDEFAULTACCOUNT, COMPSIDS, INTDEFAULTSTATUS, FULLNAME, PASSWORD, LAF, LOCALE, DEFCOUNTRY, MAIL, LANGUAGE, INTHIGHESTRIGHT, ISENABLED, ISRGROUPED, ISLOGGEDIN, DATELASTLOG, DATEADDED, INTADDEDBY, INVISIBLE, RESERVE1, RESERVE2)
  VALUES( 'admin', 1, 1, 0, 1, 'Administrator', '5f4dcc3b5aa765d61d8327deb882cf99', 'com.sun.java.swing.plaf.windows.WindowsLookAndFeel', 'en_GB', '', '', 'buildin_en', 0, 1, 0, 0, '2009-10-06', '2009-04-03', 0, 0, NULL, NULL);

