/*
 * * This file is an extension part of MP by anti43 /GPL.
 *
 * MP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MP. If not, see <http://www.gnu.org/licenses/>.
 *
 * TaxFormDialog.java
 *
 * Created on 15.03.2009
 */
package mpv5.ui.dialogs;

import java.awt.Component;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JScrollPane;
import javax.swing.text.JTextComponent;

/**
 * The dialog frame for personal data.
 * @author hnauheim
 */
public class TaxAddressDialog extends javax.swing.JDialog {

  private List<JTextComponent> inputfields = new ArrayList<JTextComponent>();
  private Map<String, String> map;

  /** Creates new form TaxFormDialog
   * @param The root pane
   * @param The visible frame title
   * @param model The taxModel to use
   */
  public TaxAddressDialog(Frame parent, String title, Map<String, String> m) {
    super(parent, title, true);
    super.setBounds(200, 200, 200, 200);
    super.setResizable(false);
    this.map = m;
    initComponents();
    collectInputfields();
    setData();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    streetField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    taxnumberField = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    profField = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    mandantField = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    cityField = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    faArea = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    stbArea = new javax.swing.JTextArea();
    jLabel10 = new javax.swing.JLabel();
    phone2Field = new javax.swing.JTextField();
    phone1Field = new javax.swing.JTextField();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    nameField1 = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    nameField2 = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    mandantField1 = new javax.swing.JTextField();
    jTextField1 = new javax.swing.JTextField();
    taxnumberField1 = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mpv5/resources/languages/Panels"); // NOI18N
    jLabel1.setText(bundle.getString("TaxAddressDialog.compname")); // NOI18N

    nameField.setToolTipText("Name des Unternehmers/Firma");
    nameField.setName("comp_name"); // NOI18N

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel2.setText(bundle.getString("TaxAddressDialog.compstreet")); // NOI18N

    streetField.setToolTipText("Straße und Hausnummer des Unternehmens");
    streetField.setName("comp_street"); // NOI18N

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel3.setText(bundle.getString("TaxAddressDialog.comptaxauthority")); // NOI18N

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel4.setText(bundle.getString("TaxAddressDialog.compstate")); // NOI18N

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel5.setText(bundle.getString("TaxAddressDialog.comptaxnumber")); // NOI18N

    taxnumberField.setToolTipText("Beispiel: 123/123/12345");
    taxnumberField.setName("comp_state"); // NOI18N

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel6.setText(bundle.getString("TaxAddressDialog.comptaxadvjob")); // NOI18N

    profField.setName("comp_taxadvjob"); // NOI18N

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel7.setText(bundle.getString("TaxAddressDialog.comptaxadvmandant")); // NOI18N

    mandantField.setName("comp_taxadvmandant"); // NOI18N

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel8.setText(bundle.getString("TaxAddressDialog.compphone")); // NOI18N

    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel9.setText(bundle.getString("TaxAddressDialog.compcity")); // NOI18N

    cityField.setToolTipText("Firmenort");
    cityField.setName("comp_city"); // NOI18N

    faArea.setColumns(20);
    faArea.setRows(5);
    faArea.setToolTipText(bundle.getString("TaxAddressDialog.taxoffice.tooltip")); // NOI18N
    faArea.setName("comp_taxauthority"); // NOI18N
    jScrollPane1.setViewportView(faArea);

    stbArea.setColumns(20);
    stbArea.setRows(5);
    stbArea.setToolTipText(bundle.getString("TaxAddressDialog.taxadvisor.tooltip")); // NOI18N
    stbArea.setName("comp_taxadvisor"); // NOI18N
    jScrollPane2.setViewportView(stbArea);

    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel10.setText(bundle.getString("TaxAddressDialog.comptaxadvisor")); // NOI18N

    phone2Field.setName("comp_phone"); // NOI18N

    phone1Field.setName("comp_phoneprefix"); // NOI18N

    cancelButton.setText("Abbrechen");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    nameField1.setToolTipText("Name des Unternehmers/Firma");
    nameField1.setName("comp_firstname"); // NOI18N

    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel11.setText(bundle.getString("TaxAddressDialog.compfirstname")); // NOI18N

    nameField2.setToolTipText("Name des Unternehmers/Firma");
    nameField2.setName("comp_business"); // NOI18N

    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel12.setText(bundle.getString("TaxAddressDialog.compbusiness")); // NOI18N

    mandantField1.setToolTipText("Nur ausfüllen, falls die Meldung von einem Steuerberater o. ä. erstellt wurde");
    mandantField1.setName("comp_taxnumber"); // NOI18N

    jTextField1.setName("comp_zipcode"); // NOI18N

    taxnumberField1.setToolTipText("Beispiel: 123/123/12345");
    taxnumberField1.setName("comp_email"); // NOI18N

    jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel13.setText(bundle.getString("TaxAddressDialog.compemail")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel8)
              .addComponent(jLabel13)
              .addComponent(jLabel5)
              .addComponent(jLabel10, 0, 194, Short.MAX_VALUE)
              .addComponent(jLabel1)
              .addComponent(jLabel3)
              .addComponent(jLabel11)
              .addComponent(jLabel12)
              .addComponent(jLabel2)
              .addComponent(jLabel9)
              .addComponent(jLabel7)
              .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(phone1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
              .addComponent(mandantField, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
              .addComponent(profField, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
              .addComponent(mandantField1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
              .addComponent(streetField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(nameField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
              .addComponent(nameField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
              .addComponent(taxnumberField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(167, 167, 167)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(taxnumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(336, Short.MAX_VALUE)
            .addComponent(cancelButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, mandantField, mandantField1, nameField, profField, streetField, taxnumberField});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel11))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nameField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel12))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(taxnumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8)
          .addComponent(phone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(phone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(taxnumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel13))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(mandantField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(profField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(mandantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel10))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(okButton)
          .addComponent(cancelButton))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    getValues();
    setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    setVisible(false);
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void collectInputfields() {
    Component[] comps = getContentPane().getComponents();
    for (int i = 0; i < comps.length; i++) {
      if (comps[i] instanceof JTextComponent) {
        JTextComponent comp = (JTextComponent) comps[i];
        inputfields.add(comp);
      }
      if (comps[i] instanceof JScrollPane) {
        JScrollPane sp = (JScrollPane) comps[i];
        JTextComponent comp = (JTextComponent) sp.getViewport().getView();
        inputfields.add(comp);
      }
    }
  }

  /**
   * Fills the input text components
   */
  private void setData() {
    for (int i = 0; i < inputfields.size(); i++) {
      JTextComponent comp = inputfields.get(i);
      if (map.containsKey(comp.getName())) {
        comp.setText(map.get(comp.getName()));
      }
    }
  }

  private void getValues() {
    for (int i = 0; i < inputfields.size(); i++) {
      JTextComponent comp = inputfields.get(i);
      map.put(comp.getName(), comp.getText());
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      @Override
      public void run() {
//        ProfitModel model = new ProfitModel(null);
        TaxAddressDialog dialog = new TaxAddressDialog(new javax.swing.JFrame(), "bla", null);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {

          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextField cityField;
  private javax.swing.JTextArea faArea;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField mandantField;
  private javax.swing.JTextField mandantField1;
  private javax.swing.JTextField nameField;
  private javax.swing.JTextField nameField1;
  private javax.swing.JTextField nameField2;
  private javax.swing.JButton okButton;
  private javax.swing.JTextField phone1Field;
  private javax.swing.JTextField phone2Field;
  private javax.swing.JTextField profField;
  private javax.swing.JTextArea stbArea;
  private javax.swing.JTextField streetField;
  private javax.swing.JTextField taxnumberField;
  private javax.swing.JTextField taxnumberField1;
  // End of variables declaration//GEN-END:variables
}
