/*
 * Kundes.java
 *
 * Created on 28. Dezember 2007, 19:17
 */
package mp4.panels.kontakte;

import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import mp4.globals.Strings;
import mp4.items.visual.Popup;
import mp4.datenbank.verbindung.ConnectionHandler;
import mp4.items.Kunde;
import mp4.items.HistoryItem;
import mp4.frames.mainframe;
import mp4.items.visual.serialLetter;
import mp4.utils.tabellen.SelectionCheck;
import mp4.logs.*;
import mp4.benutzerverwaltung.User;
import mp4.interfaces.ContactPanel;
import mp4.utils.tabellen.models.CustomerBAListTableModel;

import mp4.items.People;
import mp4.items.Angebot;
import mp4.items.Rechnung;
import mp4.panels.misc.NumberFormatEditor;
import mp4.utils.export.textdatei.VCard;
import mp4.utils.files.DialogForFile;
import mp4.utils.files.FileReaderWriter;
import mp4.utils.tabellen.TableFormat;
import mp4.utils.tabellen.models.ContactListTableModel;

/**
 *
 * @author  anti43
 */
public class customersView extends mp4.items.visual.CommonPanel implements mp4.datenbank.installation.Tabellen, ContactPanel {

    public Kunde current;
    private String[][] liste;
    private mainframe mainframe;
    private boolean edited = false;
    private boolean numberfieldedited;

    /** Creates new form Kundes
     * @param frame 
     */
    public customersView(mainframe frame) {

        initComponents();
        current = new Kunde();
        this.mainframe = frame;
        updateListTable();
        fillSearchTable();
    }

    public customersView(Kunde current, mainframe frame) {
        initComponents();
        this.current = current;
        this.mainframe = frame;
        updateListTable();
        fillSearchTable();
        setContact(current);
    }

    private void fillSearchTable() {
        String[][] list = current.select("id, nummer, firma ", null, null, "nummer", false);
        String k = "id, " + "Nummer,Firma";

        this.jTable3.setModel(new DefaultTableModel(list, k.split(",")));
        TableFormat.stripFirst(jTable3);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

jTabbedPane1 = new javax.swing.JTabbedPane();
jPanel2 = new javax.swing.JPanel();
jPanel5 = new javax.swing.JPanel();
jScrollPane5 = new javax.swing.JScrollPane();
jTable3 = new javax.swing.JTable()

{
    public boolean isCellEditable(int x, int y) {
        return false;
    }
}
;
jPanel4 = new javax.swing.JPanel();
jLabel2 = new javax.swing.JLabel();
jTextField1 = new javax.swing.JTextField();
jTextField2 = new javax.swing.JTextField();
jLabel3 = new javax.swing.JLabel();
jTextField3 = new javax.swing.JTextField();
jLabel4 = new javax.swing.JLabel();
jPanel6 = new javax.swing.JPanel();
jButton7 = new javax.swing.JButton();
jLabel1 = new javax.swing.JLabel();
jPanel7 = new javax.swing.JPanel();
jTextField11 = new javax.swing.JTextField();
jLabel12 = new javax.swing.JLabel();
jLabel15 = new javax.swing.JLabel();
jTextField14 = new javax.swing.JTextField();
jLabel13 = new javax.swing.JLabel();
jLabel16 = new javax.swing.JLabel();
jTextField15 = new javax.swing.JTextField();
jTextField12 = new javax.swing.JTextField();
jLabel14 = new javax.swing.JLabel();
jTextField13 = new javax.swing.JTextField();
jPanel8 = new javax.swing.JPanel();
jTextField6 = new javax.swing.JTextField();
jLabel7 = new javax.swing.JLabel();
jLabel18 = new javax.swing.JLabel();
jTextField16 = new javax.swing.JTextField();
jLabel9 = new javax.swing.JLabel();
jLabel11 = new javax.swing.JLabel();
jTextField10 = new javax.swing.JTextField();
jTextField8 = new javax.swing.JTextField();
jLabel8 = new javax.swing.JLabel();
jLabel10 = new javax.swing.JLabel();
jTextField9 = new javax.swing.JTextField();
jTextField7 = new javax.swing.JTextField();
jPanel9 = new javax.swing.JPanel();
jTextField4 = new javax.swing.JTextField();
jLabel5 = new javax.swing.JLabel();
jLabel6 = new javax.swing.JLabel();
jTextField5 = new javax.swing.JTextField();
jLabel20 = new javax.swing.JLabel();
jTextField17 = new javax.swing.JTextField();
jButton16 = new javax.swing.JButton();
jPanel10 = new javax.swing.JPanel();
jScrollPane2 = new javax.swing.JScrollPane();
jTextArea1 = new javax.swing.JTextArea();
jLabel17 = new javax.swing.JLabel();
jPanel14 = new javax.swing.JPanel();
jPanel11 = new javax.swing.JPanel();
jScrollPane3 = new javax.swing.JScrollPane();
jTable1 = new javax.swing.JTable()

{
    public boolean isCellEditable(int x, int y) {
        return false;
    }
}

;
jLabel19 = new javax.swing.JLabel();
jPanel12 = new javax.swing.JPanel();
jScrollPane6 = new javax.swing.JScrollPane();
jTable4 = new javax.swing.JTable()

{
    public boolean isCellEditable(int x, int y) {
        return false;
    }
}

;
jLabel21 = new javax.swing.JLabel();
jPanel3 = new javax.swing.JPanel();
jScrollPane4 = new javax.swing.JScrollPane();
jTable2 = new javax.swing.JTable()
 {
    public boolean isCellEditable(int x, int y) {
        return false;
    }
}



;
jButton11 = new javax.swing.JButton();
jPanel1 = new javax.swing.JPanel();
jToolBar2 = new javax.swing.JToolBar();
jButton20 = new javax.swing.JButton();
jButton14 = new javax.swing.JButton();
jButton13 = new javax.swing.JButton();
jSeparator2 = new javax.swing.JToolBar.Separator();
jButton10 = new javax.swing.JButton();
jButton8 = new javax.swing.JButton();
jButton9 = new javax.swing.JButton();
jSeparator3 = new javax.swing.JToolBar.Separator();
jButton18 = new javax.swing.JButton();

jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
jTabbedPane1.setOpaque(true);

jPanel2.setBackground(new java.awt.Color(255, 255, 255));

jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datensätze"));

jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

jTable3.setAutoCreateRowSorter(true);
jTable3.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		{null, null}
	},
	new String [] {
		"Nummer", "Firma"
	}
) {
	boolean[] canEdit = new boolean [] {
		false, false
	};

	public boolean isCellEditable(int rowIndex, int columnIndex) {
		return canEdit [columnIndex];
	}
});
jTable3.setRequestFocusEnabled(false);
jTable3.setUpdateSelectionOnSort(false);
jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jTable3MouseClicked(evt);
}
});
jScrollPane5.setViewportView(jTable3);

javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
jPanel5.setLayout(jPanel5Layout);
jPanel5Layout.setHorizontalGroup(
jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
);
jPanel5Layout.setVerticalGroup(
jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
);

jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Suche"));
jPanel4.setMaximumSize(new java.awt.Dimension(240, 32767));

jLabel2.setText("Nummer:");

jTextField1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField1ActionPerformed(evt);
}
});

jTextField2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField2ActionPerformed(evt);
}
});

jLabel3.setText("Name:");

jTextField3.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField3ActionPerformed(evt);
}
});

jLabel4.setText("Firma:");

javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
jPanel4.setLayout(jPanel4Layout);
jPanel4Layout.setHorizontalGroup(
jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel2)
.addComponent(jLabel3)
.addComponent(jLabel4))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(jTextField3)
.addComponent(jTextField2)
.addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);
jPanel4Layout.setVerticalGroup(
jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel4Layout.createSequentialGroup()
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel2)
.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3)
.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel4)
.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);

jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

jButton7.setText("AC");
jButton7.setFocusable(false);
jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jButton7.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton7ActionPerformed(evt);
}
});

jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
jLabel1.setText("Kontaktdaten");

jPanel7.setBackground(new java.awt.Color(227, 219, 202));
jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jTextField11.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField11ActionPerformed(evt);
}
});

jLabel12.setText("Telefon");

jLabel15.setText("Email");

jTextField14.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField14ActionPerformed(evt);
}
});

jLabel13.setText("Fax");

jLabel16.setText("Webseite");

jTextField15.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField15ActionPerformed(evt);
}
});

jTextField12.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField12ActionPerformed(evt);
}
});

jLabel14.setText("Mobil");

jTextField13.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField13ActionPerformed(evt);
}
});

javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
jPanel7.setLayout(jPanel7Layout);
jPanel7Layout.setHorizontalGroup(
jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel7Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel12)
.addComponent(jLabel15))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel7Layout.createSequentialGroup()
.addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel13)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(jPanel7Layout.createSequentialGroup()
.addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jLabel16)))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(jPanel7Layout.createSequentialGroup()
.addComponent(jLabel14)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
.addComponent(jTextField15))
.addContainerGap(28, Short.MAX_VALUE))
);
jPanel7Layout.setVerticalGroup(
jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel7Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel7Layout.createSequentialGroup()
.addGap(31, 31, 31)
.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel15)
.addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel16)
.addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel12)
.addComponent(jLabel13)
.addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel14)
.addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);

jPanel8.setBackground(new java.awt.Color(227, 219, 202));
jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
editListener(evt);
}
});
jTextField6.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField6ActionPerformed(evt);
}
});

jLabel7.setText("Anrede");

jLabel18.setText("PLZ");

jTextField16.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField16ActionPerformed(evt);
}
});

jLabel9.setText("Vorname");

jLabel11.setText("Ort");

jTextField10.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField10ActionPerformed(evt);
}
});

jTextField8.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField8ActionPerformed(evt);
}
});

jLabel8.setText("Name");

jLabel10.setText("Strasse");

jTextField9.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField9ActionPerformed(evt);
}
});

jTextField7.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField7ActionPerformed(evt);
}
});

javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
jPanel8.setLayout(jPanel8Layout);
jPanel8Layout.setHorizontalGroup(
jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel18)
.addComponent(jLabel7))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(jPanel8Layout.createSequentialGroup()
.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel9))
.addGroup(jPanel8Layout.createSequentialGroup()
.addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jLabel11)))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(jTextField10)
.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel10)
.addComponent(jLabel8))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(jTextField9)
.addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
.addContainerGap(30, Short.MAX_VALUE))
);
jPanel8Layout.setVerticalGroup(
jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
.addComponent(jLabel7)
.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel9)
.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel8)
.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
.addComponent(jLabel18)
.addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel11)
.addComponent(jLabel10)
.addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(20, 20, 20))
);

jPanel9.setBackground(new java.awt.Color(227, 219, 202));
jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jTextField4.setEditable(false);
jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jTextField4MouseClicked(evt);
}
});
jTextField4.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField4ActionPerformed(evt);
}
});
jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
public void keyTyped(java.awt.event.KeyEvent evt) {
jTextField4KeyTyped(evt);
}
});

jLabel5.setText("Nummer");

jLabel6.setText("Firma");

jTextField5.setEnabled(false);
jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jTextField5MouseClicked(evt);
}
});

jLabel20.setText("KSNr");

jTextField17.setEnabled(false);
jTextField17.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jTextField17MouseClicked(evt);
}
});
jTextField17.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jTextField17ActionPerformed(evt);
}
});

jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/small/search.png"))); // NOI18N
jButton16.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton16ActionPerformed(evt);
}
});

javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
jPanel9.setLayout(jPanel9Layout);
jPanel9Layout.setHorizontalGroup(
jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel9Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel5)
.addComponent(jLabel6))
.addGap(10, 10, 10)
.addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(jTextField4)
.addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
.addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel9Layout.createSequentialGroup()
.addGap(25, 25, 25)
.addComponent(jLabel20)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(jPanel9Layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
.addGap(33, 33, 33))
);
jPanel9Layout.setVerticalGroup(
jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel9Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addGroup(jPanel9Layout.createSequentialGroup()
.addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel5)
.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(11, 11, 11))
.addGroup(jPanel9Layout.createSequentialGroup()
.addComponent(jButton16)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
.addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
.addComponent(jLabel6)
.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel20))
.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);

jPanel10.setBackground(new java.awt.Color(227, 219, 202));
jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
jScrollPane2.setAutoscrolls(true);

jTextArea1.setColumns(20);
jTextArea1.setLineWrap(true);
jTextArea1.setRows(5);
jTextArea1.setWrapStyleWord(true);
jTextArea1.setBorder(null);
jScrollPane2.setViewportView(jTextArea1);

jLabel17.setText("Notizen");

javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
jPanel10.setLayout(jPanel10Layout);
jPanel10Layout.setHorizontalGroup(
jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel10Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel17)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
.addContainerGap())
);
jPanel10Layout.setVerticalGroup(
jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel10Layout.createSequentialGroup()
.addComponent(jLabel17)
.addGap(22, 22, 22))
.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
);

jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

jTable1.setAutoCreateRowSorter(true);
jTable1.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		{null, null}
	},
	new String [] {
		"Rechnungen", "Datum"
	}
) {
	boolean[] canEdit = new boolean [] {
		false, false
	};

	public boolean isCellEditable(int rowIndex, int columnIndex) {
		return canEdit [columnIndex];
	}
});
jTable1.setFocusable(false);
jTable1.setRequestFocusEnabled(false);
jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jTable1MouseClicked(evt);
}
});
jScrollPane3.setViewportView(jTable1);

jLabel19.setText("Rechnungen:");

javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
jPanel11.setLayout(jPanel11Layout);
jPanel11Layout.setHorizontalGroup(
jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel11Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
.addComponent(jLabel19))
.addContainerGap())
);
jPanel11Layout.setVerticalGroup(
jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel11Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel19)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
.addContainerGap())
);

jPanel14.add(jPanel11);

jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

jTable4.setAutoCreateRowSorter(true);
jTable4.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		{null, null}
	},
	new String [] {
		"Angebot", "Datum"
	}
) {
	boolean[] canEdit = new boolean [] {
		false, false
	};

	public boolean isCellEditable(int rowIndex, int columnIndex) {
		return canEdit [columnIndex];
	}
});
jTable4.setFocusable(false);
jTable4.setRequestFocusEnabled(false);
jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jTable4MouseClicked(evt);
}
});
jScrollPane6.setViewportView(jTable4);

jLabel21.setText("Angebote:");

javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
jPanel12.setLayout(jPanel12Layout);
jPanel12Layout.setHorizontalGroup(
jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel12Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
.addComponent(jLabel21))
.addContainerGap())
);
jPanel12Layout.setVerticalGroup(
jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel12Layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel21)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
.addContainerGap())
);

jPanel14.add(jPanel12);

javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
jPanel6.setLayout(jPanel6Layout);
jPanel6Layout.setHorizontalGroup(
jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
.addContainerGap()
.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(jPanel6Layout.createSequentialGroup()
.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
.addContainerGap())
);
jPanel6Layout.setVerticalGroup(
jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel6Layout.createSequentialGroup()
.addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1)
.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(3, 3, 3)
.addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
);

javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
jPanel2.setLayout(jPanel2Layout);
jPanel2Layout.setHorizontalGroup(
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel2Layout.createSequentialGroup()
.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addGap(2, 2, 2)
.addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
);
jPanel2Layout.setVerticalGroup(
jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel2Layout.createSequentialGroup()
.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(1, 1, 1)
.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
.addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
);

jTabbedPane1.addTab("Allgemein", jPanel2);

jPanel3.setBackground(new java.awt.Color(255, 255, 255));

jScrollPane4.setAutoscrolls(true);

jTable2.setAutoCreateRowSorter(true);
jTable2.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		{null, null, null, null},
		{null, null, null, null},
		{null, null, null, null},
		{null, null, null, null}
	},
	new String [] {
		"Nummer", "Firma", "Name", "Telefon"
	}
));
jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jTable2MouseClicked(evt);
}
public void mouseEntered(java.awt.event.MouseEvent evt) {
jTable2MouseEntered(evt);
}
});
jScrollPane4.setViewportView(jTable2);

jButton11.setText("Zeige alle");
jButton11.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton11ActionPerformed(evt);
}
});

javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
jPanel3.setLayout(jPanel3Layout);
jPanel3Layout.setHorizontalGroup(
jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
.addContainerGap(565, Short.MAX_VALUE)
.addComponent(jButton11)
.addContainerGap())
.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
);
jPanel3Layout.setVerticalGroup(
jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jButton11)
.addContainerGap())
);

jTabbedPane1.addTab("Liste", jPanel3);

jPanel1.setBackground(new java.awt.Color(255, 255, 204));
jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
jToolBar2.setFloatable(false);
jToolBar2.setRollover(true);

jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/3232/edittrash.png"))); // NOI18N
jButton20.setToolTipText("Kunde deaktivieren und Tab schliessen");
jButton20.setFocusable(false);
jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jButton20.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton20ActionPerformed(evt);
}
});
jToolBar2.add(jButton20);

jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/3232/new_window.png"))); // NOI18N
jButton14.setToolTipText("Als neuer Kunde anlegen");
jButton14.setFocusable(false);
jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jButton14MouseClicked(evt);
}
});
jToolBar2.add(jButton14);

jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/3232/filesave.png"))); // NOI18N
jButton13.setToolTipText("Speichern");
jButton13.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/3232/lock.png"))); // NOI18N
jButton13.setFocusable(false);
jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jButton13MouseClicked(evt);
}
});
jToolBar2.add(jButton13);
jToolBar2.add(jSeparator2);

jButton10.setText("Serienbrief");
jButton10.setFocusable(false);
jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jButton10.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton10ActionPerformed(evt);
}
});
jToolBar2.add(jButton10);

jButton8.setText("Neue Rechnung");
jButton8.setFocusable(false);
jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jButton8MouseClicked(evt);
}
});
jToolBar2.add(jButton8);

jButton9.setText("Angebot");
jButton9.setFocusable(false);
jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jButton9MouseClicked(evt);
}
});
jToolBar2.add(jButton9);
jToolBar2.add(jSeparator3);

jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/3232/edit_user.png"))); // NOI18N
jButton18.setToolTipText("VCard Export");
jButton18.setFocusable(false);
jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jButton18MouseClicked(evt);
}
});
jToolBar2.add(jButton18);

javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
);
jPanel1Layout.setVerticalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addContainerGap())
);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
this.setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
);
}// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param c 
     */
    @Override
    public void setContact(People c) {

        if (getLockable() != null) {
            getLockable().unlock();

        }
        setLockable(c);
        jButton13.setEnabled(!c.readonly);

        try {
            this.current = (Kunde) c;
            this.changeTabText("Kunde: " + current.getName());
            this.jTable1.setModel(new CustomerBAListTableModel(current));
            TableFormat.stripFirst(jTable1);
            this.jTable4.setModel(new CustomerBAListTableModel(current, true));
            numberfieldedited = false;
            TableFormat.stripFirst(jTable4);
        } catch (ClassCastException e) {
        }

        People contact = c;
        this.jTextField4.setText(contact.getNummer());
        this.jTextField5.setText(contact.getFirma());
        this.jTextField6.setText(contact.getAnrede());
        this.jTextField7.setText(contact.getName());
        this.jTextField8.setText(contact.getVorname());
        this.jTextField9.setText(contact.getStr());
        this.jTextField10.setText(contact.getOrt());
        this.jTextField11.setText(contact.getTel());
        this.jTextField12.setText(contact.getFax());
        this.jTextField13.setText(contact.getMobil());
        this.jTextField14.setText(contact.getMail());
        this.jTextField15.setText(contact.getWebseite());
        this.jTextField16.setText(contact.getPLZ());
        this.jTextArea1.setText(contact.getNotizen());
    }

    private void jTextField1ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed


        String[][] list = current.select("id, nummer, firma ", "nummer", jTextField1.getText(), "nummer", true);
        String k = "id, " + "Nummer,Firma";

        this.jTable3.setModel(new DefaultTableModel(list, k.split(",")));
        TableFormat.stripFirst(jTable3);

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

        String[][] list = current.select("id, nummer, name ", "name", jTextField2.getText(), "name", true);
        String k = "id, " + "Nummer,Name";

        this.jTable3.setModel(new DefaultTableModel(list, k.split(",")));
        TableFormat.stripFirst(jTable3);

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

        String[][] list = current.select("id, nummer, firma ", "firma", jTextField3.getText(), "firma", true);
        String k = "id, " + "Nummer,Firma";

        this.jTable3.setModel(new DefaultTableModel(list, k.split(",")));
        TableFormat.stripFirst(jTable3);

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
    }//GEN-LAST:event_jTextField15ActionPerformed

    private boolean createNew() {


        if (jTextField7.getText().length() >= 1 || jTextField5.getText().length() >= 1) {
            if (jTextField5.getText().length() == 0) {
                jTextField5.setText(jTextField7.getText());
            }

            if (!numberfieldedited && current.isValid()) {
                jTextField4.setText(null);
            }
            current = new Kunde();

            if (jTextField4.getText() == null || jTextField4.getText().length() == 0) {
                String s = current.getNfh().getNextNumber();
                current.setNummer(s);
            } else {
                if (!current.getNfh().exists(jTextField4.getText())) {
                    current.setNummer(jTextField4.getText());
                } else {
                    Popup.notice("Angegebene Kundennummer existiert bereits.");
                    return false;
                }
            }

            current.setFirma(jTextField5.getText());
            current.setAnrede(jTextField6.getText());
            current.setName(jTextField7.getText());
            current.setVorname(jTextField8.getText());
            current.setStr(jTextField9.getText());
            current.setPLZ(jTextField16.getText());
            current.setOrt(jTextField10.getText());
            current.setTel(jTextField11.getText());
            current.setFax(jTextField12.getText());
            current.setMobil(jTextField13.getText());
            current.setMail(jTextField14.getText());
            current.setWebseite(jTextField15.getText());
            current.setNotizen(jTextArea1.getText());

            try {
                if (current.save()) {
                    setEdited(false);
                    updateListTable();
                    try {
                        this.setContact(current);
                    } catch (Exception exception) {
                        Popup.warn(exception.getMessage(), Popup.ERROR);
                    }
                    try {
                        new HistoryItem(ConnectionHandler.instanceOf(), Strings.Kunde, "Kunde Nummer: " + current.getNummer() + " angelegt.");
                    } catch (Exception ex) {
                        Popup.warn(ex.getMessage(), Popup.ERROR);
                    }
                }
            } catch (Exception ex) {
                Popup.warn(ex.getMessage(), Popup.ERROR);
            }


        } else {
            new Popup("Sie müssen mindestens einen Namen angeben.", Popup.ERROR);
        }
        return true;
    }

    private void jTextField16ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTable2MouseClicked (java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        SelectionCheck selection = new SelectionCheck(jTable2);

        if (evt.getClickCount() >= 2 && selection.checkID() && evt.getButton() == MouseEvent.BUTTON1) {
            try {
                this.setContact(new Kunde(selection.getId()));
                jTabbedPane1.setSelectedIndex(0);
            } catch (Exception exception) {
                exception.printStackTrace();
            }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    public void save() {

        if (current.isValid()) {
            if (jTextField7.getText().length() > 0) {
                try {
                    current.setFirma(jTextField5.getText());
                    current.setAnrede(jTextField6.getText());
                    current.setName(jTextField7.getText());
                    current.setVorname(jTextField8.getText());
                    current.setStr(jTextField9.getText());
                    current.setPLZ(jTextField16.getText());
                    current.setOrt(jTextField10.getText());
                    current.setTel(jTextField11.getText());
                    current.setFax(jTextField12.getText());
                    current.setMobil(jTextField13.getText());
                    current.setMail(jTextField14.getText());
                    current.setWebseite(jTextField15.getText());
                    current.setNotizen(jTextArea1.getText());
                    if (current.save()) {
                        setEdited(false);
                        new HistoryItem(ConnectionHandler.instanceOf(), Strings.Kunde, "Kunde Nummer: " + current.getNummer() + " gespeichert.");
                        updateListTable();
                    }
                } catch (Exception ex) {
                    Log.Debug(this, ex, true);
                    Popup.warn(ex.getMessage(), Popup.ERROR);
                }
            } else {
                new Popup("Sie müssen mindestens einen Namen angeben.", Popup.ERROR);
            }
        } else {
            createNew();
        }
    }

    private void jTable3MouseClicked (java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        SelectionCheck selection = new SelectionCheck(jTable3);
        if (evt.getClickCount() >= 2 && selection.checkID() && evt.getButton() == MouseEvent.BUTTON1) {
            try {
                this.setContact(new Kunde(selection.getId()));
            } catch (Exception exception) {
                Log.Debug(this, exception, true);
            }
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton7ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        clear();
        setEdited(true);

    }//GEN-LAST:event_jButton7ActionPerformed
    private void clear() {
        this.jTextField4.setText("");
        this.jTextField5.setText("");
        this.jTextField6.setText("");
        this.jTextField7.setText("");
        this.jTextField8.setText("");
        this.jTextField9.setText("");
        this.jTextField10.setText("");
        this.jTextField11.setText("");
        this.jTextField12.setText("");
        this.jTextField13.setText("");
        this.jTextField14.setText("");
        this.jTextField15.setText("");
        this.jTextField16.setText("");
        this.jTextArea1.setText("");
        setEdited(true);

    }
    private void jButton8MouseClicked (java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked

        if (mainframe.getUser().doAction(User.EDITOR)) {
            save();
            if (current.isValid()) {
                Rechnung r = new Rechnung();
                r.setKundenId(current.getId());
                mainframe.addBillPanel(r);
            }
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jTable1MouseClicked (java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        SelectionCheck selection = new SelectionCheck(jTable1);
        if (evt.getClickCount() >= 2 && selection.checkID()) {
            try {
                mainframe.addBillPanel(new Rechnung(selection.getId()));
            } catch (Exception ex) {
                Log.Debug(this, ex);
                Popup.warn(ex.getMessage(), Popup.ERROR);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
    }//GEN-LAST:event_jTable2MouseEntered

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        save();
        if (current.isValid()) {
            serialLetter.instanceOf().addContact(current);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    liste = current.getAll(true);
    String k = "id, " + TABLE_Kunde_FIELDS;
    this.jTable2.setModel(new DefaultTableModel(liste, k.split(",")));
    TableFormat.stripFirst(jTable2);
}//GEN-LAST:event_jButton11ActionPerformed

private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked

    if (mainframe.getUser().doAction(User.EDITOR)) {
        save();
    }

}//GEN-LAST:event_jButton13MouseClicked

private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
    if (mainframe.getUser().doAction(User.EDITOR)) {
        createNew();
    }
}//GEN-LAST:event_jButton14MouseClicked

private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
   save();
 if (current.isValid()) {//GEN-LAST:event_jButton18MouseClicked
            DialogForFile dialog = new DialogForFile(DialogForFile.FILES_ONLY, current.getName() + ".vcf");
            if (dialog.chooseFile()) {
                new FileReaderWriter(dialog.getFile()).write(new VCard(current).getVCard());
            }
        } 
    }

private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
     if (mainframe.getUser().doAction(User.EDITOR)) {
        if (Popup.Y_N_dialog("Diesen Kontakt wirklich deaktivieren?") && mainframe.getUser().doAction(User.EDITOR)) {
            deactivate();
//        this.close();
        }
    }
}//GEN-LAST:event_jButton20ActionPerformed

private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked

    SelectionCheck selection = new SelectionCheck(jTable4);
    if (evt.getClickCount() >= 2 && selection.checkID()) {
        try {
            mainframe.addAngebotPanel(new Angebot(selection.getId()));
        } catch (Exception ex) {
            Log.Debug(this, ex);
            Popup.warn(ex.getMessage(), Popup.ERROR);
        }
    }

}//GEN-LAST:event_jTable4MouseClicked

private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
    jTextField17.setEnabled(true);
}//GEN-LAST:event_jTextField17ActionPerformed

private void editListener(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editListener
    setEdited(true);
}//GEN-LAST:event_editListener

private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
    setEdited(true);
    jTextField5.setEnabled(true);
}//GEN-LAST:event_jTextField5MouseClicked

private void jTextField17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField17MouseClicked
    setEdited(true);
    jTextField17.setEnabled(true);
}//GEN-LAST:event_jTextField17MouseClicked

private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
    new NumberFormatEditor(this.current);
}//GEN-LAST:event_jButton16ActionPerformed

private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
    numberfieldedited = true;
}//GEN-LAST:event_jTextField4KeyTyped

private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
    jTextField4.setEditable(true);
}//GEN-LAST:event_jTextField4MouseClicked

private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked

    if (mainframe.getUser().doAction(User.EDITOR)) {
        save();
        if (current.isValid()) {
            Angebot r = new Angebot();
            r.setKundenId(current.getId());
            mainframe.addAngebotPanel(r);
        }
    }
}//GEN-LAST:event_jButton9MouseClicked

    private void deactivate() {
        if (current.getId() > 0) {
            if ((JOptionPane.showConfirmDialog(this, "Wirklich löschen?", "Sicher?", JOptionPane.YES_NO_OPTION)) == JOptionPane.YES_OPTION) {
                try {
                    current.deactivate(current.getId().toString());

                    new HistoryItem(ConnectionHandler.instanceOf(), Strings.Kunde, "Kunde Nummer: " + current.getNummer() + " gelöscht.");

                    this.liste = current.getAll(false);
                    String k = "id," + TABLE_Kunde_FIELDS;

                    this.jTable2.setModel(new DefaultTableModel(liste, k.split(",")));
                    TableFormat.stripFirst(jTable2);

                    current = new Kunde(ConnectionHandler.instanceOf());
                } catch (Exception ex) {
                    Popup.warn(ex.getMessage(), Popup.ERROR);
                }
            }
        } else {
            mainframe.setMessage("Kein Kontakt gewählt.");
        }
    }
// Variables declaration - do not modify//GEN-BEGIN:variables
public javax.swing.JButton jButton10;
public javax.swing.JButton jButton11;
public javax.swing.JButton jButton13;
public javax.swing.JButton jButton14;
public javax.swing.JButton jButton16;
public javax.swing.JButton jButton18;
public javax.swing.JButton jButton20;
public javax.swing.JButton jButton7;
public javax.swing.JButton jButton8;
public javax.swing.JButton jButton9;
public javax.swing.JLabel jLabel1;
public javax.swing.JLabel jLabel10;
public javax.swing.JLabel jLabel11;
public javax.swing.JLabel jLabel12;
public javax.swing.JLabel jLabel13;
public javax.swing.JLabel jLabel14;
public javax.swing.JLabel jLabel15;
public javax.swing.JLabel jLabel16;
public javax.swing.JLabel jLabel17;
public javax.swing.JLabel jLabel18;
public javax.swing.JLabel jLabel19;
public javax.swing.JLabel jLabel2;
public javax.swing.JLabel jLabel20;
public javax.swing.JLabel jLabel21;
public javax.swing.JLabel jLabel3;
public javax.swing.JLabel jLabel4;
public javax.swing.JLabel jLabel5;
public javax.swing.JLabel jLabel6;
public javax.swing.JLabel jLabel7;
public javax.swing.JLabel jLabel8;
public javax.swing.JLabel jLabel9;
public javax.swing.JPanel jPanel1;
public javax.swing.JPanel jPanel10;
public javax.swing.JPanel jPanel11;
public javax.swing.JPanel jPanel12;
public javax.swing.JPanel jPanel14;
public javax.swing.JPanel jPanel2;
public javax.swing.JPanel jPanel3;
public javax.swing.JPanel jPanel4;
public javax.swing.JPanel jPanel5;
public javax.swing.JPanel jPanel6;
public javax.swing.JPanel jPanel7;
public javax.swing.JPanel jPanel8;
public javax.swing.JPanel jPanel9;
public javax.swing.JScrollPane jScrollPane2;
public javax.swing.JScrollPane jScrollPane3;
public javax.swing.JScrollPane jScrollPane4;
public javax.swing.JScrollPane jScrollPane5;
public javax.swing.JScrollPane jScrollPane6;
public javax.swing.JToolBar.Separator jSeparator2;
public javax.swing.JToolBar.Separator jSeparator3;
public javax.swing.JTabbedPane jTabbedPane1;
public javax.swing.JTable jTable1;
public javax.swing.JTable jTable2;
public javax.swing.JTable jTable3;
public javax.swing.JTable jTable4;
public javax.swing.JTextArea jTextArea1;
public javax.swing.JTextField jTextField1;
public javax.swing.JTextField jTextField10;
public javax.swing.JTextField jTextField11;
public javax.swing.JTextField jTextField12;
public javax.swing.JTextField jTextField13;
public javax.swing.JTextField jTextField14;
public javax.swing.JTextField jTextField15;
public javax.swing.JTextField jTextField16;
public javax.swing.JTextField jTextField17;
public javax.swing.JTextField jTextField2;
public javax.swing.JTextField jTextField3;
public javax.swing.JTextField jTextField4;
public javax.swing.JTextField jTextField5;
public javax.swing.JTextField jTextField6;
public javax.swing.JTextField jTextField7;
public javax.swing.JTextField jTextField8;
public javax.swing.JTextField jTextField9;
public javax.swing.JToolBar jToolBar2;
// End of variables declaration//GEN-END:variables
    public void update() {
        this.updateListTable();
    }

    private void updateListTable() {
        this.jTable2.setModel(new ContactListTableModel(current));
        TableFormat.stripFirst(jTable2);
    }

    public People getContact() {
        return current;
    }

    public void switchTab(int i) {
        jTabbedPane1.setSelectedIndex(i);
    }
}

