/*
 * LinienDiagramm.java
 *
 * Created on 20. August 2008, 20:55
 */
package mp4.statistik.graphs;


import java.util.Currency;
import mp4.statistik.*;
import java.util.Vector;
//import mp4.logs.*;*
import mp4.einstellungen.Einstellungen;
import mp4.logs.*;
import mp4.statistik.data.DefaultDataMonths;
import mp4.utils.zahlen.FormatNumber;

/**
 *
 * @author  Andreas
 */
public class LinienDiagramm extends javax.swing.JFrame {
    private Diagramme d;

    /** Creates new form LinienDiagramm
     * @param von
     * @param bis
     * @param title 
     */
    public LinienDiagramm(String von, String bis, String title) {
        initComponents();
        addDiagram(von, bis, title);
        setVisible(rootPaneCheckingEnabled);
    }

    @SuppressWarnings({"unchecked", "unchecked","unchecked"})
    private void addDiagram(String von, String bis, String title) {

        DefaultDataMonths data;

        d = new Diagramme(jPanel1);
        try {
            data = new DefaultDataMonths(von, bis);        
            d.erzeugeLinienGrafik("", new Vector(data.getColumns()), 
                    new Vector(data.getUmsatz()), Currency.getInstance(Einstellungen.instanceOf().getLocale()).getSymbol(), title + " " + von + " - " + bis, "Zeitraum", Currency.getInstance(Einstellungen.instanceOf().getLocale()).getSymbol(), "", FormatNumber.getDefaultDecimalFormat());
        } catch (Exception ex) {
            Log.Debug(ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {

jToolBar1 = new javax.swing.JToolBar();
jButton1 = new javax.swing.JButton();
jButton2 = new javax.swing.JButton();
jPanel1 = new javax.swing.JPanel();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("MP Diagramm");

jToolBar1.setFloatable(false);
jToolBar1.setRollover(true);

jButton1.setText("Drucken");
jButton1.setFocusable(false);
jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jToolBar1.add(jButton1);

jButton2.setText("Speichern");
jButton2.setFocusable(false);
jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
jButton2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton2ActionPerformed(evt);
}
});
jToolBar1.add(jButton2);

jPanel1.setBackground(new java.awt.Color(51, 0, 51));
jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
jPanel1.setLayout(new java.awt.BorderLayout());

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
);

pack();
}// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    d.writeToFile("test.png");
}//GEN-LAST:event_jButton2ActionPerformed

  

// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton jButton1;
private javax.swing.JButton jButton2;
private javax.swing.JPanel jPanel1;
private javax.swing.JToolBar jToolBar1;
// End of variables declaration//GEN-END:variables

}
