/*
 * Logger.java
 *
 * Created on 18. Februar 2008, 22:14
 */
package mp4.frames;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import javax.swing.text.BadLocationException;

/**
 *
 * @author  anti43
 */
public class Logger extends javax.swing.JFrame {

    private static File logfile = null;
    private static boolean FILE_LOG_ENABLED = false;
    private static FileWriter logwriter;

    public static void setLogFile(String string) throws Exception {
        Logger.logfile = new File(string);

        if (!logfile.canWrite()) {
            throw new Exception("Fehler in " + logfile.getCanonicalPath());
        } else {
            FILE_LOG_ENABLED = true;
            logwriter = new FileWriter(logfile);
        }
    }

    /** Creates new form Logger */
    public Logger() {
        initComponents();
        this.setExtendedState(ICONIFIED);

    }

    public void log() throws IOException {
        if (FILE_LOG_ENABLED) {
            logwriter.write("\n");
        } else {
            jTextArea1.append("\n");
        }
    }

    public void log(Object object) throws IOException {
        if (FILE_LOG_ENABLED)logwriter.write(object.toString()); 
        else {
            if (object != null) {
                jTextArea1.append("\n" + object.toString());
            } else {
                jTextArea1.append("\nNULL");
            }
        }
    }

    public void log(String string) throws IOException {
        if (FILE_LOG_ENABLED)logwriter.write(string); else {
            jTextArea1.append("\n" + string);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MP Logger");

        jLabel1.setText("MP Logger:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Flush");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jTextArea1.setText(null);
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Logger().setVisible(true);
            }
        });
    }

    public void log(Exception e) {

        jTextArea1.append(e.getMessage());
    }
    
         
    public void flush() {
       System.out.print(jTextArea1.getText());
       jTextArea1.setText(null);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    // End of variables declaration
    static class DocumentWriter
            extends Writer {

        final javax.swing.text.Document doc;

        public DocumentWriter(javax.swing.JTextArea jta) {
            this(jta.getDocument());
        }

        public DocumentWriter(javax.swing.text.Document doc) {
            this.doc = doc;
        }

        public void close() {
        }

        public void flush() {
        }

        public void write(char[] cbuf, int off, int len) {
            try {
                doc.insertString(doc.getLength(), String.valueOf(cbuf, off, len), null);
            } catch (BadLocationException ex) {
            }
        }
    }
    
  
}
