/*
 * PdfVorschauWindow.java
 *
 * Created on July 30, 2008, 2:23 PM
 */
package mp4.frames;

import com.sun.pdfview.PDFFile;
import com.sun.pdfview.PDFPage;
import com.sun.pdfview.PagePanel;
import java.awt.BorderLayout;
import java.io.*;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import mp4.interfaces.Waiter;
import mp4.logs.*;
import mp4.utils.export.druck.DruckJob;
import mp4.utils.files.DialogForFile;
import mp4.utils.files.FileDirectoryHandler;
import mp4.utils.ui.Position;

/**
 *
 * @author  anti43
 */
public class PdfVorschauWindow extends javax.swing.JFrame implements Waiter {

    private File file;
    private RandomAccessFile raf;
    private PDFFile pdffile;
    private PDFPage page;
    private File filename;

    /** Creates new form PdfVorschauWindow
     * @param pdfFile
     */
    public PdfVorschauWindow(File pdfFile) {

        this.file = pdfFile;

        try { 
            openPDF();
        } catch (Exception ex) {
            Log.Debug(this,ex);
        }
    }

    public PdfVorschauWindow() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PDF Vorschau");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Drucken");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Schlieﬂen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Speichern");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            page = null;
            pdffile = null;
            raf.close();
        } catch (IOException ex) {
            Logger.getLogger(PdfVorschauWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    DruckJob djob = new DruckJob(DocFlavor.INPUT_STREAM.PDF);

    djob.set(FileDirectoryHandler.tempFileClone(file, "pdf"));


}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    new DialogForFile(DialogForFile.FILES_ONLY, ((mp4.utils.files.PDFFile)file).getTargetFile()).writeFile(((mp4.utils.files.PDFFile)file));
}//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void set(Object object) {

        file = ((mp4.utils.files.PDFFile) object);

        try {
         openPDF();

        } catch (Exception ex) {
            Log.Debug(this,ex);
        }
    }

    private void openPDF() throws Exception {
          initComponents();
            PagePanel panel = new PagePanel();
            this.jPanel1.add(panel, BorderLayout.CENTER);

            raf = new RandomAccessFile(file, "r");

            FileChannel channel = raf.getChannel();
           
            ByteBuffer buf = 
                    channel.map(FileChannel.MapMode.READ_ONLY,
                    0, channel.size());
//            
            pdffile = new PDFFile(buf);
            
            
            buf.clear();
            channel.close();
            raf.close();

            this.pack();
            new Position(this);
            setVisible(true);

            // show the first page
            page = pdffile.getPage(0);
            panel.showPage(page);
            panel.useZoomTool(true);
    }
}
