CREATE TABLE ACCOUNTS  (
	IDS             	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	INTACCOUNTCLASS 	SMALLINT DEFAULT 0,
	CNAME           	VARCHAR(250) NOT NULL,
	DESCRIPTION     	VARCHAR(250) NOT NULL,
	TAXVALUE        	DOUBLE NOT NULL DEFAULT 0,
	DATEADDED       	DATE NOT NULL,
	INTADDEDBY      	BIGINT(20) DEFAULT 0,
	INTPARENTACCOUNT	BIGINT(20) DEFAULT 0,
	GROUPSIDS       	BIGINT(20) UNSIGNED NOT NULL  DEFAULT 1,
	INVISIBLE       	SMALLINT DEFAULT 0,
	INTACCOUNTTYPE  	SMALLINT NOT NULL,
	INTPROFITFID    	SMALLINT NOT NULL,
	INTTAXFID       	SMALLINT NOT NULL,
	INTTAXUID       	SMALLINT NOT NULL,
	FRAME           	VARCHAR(25) NOT NULL,
	HIERARCHYPATH   	VARCHAR(250) DEFAULT NULL
);

CREATE TABLE ADDRESSES  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	CONTACTSIDS	BIGINT(20) UNSIGNED NOT NULL ,
	TITLE      	VARCHAR(250) DEFAULT NULL,
	TAXNUMBER  	VARCHAR(250) DEFAULT NULL,
	PRENAME    	VARCHAR(250) DEFAULT NULL,
	CNAME      	VARCHAR(250) DEFAULT NULL,
	STREET     	VARCHAR(250) DEFAULT NULL,
	ZIP        	VARCHAR(50) DEFAULT NULL,
	CITY       	VARCHAR(300) DEFAULT NULL,
	COMPANY    	VARCHAR(250) DEFAULT NULL,
	DEPARTMENT 	VARCHAR(250) DEFAULT NULL,
	COUNTRY    	VARCHAR(50) DEFAULT NULL,
	ISMALE     	SMALLINT DEFAULT 0,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE DEFAULT NULL,
	INTTYPE    	SMALLINT DEFAULT 0,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE COMPS  (
	IDS          	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	GROUPSIDS    	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	CNAME        	VARCHAR(250) DEFAULT NULL,
	STATE        	VARCHAR(250) DEFAULT NULL,
	PHONEPREFIX  	VARCHAR(250) DEFAULT NULL,
	BUSINESS     	VARCHAR(250) DEFAULT NULL,
	TAXADVISOR   	VARCHAR(250) DEFAULT NULL,
	CITY         	VARCHAR(250) DEFAULT NULL,
	TAXADVJOB    	VARCHAR(250) DEFAULT NULL,
	STREET       	VARCHAR(250) DEFAULT NULL,
	STB          	VARCHAR(250) DEFAULT NULL,
	EMAIL        	VARCHAR(250) DEFAULT NULL,
	NAME         	VARCHAR(250) DEFAULT NULL,
	ZIPCODE      	VARCHAR(250) DEFAULT NULL,
	PHONE        	VARCHAR(250) DEFAULT NULL,
	FIRSTNAME    	VARCHAR(250) DEFAULT NULL,
	TAXAUTHORITY 	VARCHAR(250) DEFAULT NULL,
	TAXNUMBER    	VARCHAR(250) DEFAULT NULL,
	TAXADVMANDANT	VARCHAR(250) DEFAULT NULL,
	DATEADDED    	DATE NOT NULL,
	ISMALE       	SMALLINT DEFAULT 0,
	ISENABLED    	SMALLINT DEFAULT 1,
	INTADDEDBY   	BIGINT(20) DEFAULT 0,
	INVISIBLE    	SMALLINT DEFAULT 0,
	RESERVE1     	VARCHAR(500) DEFAULT NULL,
	RESERVE2     	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE CONTACTS  (
	IDS           	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNUMBER       	VARCHAR(250) DEFAULT NULL,
	TAXNUMBER     	VARCHAR(250),
	TITLE         	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS     	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	COUNTRY       	VARCHAR(50) DEFAULT NULL,
	PRENAME       	VARCHAR(250) DEFAULT NULL,
	CNAME         	VARCHAR(250) DEFAULT NULL,
	STREET        	VARCHAR(250) DEFAULT NULL,
	ZIP           	VARCHAR(50) DEFAULT NULL,
	CITY          	VARCHAR(300) DEFAULT NULL,
	MAINPHONE     	VARCHAR(250) DEFAULT NULL,
	FAX           	VARCHAR(250) DEFAULT NULL,
	MOBILEPHONE   	VARCHAR(250) DEFAULT NULL,
	WORKPHONE     	VARCHAR(250) DEFAULT NULL,
	MAILADDRESS   	VARCHAR(350) DEFAULT NULL,
	COMPANY       	VARCHAR(250) DEFAULT NULL,
	DEPARTMENT    	VARCHAR(250) DEFAULT NULL,
	WEBSITE       	VARCHAR(350) DEFAULT NULL,
	NOTES         	VARCHAR(10000),
	DATEADDED     	DATE NOT NULL,
	ISACTIVE      	SMALLINT DEFAULT 0,
	ISCUSTOMER    	SMALLINT DEFAULT 0,
	ISMANUFACTURER	SMALLINT DEFAULT 0,
	ISSUPPLIER    	SMALLINT DEFAULT 0,
	ISCOMPANY     	SMALLINT DEFAULT 0,
	ISMALE        	SMALLINT DEFAULT 0,
	ISENABLED     	SMALLINT DEFAULT 1,
	INTADDEDBY    	BIGINT(20) DEFAULT 0,
	INVISIBLE     	SMALLINT DEFAULT 0,
	RESERVE1      	VARCHAR(500) DEFAULT NULL,
	RESERVE2      	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE COUNTRIES  (
	IDS      	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME    	VARCHAR(250) NOT NULL,
	ISO      	SMALLINT NOT NULL,
	GROUPSIDS	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	RESERVE1 	VARCHAR(500) DEFAULT NULL,
	RESERVE2 	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE EXPENSES  (
	IDS            	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	GROUPSIDS      	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	CNUMBER        	VARCHAR(250) DEFAULT NULL,
	CNAME          	VARCHAR(250) DEFAULT NULL,
	ACCOUNTSIDS    	BIGINT(20) UNSIGNED NOT NULL ,
	NETVALUE       	DOUBLE DEFAULT 0,
	TAXPERCENTVALUE	DOUBLE DEFAULT 0,
	BRUTVALUE      	DOUBLE DEFAULT 0,
	DESCRIPTION    	VARCHAR(5000) DEFAULT NULL,
	DATEADDED      	DATE NOT NULL,
	INTADDEDBY     	BIGINT(20) DEFAULT 0,
	INVISIBLE      	SMALLINT DEFAULT 0,
	RESERVE1       	VARCHAR(500) DEFAULT NULL,
	RESERVE2       	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE FAVOURITES  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250) NOT NULL,
	USERSIDS  	BIGINT(20) UNSIGNED NOT NULL ,
	GROUPSIDS 	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	ITEMSIDS  	BIGINT(20) UNSIGNED NOT NULL NOT NULL,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	INVISIBLE 	SMALLINT DEFAULT 0,
	RESERVE1  	VARCHAR(500) DEFAULT NULL,
	RESERVE2  	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE FILES  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(25) NOT NULL,
	GROUPSIDS 	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	DATEADDED 	DATE NOT NULL,
	DATA      	BLOB(5242880) NOT NULL,
	FILESIZE  	BIGINT(20) NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	INVISIBLE 	SMALLINT DEFAULT 0
);

CREATE TABLE FILESTOCONTACTS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	CONTACTSIDS	BIGINT(20) UNSIGNED NOT NULL NOT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTSIZE    	BIGINT(20) DEFAULT 0,
	MIMETYPE   	VARCHAR(25) DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1
);

CREATE TABLE FILESTOITEMS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	ITEMSIDS   	BIGINT(20) UNSIGNED NOT NULL NOT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTSIZE    	BIGINT(20) DEFAULT 0,
	MIMETYPE   	VARCHAR(25) DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1
);

CREATE TABLE FILESTOPRODUCTS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	PRODUCTSIDS	BIGINT(20) UNSIGNED NOT NULL NOT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTSIZE    	BIGINT(20) DEFAULT 0,
	MIMETYPE   	VARCHAR(25) DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20)  UNSIGNED NOT NULL DEFAULT 1
);

CREATE TABLE FORMATSTOUSERS  (
	IDS     	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME   	VARCHAR(250) NOT NULL,
	USERSIDS	BIGINT(20) UNSIGNED NOT NULL ,
	INTTYPE 	SMALLINT DEFAULT 0
);

CREATE TABLE GLOBALSETTINGS  (
	IDS      	BIGINT(20) DEFAULT 1,
	CNAME    	VARCHAR(250) NOT NULL,
	GROUPSIDS	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	VALUE    	VARCHAR(250) NOT NULL
	);

CREATE TABLE GROUPS  (
	IDS          	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME        	VARCHAR(250) NOT NULL,
	DESCRIPTION  	VARCHAR(750) DEFAULT NULL,
	DEFAULTS     	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS    	BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	DATEADDED    	DATE NOT NULL,
	RESERVE1     	VARCHAR(500) DEFAULT NULL,
	INTADDEDBY   	BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	HIERARCHYPATH	VARCHAR(500) DEFAULT NULL,
	RESERVE2     	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE HISTORY  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250) NOT NULL,
	USERNAME  	VARCHAR(250) NOT NULL,
	DBIDENTITY	VARCHAR(25) NOT NULL,
	INTITEM   	SMALLINT NOT NULL,
	GROUPSIDS 	BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	RESERVE1  	VARCHAR(500) DEFAULT NULL,
	RESERVE2  	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE ITEMS  (
	IDS          	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME        	VARCHAR(250) NOT NULL,
	CNUMBER      	VARCHAR(250) NOT NULL,
	DESCRIPTION  	VARCHAR(2500) DEFAULT NULL,
	GROUPSIDS    	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	ACCOUNTSIDS  	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	CONTACTSIDS  	BIGINT(20) UNSIGNED NOT NULL ,
	NETVALUE     	DOUBLE DEFAULT 0,
	TAXVALUE     	DOUBLE DEFAULT 0,
	DISCOUNTVALUE	DOUBLE DEFAULT 0,
	SHIPPINGVALUE	DOUBLE DEFAULT 0,
	DATETODO     	DATE DEFAULT NULL,
	DATEEND      	DATE DEFAULT NULL,
	INTREMINDERS 	INTEGER DEFAULT 0,
	INTTYPE      	SMALLINT DEFAULT 0,
	DATEADDED    	DATE NOT NULL,
	INTADDEDBY   	BIGINT(20) DEFAULT 0,
	INVISIBLE    	SMALLINT DEFAULT 0,
	INTSTATUS    	SMALLINT DEFAULT 0,
	HIERARCHYPATH	VARCHAR(500) DEFAULT NULL,
	RESERVE1     	VARCHAR(500) DEFAULT NULL,
	RESERVE2     	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE ITEMSTOACCOUNTS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	ITEMSIDS   	BIGINT(20) UNSIGNED NOT NULL NOT NULL,
	ACCOUNTSIDS	BIGINT(20) UNSIGNED NOT NULL ,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE LANGUAGES  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250) NOT NULL,
	GROUPSIDS 	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	LONGNAME  	VARCHAR(250) NOT NULL,
	FILENAME  	VARCHAR(25) NOT NULL,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	INVISIBLE 	SMALLINT DEFAULT 0,
	RESERVE1  	VARCHAR(500) DEFAULT NULL,
	RESERVE2  	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE MAILS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(1000) NOT NULL,
	DATEADDED  	DATE NOT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	INVISIBLE  	SMALLINT DEFAULT 0,
	USERSIDS   	BIGINT(20) UNSIGNED NOT NULL ,
	DESCRIPTION	VARCHAR(5000) NOT NULL
);

CREATE TABLE PLUGINS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1
);

CREATE TABLE PLUGINSTOUSERS  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250) NOT NULL,
	USERSIDS  	BIGINT(20) UNSIGNED NOT NULL NOT NULL,
	PLUGINSIDS	BIGINT(20) UNSIGNED NOT NULL NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	DATEADDED 	DATE NOT NULL,
	GROUPSIDS 	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1
);

CREATE TABLE PRODUCTGROUPS  (
	IDS             	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME           	VARCHAR(250) NOT NULL,
	DESCRIPTION     	VARCHAR(750) DEFAULT NULL,
	DEFAULTS        	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS       	BIGINT(20) UNSIGNED NOT NULL  DEFAULT 0,
	PRODUCTGROUPSIDS	BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	DATEADDED       	DATE NOT NULL,
	HIERARCHYPATH   	VARCHAR(500) DEFAULT NULL,
	RESERVE1        	VARCHAR(500) DEFAULT NULL,
	INTADDEDBY      	BIGINT(20) DEFAULT 0,
	RESERVE2        	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE PRODUCTLISTITEMS  (
	IDS                	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME              	VARCHAR(2500) DEFAULT NULL,
	LINKURL            	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS          	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	PRODUCTLISTSIDS    	BIGINT(20) UNSIGNED NOT NULL ,
	ORIGINALPRODUCTSIDS	BIGINT(20) UNSIGNED NOT NULL ,
	COUNTVALUE         	DOUBLE NOT NULL DEFAULT 0,
	QUANTITYVALUE      	DOUBLE NOT NULL DEFAULT 0,
	MEASURE            	VARCHAR(250) NOT NULL,
	DESCRIPTION        	VARCHAR(1000) DEFAULT NULL,
	INTERNALVALUE      	DOUBLE DEFAULT 0,
	TOTALNETVALUE      	DOUBLE DEFAULT 0,
	TOTALBRUTVALUE     	DOUBLE DEFAULT 0,
	EXTERNALVALUE      	DOUBLE DEFAULT 0,
	TAXPERCENTVALUE    	DOUBLE NOT NULL DEFAULT 0,
	DATEADDED          	DATE NOT NULL,
	INTADDEDBY         	BIGINT(20) DEFAULT 0,
	INVISIBLE          	SMALLINT DEFAULT 0,
	RESERVE1           	VARCHAR(500) DEFAULT NULL,
	RESERVE2           	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE PRODUCTLISTS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(2500) DEFAULT NULL,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL  DEFAULT 1,
	DESCRIPTION	VARCHAR(1000) DEFAULT NULL,
	DATEADDED  	DATE NOT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	INVISIBLE  	SMALLINT DEFAULT 0,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE PRODUCTS  (
	IDS             	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME           	VARCHAR(500) NOT NULL,
	CNUMBER         	VARCHAR(250) NOT NULL,
	DESCRIPTION     	VARCHAR(5000),
	EXTERNALNETVALUE	DOUBLE DEFAULT 0,
	INTERNALNETVALUE	DOUBLE DEFAULT 0,
	MEASURE         	VARCHAR(250) NOT NULL,
	TAXIDS          	BIGINT(20) UNSIGNED NOT NULL ,
	MANUFACTURERSIDS	BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	SUPPLIERSIDS    	BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	GROUPSIDS       	BIGINT(20) UNSIGNED NOT NULL  DEFAULT 1,
	PRODUCTGROUPSIDS	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	URL             	VARCHAR(250) DEFAULT NULL,
	EAN             	VARCHAR(25) DEFAULT NULL,
	REFERENCE       	VARCHAR(50) DEFAULT NULL,
	DATEADDED       	DATE NOT NULL,
	INTADDEDBY      	BIGINT(20) DEFAULT 0,
	INVISIBLE       	SMALLINT DEFAULT 0,
	INTTYPE         	SMALLINT NOT NULL,
	DEFAULTIMAGE    	VARCHAR(30) DEFAULT NULL,
	RESERVE1        	VARCHAR(500) DEFAULT NULL,
	RESERVE2        	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE REMINDERS  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	STAGESIDS  	BIGINT(20) UNSIGNED NOT NULL,
	ITEMSIDS   	BIGINT(20) UNSIGNED NOT NULL,
	EXTRAVALUE 	DOUBLE DEFAULT 0,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1
);

CREATE TABLE REVENUES  (
	IDS            	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	GROUPSIDS      	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	CNUMBER        	VARCHAR(250) DEFAULT NULL,
	CNAME          	VARCHAR(250) DEFAULT NULL,
	ACCOUNTSIDS    	BIGINT(20) UNSIGNED NOT NULL,
	NETVALUE       	DOUBLE DEFAULT 0,
	TAXPERCENTVALUE	DOUBLE DEFAULT 0,
	BRUTVALUE      	DOUBLE DEFAULT 0,
	DESCRIPTION    	VARCHAR(5000) DEFAULT NULL,
	DATEADDED      	DATE NOT NULL,
	INTADDEDBY     	BIGINT(20) DEFAULT 0,
	INVISIBLE      	SMALLINT DEFAULT 0,
	RESERVE1       	VARCHAR(500) DEFAULT NULL,
	RESERVE2       	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE SCHEDULE  (
	IDS          	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME        	VARCHAR(250) NOT NULL,
	GROUPSIDS    	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	USERSIDS     	BIGINT(20) UNSIGNED NOT NULL ,
	ITEMSIDS     	BIGINT(20) UNSIGNED NOT NULL ,
	STOPDATE     	DATE NOT NULL,
	STARTDATE    	DATE NOT NULL,
	NEXTDATE     	DATE NOT NULL,
	ISDONE       	SMALLINT DEFAULT 0,
	INTERVALMONTH	SMALLINT NOT NULL,
	DATEADDED    	DATE NOT NULL,
	INTADDEDBY   	BIGINT(20) DEFAULT 0,
	INVISIBLE    	SMALLINT DEFAULT 0,
	RESERVE1     	VARCHAR(500) DEFAULT NULL,
	RESERVE2     	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE SEARCHINDEX  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	DBIDENTITY	VARCHAR(25) NOT NULL,
	GROUPSIDS 	BIGINT(20) UNSIGNED NOT NULL ,
	ROWID     	BIGINT(20) NOT NULL,
	TEXT      	VARCHAR(5000) DEFAULT NULL
	);

CREATE TABLE STAGES  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	EXTRAVALUE 	DOUBLE DEFAULT 0,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1
);

CREATE TABLE SUBITEMS  (
	IDS                	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME              	VARCHAR(5000) DEFAULT NULL,
	ITEMSIDS           	BIGINT(20) UNSIGNED NOT NULL ,
	GROUPSIDS          	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	ORIGINALPRODUCTSIDS	BIGINT(20) UNSIGNED DEFAULT NULL,
	COUNTVALUE         	DOUBLE NOT NULL DEFAULT 0,
	QUANTITYVALUE      	DOUBLE NOT NULL DEFAULT 0,
	MEASURE            	VARCHAR(250) NOT NULL,
	LINKURL            	VARCHAR(1000) DEFAULT NULL,
	DESCRIPTION        	VARCHAR(1000) DEFAULT NULL,
	INTERNALVALUE      	DOUBLE DEFAULT 0,
	TOTALNETVALUE      	DOUBLE DEFAULT 0,
	TOTALBRUTVALUE     	DOUBLE DEFAULT 0,
	EXTERNALVALUE      	DOUBLE DEFAULT 0,
	TAXPERCENTVALUE    	DOUBLE NOT NULL DEFAULT 0,
	DATEDELIVERY       	DATE DEFAULT NULL,
	DATEADDED          	DATE NOT NULL,
	INTADDEDBY         	BIGINT(20) DEFAULT 0,
	INVISIBLE          	SMALLINT DEFAULT 0,
	RESERVE1           	VARCHAR(500) DEFAULT NULL,
	RESERVE2           	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE TABLELOCK  (
	IDS     	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME   	VARCHAR(250),
	ROWID   	BIGINT(20) NOT NULL,
	USERSIDS	BIGINT(20) UNSIGNED NOT NULL ,
	RESERVE1	VARCHAR(500) DEFAULT NULL,
	RESERVE2	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE TAX  (
	IDS       	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME     	VARCHAR(250),
	TAXVALUE  	DOUBLE DEFAULT 0,
	IDENTIFIER	VARCHAR(250) DEFAULT NULL,
	GROUPSIDS 	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	COUNTRY   	VARCHAR(50) DEFAULT NULL,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	INVISIBLE 	SMALLINT DEFAULT 0,
	RESERVE1  	VARCHAR(500) DEFAULT NULL,
	RESERVE2  	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE TEMPLATES  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(250) NOT NULL,
	FORMAT     	VARCHAR(55) DEFAULT NULL,
	DESCRIPTION	VARCHAR(550) DEFAULT NULL,
	INTSIZE    	BIGINT(20) DEFAULT 0,
	MIMETYPE   	VARCHAR(25) DEFAULT NULL,
	FILENAME   	VARCHAR(25) NOT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	DATEADDED  	DATE NOT NULL,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1
);

CREATE TABLE TEMPLATESTOUSERS  (
	IDS         	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME       	VARCHAR(250) NOT NULL,
	USERSIDS    	BIGINT(20) UNSIGNED NOT NULL ,
	TEMPLATESIDS	BIGINT(20) UNSIGNED NOT NULL NOT NULL,
	GROUPSIDS   	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1
);

CREATE TABLE TRASHBIN  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME      	VARCHAR(500),
	ROWID      	BIGINT(20) NOT NULL,
	DESCRIPTION	VARCHAR(2500),
	DELETEME   	SMALLINT DEFAULT 1,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE USERPROPERTIES  (
	IDS       	BIGINT(20) DEFAULT 1,
	CNAME     	VARCHAR(250) NOT NULL,
	VALUE     	VARCHAR(250) NOT NULL,
	USERSIDS  	BIGINT(20) UNSIGNED NOT NULL NOT NULL,
	DATEADDED 	DATE NOT NULL,
	INTADDEDBY	BIGINT(20) DEFAULT 0,
	GROUPSIDS 	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	INVISIBLE 	SMALLINT DEFAULT 0
	);

CREATE TABLE USERS  (
	IDS              	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME            	VARCHAR(250) NOT NULL,
	GROUPSIDS        	BIGINT(20) UNSIGNED NOT NULL DEFAULT 1,
	INTDEFAULTACCOUNT	BIGINT(20) DEFAULT 1,
	COMPSIDS         	BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	INTDEFAULTSTATUS 	BIGINT(20) DEFAULT 1,
	FULLNAME         	VARCHAR(250) NOT NULL,
	PASSWORD         	VARCHAR(250) NOT NULL,
	LAF              	VARCHAR(50) DEFAULT NULL,
	LOCALE           	VARCHAR(50) DEFAULT NULL,
	DEFCOUNTRY       	VARCHAR(50) DEFAULT NULL,
	MAIL             	VARCHAR(50) DEFAULT NULL,
	LANGUAGE         	VARCHAR(50) DEFAULT NULL,
	INTHIGHESTRIGHT  	SMALLINT DEFAULT 3,
	ISENABLED        	SMALLINT DEFAULT 1,
	ISRGROUPED       	SMALLINT DEFAULT 0,
	ISLOGGEDIN       	SMALLINT DEFAULT 0,
	DATELASTLOG      	DATE DEFAULT NULL,
	DATEADDED        	DATE NOT NULL,
	INTADDEDBY       	BIGINT(20) DEFAULT 0,
	INVISIBLE        	SMALLINT DEFAULT 0,
	RESERVE1         	VARCHAR(500) DEFAULT NULL,
	RESERVE2         	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE WEBSHOPS  (
	IDS                 	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	CNAME               	VARCHAR(250) NOT NULL,
	DESCRIPTION         	VARCHAR(750) DEFAULT NULL,
	GROUPSIDS           	BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
	DATEADDED           	DATE NOT NULL,
	ISREQUESTCOMPRESSION	SMALLINT DEFAULT 0,
	ISAUTHENTICATED     	SMALLINT DEFAULT 0,
	USERNAME            	VARCHAR(50) DEFAULT NULL,
	PASSW               	VARCHAR(50) DEFAULT NULL,
	RESERVE1            	VARCHAR(500) DEFAULT NULL,
	INTADDEDBY          	BIGINT(20) DEFAULT 0,
	INTERV               	BIGINT(20) DEFAULT 0,
	URL                 	VARCHAR(500) DEFAULT NULL,
	RESERVE2            	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE WSCONTACTSMAPPING  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	WEBSHOPSIDS	BIGINT(20) UNSIGNED NOT NULL ,
	CNAME      	VARCHAR(250) NOT NULL,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL ,
	CONTACTSIDS	BIGINT(20) UNSIGNED NOT NULL ,
	WSCONTACT  	VARCHAR(250) NOT NULL,
	DATEADDED  	DATE DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	INVISIBLE  	SMALLINT DEFAULT 0,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE TABLE WSITEMSMAPPING  (
	IDS        	BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY auto_increment,
	WEBSHOPSIDS	BIGINT(20) UNSIGNED NOT NULL ,
	CNAME      	VARCHAR(250) NOT NULL,
	GROUPSIDS  	BIGINT(20) UNSIGNED NOT NULL ,
	ITEMSIDS   	BIGINT(20) UNSIGNED NOT NULL ,
	WSITEM     	VARCHAR(250) NOT NULL,
	DATEADDED  	DATE DEFAULT NULL,
	INTADDEDBY 	BIGINT(20) DEFAULT 0,
	INVISIBLE  	SMALLINT DEFAULT 0,
	RESERVE1   	VARCHAR(500) DEFAULT NULL,
	RESERVE2   	VARCHAR(500) DEFAULT NULL
);

CREATE UNIQUE INDEX SQL091006084310810
	ON GROUPS(CNAME);

CREATE UNIQUE INDEX SQL091006084310820
	ON GROUPS(IDS);

CREATE UNIQUE INDEX SQL091006084311391
	ON PRODUCTGROUPS(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084311390
	ON PRODUCTGROUPS(IDS);

CREATE UNIQUE INDEX SQL091006084311800
	ON HISTORY(IDS);

CREATE UNIQUE INDEX SQL091006084312110
	ON COUNTRIES(ISO);

CREATE UNIQUE INDEX SQL091006084312111
	ON COUNTRIES(IDS);

CREATE UNIQUE INDEX SQL091006084312620
	ON GLOBALSETTINGS(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084312900
	ON TAX(IDS);

CREATE INDEX SQL091006084312890
	ON TAX(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084313452
	ON CONTACTS(CNUMBER, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084313451
	ON CONTACTS(IDS);

CREATE INDEX SQL091006084313450
	ON CONTACTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084313971
	ON USERS(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084313970
	ON USERS(IDS);

CREATE INDEX SQL091006084313960
	ON USERS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084314570
	ON FILES(CNAME);

CREATE UNIQUE INDEX SQL091006084314572
	ON FILES(IDS);

CREATE INDEX SQL091006084314571
	ON FILES(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084315174
	ON LANGUAGES(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084315171
	ON LANGUAGES(LONGNAME);

CREATE UNIQUE INDEX SQL091006084315173
	ON LANGUAGES(IDS);

CREATE INDEX SQL091006084315170
	ON LANGUAGES(GROUPSIDS);

CREATE INDEX SQL091006084315172
	ON LANGUAGES(FILENAME);

CREATE UNIQUE INDEX SQL091006084315882
	ON FAVOURITES(IDS);

CREATE INDEX SQL091006084315880
	ON FAVOURITES(USERSIDS);

CREATE INDEX SQL091006084315881
	ON FAVOURITES(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084316451
	ON ACCOUNTS(IDS);

CREATE INDEX SQL091006084316450
	ON ACCOUNTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084316862
	ON ITEMS(CNUMBER, INTTYPE);

CREATE UNIQUE INDEX SQL091006084316861
	ON ITEMS(IDS);

CREATE INDEX SQL091006084316850
	ON ITEMS(GROUPSIDS);

CREATE INDEX SQL091006084316851
	ON ITEMS(ACCOUNTSIDS);

CREATE INDEX SQL091006084316860
	ON ITEMS(CONTACTSIDS);

CREATE UNIQUE INDEX SQL091006084317902
	ON SUBITEMS(IDS);

CREATE INDEX SQL091006084317900
	ON SUBITEMS(ITEMSIDS);

CREATE INDEX SQL091006084317901
	ON SUBITEMS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084318483
	ON SCHEDULE(IDS);

CREATE INDEX SQL091006084318480
	ON SCHEDULE(GROUPSIDS);

CREATE INDEX SQL091006084318481
	ON SCHEDULE(USERSIDS);

CREATE INDEX SQL091006084318482
	ON SCHEDULE(ITEMSIDS);

CREATE UNIQUE INDEX SQL091006084319621
	ON PRODUCTS(CNUMBER, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084319620
	ON PRODUCTS(IDS);

CREATE INDEX SQL091006084319610
	ON PRODUCTS(TAXIDS);

CREATE INDEX SQL091006084319611
	ON PRODUCTS(GROUPSIDS);

CREATE INDEX SQL091006084319612
	ON PRODUCTS(PRODUCTGROUPSIDS);

CREATE UNIQUE INDEX SQL091006084320591
	ON PRODUCTLISTS(IDS);

CREATE INDEX SQL091006084320590
	ON PRODUCTLISTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084321141
	ON PRODUCTLISTITEMS(IDS);

CREATE INDEX SQL091006084321130
	ON PRODUCTLISTITEMS(GROUPSIDS);

CREATE INDEX SQL091006084321131
	ON PRODUCTLISTITEMS(PRODUCTLISTSIDS);

CREATE INDEX SQL091006084321140
	ON PRODUCTLISTITEMS(ORIGINALPRODUCTSIDS);

CREATE INDEX SQL091006084322190
	ON USERPROPERTIES(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084322552
	ON MAILS(IDS);

CREATE INDEX SQL091006084322550
	ON MAILS(GROUPSIDS);

CREATE INDEX SQL091006084322551
	ON MAILS(USERSIDS);

CREATE UNIQUE INDEX SQL091006084323381
	ON COMPS(IDS);

CREATE INDEX SQL091006084323380
	ON COMPS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084324160
	ON EXPENSES(IDS);

CREATE INDEX SQL091006084324140
	ON EXPENSES(GROUPSIDS);

CREATE INDEX SQL091006084324141
	ON EXPENSES(ACCOUNTSIDS);

CREATE UNIQUE INDEX SQL091006084324810
	ON REVENUES(IDS);

CREATE INDEX SQL091006084324790
	ON REVENUES(GROUPSIDS);

CREATE INDEX SQL091006084324800
	ON REVENUES(ACCOUNTSIDS);

CREATE UNIQUE INDEX SQL091006084325551
	ON WEBSHOPS(CNAME, GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084325550
	ON WEBSHOPS(IDS);

CREATE UNIQUE INDEX SQL091006084326054
	ON WSCONTACTSMAPPING(WSCONTACT, GROUPSIDS, WEBSHOPSIDS);

CREATE UNIQUE INDEX SQL091006084326053
	ON WSCONTACTSMAPPING(IDS);

CREATE INDEX SQL091006084326050
	ON WSCONTACTSMAPPING(WEBSHOPSIDS);

CREATE INDEX SQL091006084326051
	ON WSCONTACTSMAPPING(GROUPSIDS);

CREATE INDEX SQL091006084326052
	ON WSCONTACTSMAPPING(CONTACTSIDS);

CREATE UNIQUE INDEX SQL091006084326881
	ON WSITEMSMAPPING(WSITEM, GROUPSIDS, WEBSHOPSIDS);

CREATE UNIQUE INDEX SQL091006084326880
	ON WSITEMSMAPPING(IDS);

CREATE INDEX SQL091006084326870
	ON WSITEMSMAPPING(WEBSHOPSIDS);

CREATE INDEX SQL091006084326871
	ON WSITEMSMAPPING(GROUPSIDS);

CREATE INDEX SQL091006084326872
	ON WSITEMSMAPPING(ITEMSIDS);

CREATE UNIQUE INDEX SQL091006084327910
	ON TABLELOCK(IDS);

CREATE UNIQUE INDEX SQL091006084327911
	ON TABLELOCK(CNAME, ROWID);

CREATE INDEX SQL091006084327890
	ON TABLELOCK(USERSIDS);

CREATE UNIQUE INDEX SQL091006084328480
	ON ITEMSTOACCOUNTS(IDS);

CREATE INDEX SQL091006084328460
	ON ITEMSTOACCOUNTS(ITEMSIDS);

CREATE INDEX SQL091006084328461
	ON ITEMSTOACCOUNTS(ACCOUNTSIDS);

CREATE UNIQUE INDEX SQL091006084329120
	ON TRASHBIN(IDS);

CREATE UNIQUE INDEX SQL091006084329671
	ON FILESTOCONTACTS(IDS);

CREATE INDEX SQL091006084329650
	ON FILESTOCONTACTS(CONTACTSIDS);

CREATE INDEX SQL091006084329651
	ON FILESTOCONTACTS(FILENAME);

CREATE INDEX SQL091006084329670
	ON FILESTOCONTACTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084330492
	ON TEMPLATES(IDS);

CREATE INDEX SQL091006084330490
	ON TEMPLATES(FILENAME);

CREATE INDEX SQL091006084330491
	ON TEMPLATES(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084331263
	ON FILESTOITEMS(IDS);

CREATE INDEX SQL091006084331260
	ON FILESTOITEMS(ITEMSIDS);

CREATE INDEX SQL091006084331261
	ON FILESTOITEMS(FILENAME);

CREATE INDEX SQL091006084331262
	ON FILESTOITEMS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084332163
	ON FILESTOPRODUCTS(IDS);

CREATE INDEX SQL091006084332160
	ON FILESTOPRODUCTS(PRODUCTSIDS);

CREATE INDEX SQL091006084332161
	ON FILESTOPRODUCTS(FILENAME);

CREATE INDEX SQL091006084332162
	ON FILESTOPRODUCTS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084333560
	ON PLUGINS(IDS);

CREATE INDEX SQL091006084333550
	ON PLUGINS(FILENAME);

CREATE INDEX SQL091006084333551
	ON PLUGINS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084334241
	ON PLUGINSTOUSERS(IDS);

CREATE INDEX SQL091006084334230
	ON PLUGINSTOUSERS(PLUGINSIDS);

CREATE INDEX SQL091006084334240
	ON PLUGINSTOUSERS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084334891
	ON FORMATSTOUSERS(IDS);

CREATE INDEX SQL091006084334890
	ON FORMATSTOUSERS(USERSIDS);

CREATE UNIQUE INDEX SQL091006084335461
	ON TEMPLATESTOUSERS(IDS);

CREATE INDEX SQL091006084335450
	ON TEMPLATESTOUSERS(USERSIDS);

CREATE INDEX SQL091006084335451
	ON TEMPLATESTOUSERS(TEMPLATESIDS);

CREATE INDEX SQL091006084335460
	ON TEMPLATESTOUSERS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084336332
	ON ADDRESSES(IDS);

CREATE INDEX SQL091006084336330
	ON ADDRESSES(GROUPSIDS);

CREATE INDEX SQL091006084336331
	ON ADDRESSES(CONTACTSIDS);

CREATE UNIQUE INDEX SQL091006084336882
	ON REMINDERS(IDS);

CREATE INDEX SQL091006084336880
	ON REMINDERS(ITEMSIDS);

CREATE INDEX SQL091006084336881
	ON REMINDERS(GROUPSIDS);

CREATE UNIQUE INDEX SQL091006084337581
	ON STAGES(IDS);

CREATE INDEX SQL091006084337580
	ON STAGES(GROUPSIDS);

ALTER TABLE CONTACTS
	ADD CONSTRAINT CONST3
	 UNIQUE (CNUMBER, GROUPSIDS) ;

ALTER TABLE COUNTRIES
	ADD CONSTRAINT SQL0910060843121101
	 UNIQUE (ISO) ;

ALTER TABLE FILES
	ADD CONSTRAINT SQL0910060843145701
	 UNIQUE (CNAME) ;

ALTER TABLE GLOBALSETTINGS
	ADD CONSTRAINT CONST2
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE GROUPS
	ADD CONSTRAINT SQL0910060843108101
	 UNIQUE (CNAME) ;

ALTER TABLE ITEMS
	ADD CONSTRAINT CONST7
	 UNIQUE (CNUMBER, INTTYPE) ;

ALTER TABLE LANGUAGES
	ADD CONSTRAINT SQL0910060843151711
	 UNIQUE (LONGNAME) ;

ALTER TABLE LANGUAGES
	ADD CONSTRAINT CONST6
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE PRODUCTGROUPS
	ADD CONSTRAINT CONST1
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE PRODUCTS
	ADD CONSTRAINT CONST8
	 UNIQUE (CNUMBER, GROUPSIDS) ;

ALTER TABLE TABLELOCK
	ADD CONSTRAINT ONE_LOCK
	 UNIQUE (CNAME, ROWID) ;

ALTER TABLE USERS
	ADD CONSTRAINT CONST4
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE WEBSHOPS
	ADD CONSTRAINT CONST9
	 UNIQUE (CNAME, GROUPSIDS) ;

ALTER TABLE WSCONTACTSMAPPING
	ADD CONSTRAINT CONST10
	 UNIQUE (WSCONTACT, GROUPSIDS, WEBSHOPSIDS) ;

ALTER TABLE WSITEMSMAPPING
	ADD CONSTRAINT CONST11
	 UNIQUE (WSITEM, GROUPSIDS, WEBSHOPSIDS) ;

ALTER TABLE ACCOUNTS
	ADD CONSTRAINT SQL0910060843164501
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE ADDRESSES
	ADD CONSTRAINT SQL0910060843363311
	FOREIGN KEY(CONTACTSIDS)
	REFERENCES CONTACTS(IDS);

ALTER TABLE ADDRESSES
	ADD CONSTRAINT SQL0910060843363301
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE COMPS
	ADD CONSTRAINT SQL0910060843233801
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE CONTACTS
	ADD CONSTRAINT SQL0910060843134501
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE EXPENSES
	ADD CONSTRAINT SQL0910060843241411
	FOREIGN KEY(ACCOUNTSIDS)
	REFERENCES ACCOUNTS(IDS);

ALTER TABLE EXPENSES
	ADD CONSTRAINT SQL0910060843241401
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FAVOURITES
	ADD CONSTRAINT SQL0910060843158811
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FAVOURITES
	ADD CONSTRAINT SQL0910060843158801
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE FILES
	ADD CONSTRAINT SQL0910060843145711
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FILESTOCONTACTS
	ADD CONSTRAINT SQL0910060843296701
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FILESTOCONTACTS
	ADD CONSTRAINT SQL0910060843296511
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOCONTACTS
	ADD CONSTRAINT SQL0910060843296501
	FOREIGN KEY(CONTACTSIDS)
	REFERENCES CONTACTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOITEMS
	ADD CONSTRAINT SQL0910060843312621
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FILESTOITEMS
	ADD CONSTRAINT SQL0910060843312611
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOITEMS
	ADD CONSTRAINT SQL0910060843312601
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOPRODUCTS
	ADD CONSTRAINT SQL0910060843321621
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE FILESTOPRODUCTS
	ADD CONSTRAINT SQL0910060843321611
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE FILESTOPRODUCTS
	ADD CONSTRAINT SQL0910060843321601
	FOREIGN KEY(PRODUCTSIDS)
	REFERENCES PRODUCTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE FORMATSTOUSERS
	ADD CONSTRAINT SQL0910060843348901
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE ITEMS
	ADD CONSTRAINT SQL0910060843168601
	FOREIGN KEY(CONTACTSIDS)
	REFERENCES CONTACTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE ITEMS
	ADD CONSTRAINT SQL0910060843168511
	FOREIGN KEY(ACCOUNTSIDS)
	REFERENCES ACCOUNTS(IDS);

ALTER TABLE ITEMS
	ADD CONSTRAINT SQL0910060843168501
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE ITEMSTOACCOUNTS
	ADD CONSTRAINT SQL0910060843284611
	FOREIGN KEY(ACCOUNTSIDS)
	REFERENCES ACCOUNTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE ITEMSTOACCOUNTS
	ADD CONSTRAINT SQL0910060843284601
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE LANGUAGES
	ADD CONSTRAINT SQL0910060843151721
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE LANGUAGES
	ADD CONSTRAINT SQL0910060843151701
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE MAILS
	ADD CONSTRAINT SQL0910060843225511
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE MAILS
	ADD CONSTRAINT SQL0910060843225501
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PLUGINS
	ADD CONSTRAINT SQL0910060843335511
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PLUGINS
	ADD CONSTRAINT SQL0910060843335501
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE PLUGINSTOUSERS
	ADD CONSTRAINT SQL0910060843342401
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PLUGINSTOUSERS
	ADD CONSTRAINT SQL0910060843342301
	FOREIGN KEY(PLUGINSIDS)
	REFERENCES PLUGINS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE PRODUCTLISTITEMS
	ADD CONSTRAINT SQL0910060843211401
	FOREIGN KEY(ORIGINALPRODUCTSIDS)
	REFERENCES PRODUCTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE PRODUCTLISTITEMS
	ADD CONSTRAINT SQL0910060843211311
	FOREIGN KEY(PRODUCTLISTSIDS)
	REFERENCES PRODUCTLISTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE PRODUCTLISTITEMS
	ADD CONSTRAINT SQL0910060843211301
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PRODUCTLISTS
	ADD CONSTRAINT SQL0910060843205901
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PRODUCTS
	ADD CONSTRAINT SQL0910060843196121
	FOREIGN KEY(PRODUCTGROUPSIDS)
	REFERENCES PRODUCTGROUPS(IDS);

ALTER TABLE PRODUCTS
	ADD CONSTRAINT SQL0910060843196111
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE PRODUCTS
	ADD CONSTRAINT SQL0910060843196101
	FOREIGN KEY(TAXIDS)
	REFERENCES TAX(IDS);

ALTER TABLE REMINDERS
	ADD CONSTRAINT SQL0910060843368811
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE REMINDERS
	ADD CONSTRAINT SQL0910060843368801
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE REVENUES
	ADD CONSTRAINT SQL0910060843248001
	FOREIGN KEY(ACCOUNTSIDS)
	REFERENCES ACCOUNTS(IDS);

ALTER TABLE REVENUES
	ADD CONSTRAINT SQL0910060843247901
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE SCHEDULE
	ADD CONSTRAINT SQL0910060843184821
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE SCHEDULE
	ADD CONSTRAINT SQL0910060843184811
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE SCHEDULE
	ADD CONSTRAINT SQL0910060843184801
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE STAGES
	ADD CONSTRAINT SQL0910060843375801
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE SUBITEMS
	ADD CONSTRAINT SQL0910060843179011
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE SUBITEMS
	ADD CONSTRAINT SQL0910060843179001
	FOREIGN KEY(ITEMSIDS)
	REFERENCES ITEMS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE TABLELOCK
	ADD CONSTRAINT SQL0910060843278901
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE TAX
	ADD CONSTRAINT SQL0910060843128901
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE TEMPLATES
	ADD CONSTRAINT SQL0910060843304911
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE TEMPLATES
	ADD CONSTRAINT SQL0910060843304901
	FOREIGN KEY(FILENAME)
	REFERENCES FILES(CNAME)
	ON DELETE CASCADE ;

ALTER TABLE TEMPLATESTOUSERS
	ADD CONSTRAINT SQL0910060843354601
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE TEMPLATESTOUSERS
	ADD CONSTRAINT SQL0910060843354511
	FOREIGN KEY(TEMPLATESIDS)
	REFERENCES TEMPLATES(IDS)
	ON DELETE CASCADE ;

ALTER TABLE TEMPLATESTOUSERS
	ADD CONSTRAINT SQL0910060843354501
	FOREIGN KEY(USERSIDS)
	REFERENCES USERS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE USERPROPERTIES
	ADD CONSTRAINT SQL0910060843221901
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE USERS
	ADD CONSTRAINT SQL0910060843139601
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS);

ALTER TABLE WSCONTACTSMAPPING
	ADD CONSTRAINT SQL0910060843260521
	FOREIGN KEY(CONTACTSIDS)
	REFERENCES CONTACTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSCONTACTSMAPPING
	ADD CONSTRAINT SQL0910060843260511
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSCONTACTSMAPPING
	ADD CONSTRAINT SQL0910060843260501
	FOREIGN KEY(WEBSHOPSIDS)
	REFERENCES WEBSHOPS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSITEMSMAPPING
	ADD CONSTRAINT SQL0910060843268721
	FOREIGN KEY(ITEMSIDS)
	REFERENCES CONTACTS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSITEMSMAPPING
	ADD CONSTRAINT SQL0910060843268711
	FOREIGN KEY(GROUPSIDS)
	REFERENCES GROUPS(IDS)
	ON DELETE CASCADE ;

ALTER TABLE WSITEMSMAPPING
	ADD CONSTRAINT SQL0910060843268701
	FOREIGN KEY(WEBSHOPSIDS)
	REFERENCES WEBSHOPS(IDS)
	ON DELETE CASCADE ;



DELIMITER %

CREATE TRIGGER CONTACTS_INDEXER1
	AFTER INSERT ON CONTACTS

	FOR EACH ROW BEGIN
	INSERT INTO searchindex (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids, 'contacts',NEW.ids,NEW.cnumber||' '||NEW.taxnumber||' '||NEW.title||' '||NEW.country||' '|| NEW.prename||' '|| NEW.cname||' '|| NEW.street||' '||NEW.zip||' '|| NEW.city ||' '||NEW.mainphone||' '||NEW.fax||' '||NEW.mobilephone||' '||NEW.workphone||' '||NEW.mailaddress||' '||NEW.company||' '|| NEW.department||' '||NEW.website||' '||NEW.notes);
END;
	%

CREATE TRIGGER CONTACTS_INDEXER2
	AFTER UPDATE ON CONTACTS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'contacts' AND  rowid = NEW.ids;
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'contacts',NEW.ids,NEW.cnumber||' '||NEW.taxnumber||' '||NEW.title||' '||NEW.country||' '|| NEW.prename||' '|| NEW.cname||' '|| NEW.street||' '||NEW.zip||' '|| NEW.city ||' '||NEW.mainphone||' '||NEW.fax||' '||NEW.mobilephone||' '||NEW.workphone||' '||NEW.mailaddress||' '||NEW.company||' '|| NEW.department||' '||NEW.website||' '||NEW.notes);
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (NEW.invisible,'contacts',NEW.ids,NEW.cnumber||' ('|| NEW.cname||')');
END;
%

CREATE TRIGGER CONTACTS_INDEXER4
	AFTER DELETE ON CONTACTS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'contacts' AND  rowid = OLD.ids;
	DELETE FROM trashbin WHERE cname = 'contacts' AND  rowid = OLD.ids;
END;
%

CREATE TRIGGER EXPENSES_INDEXER1
	AFTER INSERT ON EXPENSES

	FOR EACH ROW BEGIN
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'expenses',NEW.ids,NEW.cname||' '||NEW.dateadded);
END;
	%
CREATE TRIGGER EXPENSES_INDEXER2
	AFTER UPDATE ON EXPENSES

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'expenses' AND  rowid = NEW.ids;
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'expenses',NEW.ids,NEW.cname||' '||NEW.dateadded);
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (NEW.invisible,'expenses',NEW.ids,NEW.cname);
END;
%

CREATE TRIGGER EXPENSES_INDEXER4
	AFTER DELETE ON EXPENSES

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'expenses' AND  rowid = OLD.ids;
	DELETE FROM trashbin WHERE cname = 'expenses' AND  rowid = OLD.ids;
END;
%

CREATE TRIGGER FILESTOCONTACTS_INDEXER1
	AFTER INSERT ON FILESTOCONTACTS

	FOR EACH ROW BEGIN
	INSERT INTO searchindex (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'filestocontacts',NEW.ids,NEW.cname||' '||NEW.description||' '||NEW.filename);
END;
	%
CREATE TRIGGER FILESTOCONTACTS_INDEXER2
	AFTER UPDATE ON FILESTOCONTACTS

	FOR EACH ROW BEGIN
  DELETE FROM searchindex WHERE dbidentity = 'filestocontacts' AND  rowid = NEW.ids;
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'filestocontacts',NEW.ids,NEW.cname||' '||NEW.description||' '||NEW.filename);
END;
	%

CREATE TRIGGER FILESTOCONTACTS_INDEXER4
	AFTER DELETE ON FILESTOCONTACTS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'filestocontacts' AND  rowid = OLD.ids;

	END;
	%
CREATE TRIGGER GROUPS_INDEXER1
	AFTER INSERT ON GROUPS

	FOR EACH ROW BEGIN
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'groups',NEW.ids,NEW.cname||' '||NEW.description||' '||NEW.dateadded);
END;
	%
CREATE TRIGGER GROUPS_INDEXER2
	AFTER UPDATE ON GROUPS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'groups' AND  rowid = NEW.ids;
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'groups',NEW.ids,NEW.cname||' '||NEW.description||' '||NEW.dateadded);
END;
%
CREATE TRIGGER GROUPS_INDEXER4
	AFTER DELETE ON GROUPS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'groups' AND  rowid = OLD.ids;
END;
	%
CREATE TRIGGER ITEMS_INDEXER1
	AFTER INSERT ON ITEMS

	FOR EACH ROW BEGIN
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'items',NEW.ids,NEW.cname||' '||NEW.dateadded);
END;
	%
CREATE TRIGGER ITEMS_INDEXER2
	AFTER UPDATE ON ITEMS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'items' AND  rowid = NEW.ids;
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'items',NEW.ids,NEW.cname||' '||NEW.dateadded);
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (NEW.invisible,'items',NEW.ids,NEW.cname);
END;
%

CREATE TRIGGER ITEMS_INDEXER4
	AFTER DELETE ON ITEMS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'items' AND  rowid = OLD.ids;
  DELETE FROM trashbin WHERE cname = 'items' AND  rowid = OLD.ids;
END;
	%

CREATE TRIGGER PRODUCTS_INDEXER1
	AFTER INSERT ON PRODUCTS

	FOR EACH ROW BEGIN
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'products',NEW.ids,NEW.cname||' '||NEW.cnumber||' '||NEW.description||' '||NEW.dateadded);
END;
	%
CREATE TRIGGER PRODUCTS_INDEXER2
	AFTER UPDATE ON PRODUCTS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'products' AND  rowid = NEW.ids;
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'products',NEW.ids,NEW.cname||' '||NEW.cnumber||' '||NEW.description||' '||NEW.dateadded);
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (NEW.invisible, 'products',NEW.ids,NEW.cnumber||' ('|| NEW.cname||')');
END;
%

CREATE TRIGGER PRODUCTS_INDEXER4
	AFTER DELETE ON PRODUCTS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'products' AND  rowid = OLD.ids;
	DELETE FROM trashbin WHERE cname = 'products' AND  rowid = OLD.ids;
END;
	%


CREATE TRIGGER REVENUES_INDEXER1
	AFTER INSERT ON REVENUES

	FOR EACH ROW BEGIN
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'revenues',NEW.ids,NEW.cname||' '||NEW.dateadded);
END;
	%
CREATE TRIGGER REVENUES_INDEXER2
	AFTER UPDATE ON REVENUES

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'revenues' AND  rowid = NEW.ids;
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'revenues',NEW.ids,NEW.cname||' '||NEW.dateadded);
	INSERT INTO trashbin (deleteme, cname, rowid, description) VALUES (NEW.invisible,'revenues',NEW.ids,NEW.cname);
END;
	%
CREATE TRIGGER REVENUES_INDEXER4
	AFTER DELETE ON REVENUES

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'revenues' AND  rowid = OLD.ids;
	DELETE FROM trashbin WHERE cname = 'revenues' AND  rowid = OLD.ids;
END;
%
CREATE TRIGGER SUBITEMS_INDEXER1
	AFTER INSERT ON SUBITEMS

	FOR EACH ROW BEGIN
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'subitems',NEW.ids,NEW.cname||' '||NEW.description||' '||NEW.dateadded);
END;
	%
CREATE TRIGGER SUBITEMS_INDEXER2
	AFTER UPDATE ON SUBITEMS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'subitems' AND  rowid = NEW.ids;
	INSERT INTO searchindex  (groupsids, dbidentity, rowid, text) VALUES (NEW.groupsids,'subitems',NEW.ids,NEW.cname||' '||NEW.description||' '||NEW.dateadded);
END;
	%

CREATE TRIGGER SUBITEMS_INDEXER4
	AFTER DELETE ON SUBITEMS

	FOR EACH ROW BEGIN
	DELETE FROM searchindex WHERE dbidentity = 'subitems' AND  rowid = OLD.ids;
END;
	%
#Does not work in mysql!
#CREATE TRIGGER THRASH_HANDLER1
#	AFTER INSERT ON TRASHBIN
#	FOR EACH ROW BEGIN
#	DELETE FROM trashbin WHERE deleteme = 0;
#	DELETE FROM trashbin WHERE ids IN (SELECT ids FROM trashbin WHERE EXISTS( SELECT ids FROM trashbin AS tmptable WHERE trashbin.cname = tmptable.cname AND trashbin.rowid = tmptable.rowid HAVING trashbin.ids < MAX(tmptable.ids) ) );
#END;
#%
DELIMITER ;


INSERT INTO GROUPS(CNAME, DESCRIPTION, DEFAULTS, GROUPSIDS, DATEADDED, RESERVE1, INTADDEDBY, HIERARCHYPATH, RESERVE2)
  VALUES( 'All Groups', 'This group is visible to everyone.', NULL, 0, '2009-04-03', NULL, 0, NULL, NULL);
INSERT INTO ACCOUNTS(INTACCOUNTCLASS, CNAME, DESCRIPTION, TAXVALUE, DATEADDED, INTADDEDBY, INTPARENTACCOUNT, GROUPSIDS, INVISIBLE, INTACCOUNTTYPE, INTPROFITFID, INTTAXFID, INTTAXUID, FRAME, HIERARCHYPATH)
  VALUES( 0, 'All Accounts', 'This account is the parent account of all account frames.', 0.0, '2009-04-03', 0, 0, 1, 0, 0, 0, 0, 0, 'builtin', NULL);
INSERT INTO ACCOUNTS(INTACCOUNTCLASS, CNAME, DESCRIPTION, TAXVALUE, DATEADDED, INTADDEDBY, INTPARENTACCOUNT, GROUPSIDS, INVISIBLE, INTACCOUNTTYPE, INTPROFITFID, INTTAXFID, INTTAXUID, FRAME, HIERARCHYPATH)
  VALUES( 0, 'Expenses', '', 0.0, '2009-04-03', 0, 1, 1, 0, 2, 0, 0, 0, 'builtin', NULL);
INSERT INTO ACCOUNTS(INTACCOUNTCLASS, CNAME, DESCRIPTION, TAXVALUE, DATEADDED, INTADDEDBY, INTPARENTACCOUNT, GROUPSIDS, INVISIBLE, INTACCOUNTTYPE, INTPROFITFID, INTTAXFID, INTTAXUID, FRAME, HIERARCHYPATH)
  VALUES( 0, 'Income', '', 0.0, '2009-04-03', 0, 1, 1, 0, 3, 0, 0, 0, 'builtin', NULL);
INSERT INTO COUNTRIES(CNAME, ISO, GROUPSIDS, RESERVE1, RESERVE2)
  VALUES( 'Deutschland', 276, 1, NULL, NULL);
INSERT INTO GLOBALSETTINGS(CNAME, GROUPSIDS, VALUE)
  VALUES( 'yabs_dbversion', 1, '1.0');
INSERT INTO PRODUCTGROUPS(CNAME, DESCRIPTION, DEFAULTS, GROUPSIDS, PRODUCTGROUPSIDS, DATEADDED, HIERARCHYPATH, RESERVE1, INTADDEDBY, RESERVE2)
  VALUES( 'All Products', 'This product group is visible to everyone.', NULL, 0, 0, '2009-04-03', NULL, NULL, 0, NULL);
INSERT INTO SEARCHINDEX(DBIDENTITY, GROUPSIDS, ROWID, TEXT)
  VALUES( 'groups', 0, 1, 'All Groups This group is visible to everyone. 2009-04-03');
INSERT INTO TAX(CNAME, TAXVALUE, IDENTIFIER, GROUPSIDS, COUNTRY, DATEADDED, INTADDEDBY, INVISIBLE, RESERVE1, RESERVE2)
  VALUES( 'Default 0%', 0.0, 'Default 0%', 1, NULL, '2009-04-03', 0, 0, NULL, NULL);
INSERT INTO TAX(CNAME, TAXVALUE, IDENTIFIER, GROUPSIDS, COUNTRY, DATEADDED, INTADDEDBY, INVISIBLE, RESERVE1, RESERVE2)
  VALUES( 'Default 19%', 19.0, 'Default 19%', 1, NULL, '2009-04-03', 0, 0, NULL, NULL);
INSERT INTO TAX( CNAME, TAXVALUE, IDENTIFIER, GROUPSIDS, COUNTRY, DATEADDED, INTADDEDBY, INVISIBLE, RESERVE1, RESERVE2)
  VALUES( 'Default 7%', 7.0, 'Default 7%', 1, NULL, '2009-04-03', 0, 0, NULL, NULL);
INSERT INTO USERS(CNAME, GROUPSIDS, INTDEFAULTACCOUNT, COMPSIDS, INTDEFAULTSTATUS, FULLNAME, PASSWORD, LAF, LOCALE, DEFCOUNTRY, MAIL, LANGUAGE, INTHIGHESTRIGHT, ISENABLED, ISRGROUPED, ISLOGGEDIN, DATELASTLOG, DATEADDED, INTADDEDBY, INVISIBLE, RESERVE1, RESERVE2)
  VALUES( 'admin', 1, 1, 0, 1, 'Administrator', '5f4dcc3b5aa765d61d8327deb882cf99', 'com.sun.java.swing.plaf.windows.WindowsLookAndFeel', 'en_GB', '', '', 'buildin_en', 0, 1, 0, 0, '2009-10-06', '2009-04-03', 0, 0, NULL, NULL);