/*
 * * This file is an extension part of MP by anti43 /GPL.
 *
 * MP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MP. If not, see <http://www.gnu.org/licenses/>.
 *
 * TaxFormDialog.java
 *
 * Created on 15.03.2009
 */
package mpv5.ui.dialogs;

import java.awt.Component;
import java.awt.Frame;
import javax.swing.text.JTextComponent;
import mpv5.utils.models.AccountCalcModel;

/**
 * The dialog frame for personal data.
 * @author hnauheim
 */
public class TaxAddressDialog extends javax.swing.JDialog {

  private AccountCalcModel model;

  /** Creates new form TaxFormDialog
   * @param The root pane
   * @param The visible frame title
   * @param model The taxModel to use
   */
  public TaxAddressDialog(Frame parent, String title, AccountCalcModel model) {
    super(parent, title, true);
    super.setBounds(200, 200, 200, 200);
    super.setResizable(false);
    this.model = model;
    initComponents();
    getData();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    streetField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    taxnumberField = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    profField = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    mandantField = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    cityField = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    faArea = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    stbArea = new javax.swing.JTextArea();
    jLabel10 = new javax.swing.JLabel();
    phone2Field = new javax.swing.JTextField();
    phone1Field = new javax.swing.JTextField();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    nameField1 = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    nameField2 = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    mandantField1 = new javax.swing.JTextField();
    zipcodefield = new javax.swing.JFormattedTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mpv5/resources/languages/Panels"); // NOI18N
    jLabel1.setText(bundle.getString("TaxAddressDialog.compname")); // NOI18N

    nameField.setToolTipText("Name des Unternehmers/Firma");
    nameField.setName("compname"); // NOI18N

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel2.setText("Straße, Hausnr.");

    streetField.setToolTipText("Straße und Hausnummer des Unternehmens");
    streetField.setName("street"); // NOI18N

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel3.setText("Finanzamt");

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel4.setText("Bundesland");

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel5.setText("Steuernummer");

    taxnumberField.setToolTipText("Beispiel: 123/123/12345");

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel6.setText("Berufsbez. falls Berater");

    profField.setToolTipText("Nur von Steuerberatern o. ä. auszufüllen");

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel7.setText("Mandantenname falls Berater");

    mandantField.setToolTipText("Nur ausfüllen, falls die Meldung von einem Steuerberater o. ä. erstellt wurde");

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel8.setText("Tel.-Vorwahl, Tel.-Nr.");

    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel9.setText("PLZ, Ort");

    cityField.setToolTipText("Firmenort");

    faArea.setColumns(20);
    faArea.setRows(5);
    faArea.setToolTipText("Anschrift des zust. Finanzamtes (mehrzeilig)");
    faArea.setName("fa"); // NOI18N
    jScrollPane1.setViewportView(faArea);

    stbArea.setColumns(20);
    stbArea.setRows(5);
    stbArea.setToolTipText("Anschrift des zust. Steuerberaters (mehrzeilig)");
    jScrollPane2.setViewportView(stbArea);

    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel10.setText("Steuerberater");

    cancelButton.setText("Abbrechen");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    okButton.setText("OK");
    okButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okButtonActionPerformed(evt);
      }
    });

    nameField1.setToolTipText("Name des Unternehmers/Firma");
    nameField1.setName("firstname"); // NOI18N

    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel11.setText(bundle.getString("TaxAddressDialog.firstname")); // NOI18N

    nameField2.setToolTipText("Name des Unternehmers/Firma");

    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel12.setText("Name");

    mandantField1.setToolTipText("Nur ausfüllen, falls die Meldung von einem Steuerberater o. ä. erstellt wurde");

    try {
      zipcodefield.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    zipcodefield.setName("zipcode"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel11)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1)
              .addComponent(jLabel9))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(profField)
              .addComponent(nameField)
              .addComponent(streetField)
              .addGroup(layout.createSequentialGroup()
                .addComponent(zipcodefield, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(phone1Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(taxnumberField)
              .addComponent(nameField1)
              .addComponent(nameField2))
            .addGap(12, 12, 12))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabel7)
                  .addComponent(jLabel6)
                  .addComponent(jLabel8)
                  .addComponent(jLabel5)
                  .addComponent(jLabel4)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                  .addComponent(mandantField, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                  .addComponent(mandantField1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, mandantField, mandantField1, nameField, profField, streetField, taxnumberField});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(nameField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel12)))
              .addComponent(jLabel11)))
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9)
          .addComponent(zipcodefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(phone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(phone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(taxnumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(profField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(mandantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(mandantField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel4)))
          .addComponent(jLabel7))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(okButton)
              .addComponent(cancelButton)))
          .addComponent(jLabel10))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    setData();
    setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    setVisible(false);
  }//GEN-LAST:event_cancelButtonActionPerformed

  public  String[][] getData() {
    Component[] comps = getContentPane().getComponents();
    String[][] arr = new String[(comps.length/2)][2];
    int j = 0;
    for (int i = 0; i < comps.length; i++) {
      if (comps[i] instanceof JTextComponent) {
        JTextComponent comp = (JTextComponent) comps[i];
        arr[j][0] = comp.getName();
        arr[j][1] = comp.getText();
//        System.out.println(arr[j][0] + ":  " + arr[j][1]);
      j++;
//      }  if (comps[i] instanceof JTextArea) {
//        System.out.println("testarea");
      }
    }
    return arr;
//    }
  }

  private void setData() {
//    model.setCompany(nameField.getText());
//    model.setCompany_street(streetField.getText());
//    model.setCompany_plz(zipcodeField.getText());
//    model.setCompany_city(cityField.getText());
//    model.setPhone1(phone1Field.getText());
//    model.setPhone2(phone2Field.getText());
//    model.setSteuernr(taxnumberField.getText());
//    model.setProfession(profField.getText());
//    model.setMandant(mandantField.getText());
//    model.setFa_address(faArea.getText());
//    model.setStb_address(stbArea.getText());
//    for (int i = 0; i < model.getRegions().length; i++) {
//      if (regionSpinner.getValue().equals(model.getRegions()[i])) {
//        model.setRegion(i + "");
//      }
//    }
//    model.saveAddress();

    Component[] comps = getContentPane().getComponents();
    for (int i = 0; i < comps.length; i++) {
      if (comps[i] instanceof JTextComponent) {
        JTextComponent comp = (JTextComponent) comps[i];
//        System.out.println(comp.getName() + ":  " + comp.getText());
      }
    }

  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      @Override
      public void run() {
//        ProfitModel model = new ProfitModel(null);
        TaxAddressDialog dialog = new TaxAddressDialog(new javax.swing.JFrame(), "bla", null);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {

          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextField cityField;
  private javax.swing.JTextArea faArea;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextField mandantField;
  private javax.swing.JTextField mandantField1;
  private javax.swing.JTextField nameField;
  private javax.swing.JTextField nameField1;
  private javax.swing.JTextField nameField2;
  private javax.swing.JButton okButton;
  private javax.swing.JTextField phone1Field;
  private javax.swing.JTextField phone2Field;
  private javax.swing.JTextField profField;
  private javax.swing.JTextArea stbArea;
  private javax.swing.JTextField streetField;
  private javax.swing.JTextField taxnumberField;
  private javax.swing.JFormattedTextField zipcodefield;
  // End of variables declaration//GEN-END:variables
}
